### ISSUE TITLE
CP not properly saving nested lists in MD

### ISSUE THREAD

**Issue by c-fitzmaurice** [statamic/v2-hub#1030]
# The problem:

When saving a nested list in the CP the nesting is ignored and the MD file is saved as a regular list. When I edit the MD file directly, the CP shows the correct sytax and is rendered in the browser correctly. When I head back to the CP and re-save the file, it again overwrites the nested MD list into a single list.

**Note**: I am on Statamic v2.1.14

Being displayed in the template as the following: `{{ description | markdown }}`
### The fieldset

```
title: Jobs
create_title: New Job Post
fields:
  position:
    type: text
    display: Position
    instructions: What title did you have?
    width: 50
    validate: required
  website:
    type: text
    display: Website
    instructions: Website of the company
    width: 50
    validate: required
  project_link:
    type: text
    display: Project Link
    instructions: Link to the project on this website
    width: 50
  start_date:
    type: date
    display: Start Date
    instructions: Date you started
    allow_blank: false
    allow_time: false
    earliest_date: January 1, 1900
    width: 25
    validate: date
  end_date:
    type: date
    display: end_date
    instructions: Date you left the company
    allow_blank: true
    allow_time: false
    earliest_date: January 1, 1900
    width: 25
    validate: date
  description:
    type: markdown
    display: Description
    instructions: What I did while employeed
    cheatsheet: true
    container: main
    folder: jobs
    validate: required
```
### The Data

```
position: The Job Title
website: https://www.google.com
start_date: 2015-04-01
end_date: 2016-05-01
description: |
  - This is the list that I am having problems with
      - The
      - Following indents
      - Keep getting
  - Overwritten
title: The post title
id: [the id string]
```
