### ISSUE TITLE
Unable to add CC to outbound form email

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1086]
### Expected behaviour
Add a `cc:` recipient to a form on my site. Can there be a field in the CP for this?

### Actual behaviour
A `cc:` value when defined in the form's yaml does not show up in the email's header. There is no field for this in the control panel.

I confirmed this using the Log driver.

### Steps to reproduce
1.  Add `cc:` to a form's yaml file.
2.  Send an email using the Log driver.
3.  Check if the cc: value is present in the email.

### Server configuration
**Operating system**:
Mac OS Sierra
**Web server:**
Valet
**PHP version:**
7
**Statamic version:**
2.1.16
**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
form yaml (also tried wrapping the cc address in quotes)
```
email:
  -
    to: '{{region}}'
    subject: 'Certification from {{company}}'
    cc: support@celtra.com
    automagic: true
```

Outbound email, as displayed in the log.
```
Date: Fri, 04 Nov 2016 19:18:15 +0000
Subject: Certification from Company
To: certifications-na@***.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_v4_1478287095_afe34f60bf8e6e229dcc264adc0b9396_=_"
```
