### ISSUE TITLE
Copy & pasted taxonomy tags don't match previously created tags

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#1093]
### Expected behaviour
All the taxonomy terms associated with the entry should show up on the entry's CP page.

### Actual behaviour
My client loves to tag. So an entry will have 30-40 terms tagged to it. Everything seemed to be working well. But now for some reason in the control panel entry page tag field, I'll only see 4-5 or maybe even none.

### Steps to reproduce
This is where it's confusing. Some entries show a few tags. When I looked closer, the IDs for many of the tags didn't match any known tags. There are entries with 40 saved tag IDs that don't match any actual taxonomy IDs. The client only works through the CP and I have not pushed any "content" via git. So I'm not sure when or how IDs got switched or why they don't match.

### Server configuration
Linux - PHP Version 7.0.12

**Comment by pmeissner** [comment]
One last clue maybe… "Once when I went to `/cp/taxonomies/terms/tags` and there were ~1400 terms — 99% were redundant. I cleared the cache and that anomaly went away, but I’m afraid that the tags are messed up now."

**Comment by pmeissner** [comment]
Comparing files to a backup, it doesn't look like the IDs stored within the tag files changed. But rather the IDs saved with the entries are bogus. And it looks like in some of the entries all of the legitimate IDs were replaced with bogus IDs.

**Comment by jasonvarga** [comment]
Do you have `auto_taxonomy_fields` enabled in system.yaml?

**Comment by pmeissner** [comment]
Nope

**Comment by pmeissner** [comment]
```
license_key: ** REMOVED **
locales:
  en:
    full: en_US
    name: English
    url: '{env:APP_URL}'
timezone: America/New_York
date_format: F jS, Y
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
app_key: ** REMOVED **
redactor:
  -
    name: Standard
    settings:
      buttons:
        - formatting
        - bold
        - italic
        - unorderedlist
        - orderedlist
        - html
  -
    name: Basic
    settings:
      buttons:
        - bold
        - italic
csrf_exclude: [ ]
send_powered_by_header: true
ensure_unique_ids: true
```
