### ISSUE TITLE
Password field type is not working?

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#110]
```
  password:
    type: password
    display: Password
    required: true
```

![screen shot 2015-11-12 at 2 34 27 pm](https://cloud.githubusercontent.com/assets/1151181/11133415/967c34a8-894a-11e5-9aea-903ac56f669e.png)
