### ISSUE TITLE
Localizable collection routes not working

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1164]
### Expected behaviour
I do expect collection routes to be localizable as per documentation

routes.yaml
```
collections:
  blog:
    en: '/blog/{year}/{month}/{day}/{slug}'
    de: '/neues/{year}/{month}/{day}/{slug}'
```

### Actual behaviour
Only one of the the routes is working

### Steps to reproduce
```
collections:
  blog:
    en: '/blog/{year}/{month}/{day}/{slug}'
    de: '/neues/{year}/{month}/{day}/{slug}'
```

### Server configuration
**Statamic version:** 2.1.18

**Updated from an older Statamic or fresh install:** fresh install

### Cause
Some methods in `AggregateRepository` do not expect the parameter `$local` but it's passed an expected in `Repository`

### Patch
```
Index: statamic/core/Stache/AggregateRepository.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- statamic/core/Stache/AggregateRepository.php	(revision 2e2ee398c6c420e241a1cff3a9a5488a6dc06972)
+++ statamic/core/Stache/AggregateRepository.php	(revision )
@@ -101,10 +101,10 @@
      *
      * @return Collection
      */
-    public function getUris()
+    public function getUris($locale = null)
     {
-        return $this->repositories->map(function ($repo) {
-            return $repo->getUris();
+        return $this->repositories->map(function ($repo) use (&$locale) {
+            return $repo->getUris($locale);
         });
     }
 
@@ -229,13 +229,13 @@
      * @param string $url
      * @return $this
      */
-    public function setUri($id, $url)
+    public function setUri($id, $url, $locale = null)
     {
         list($repo, $id) = $this->extractKeys($id);
 
         $this->ensureRepo($repo);
 
-        $this->repo($repo)->setUri($id, $url);
+        $this->repo($repo)->setUri($id, $url, $locale);
 
         return $this;
     }
```

**Comment by peda** [comment]
Please also take a look at my comment #886 as fixing this issue unveils another (at the moment hidden) bug located in `Statamic\Stache\Updater::updateLocaleAggregate`

**Comment by peda** [comment]
that was fixed as part of #886

**Comment by FR6** [comment]
Not sure if i should open a new ticket or put it here since its a similar issue?

I'm trying to localize the collections route as stated on the documentation:
https://docs.statamic.com/localization#localizing-content

_settings/routes.yaml_:
```
collections:
  fourniture:
    fr: '/fourniture/{slug}'
    en: '/furniture/{slug}'
```

When i go to edit my collection: /cp/configure/content/collections/fourniture
I get the error: 
`htmlentities() expects parameter 1 to be string, array given (View: .../statamic/resources/views/collections/edit.blade.php)`

Currently using the latest version of Statamic: 2.6.4.

Thanks!
