### ISSUE TITLE
Array fieldtype with keys doesn't show keys

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#117]
![screen shot 2015-11-13 at 2 33 38 pm](https://cloud.githubusercontent.com/assets/468029/11139520/f08761b0-8a13-11e5-9434-d7ca906eeb4d.png)

Above field generated with this code, which was generated via the CP fieldset builder:

``` yaml
address_street:
    type: array
    display: Street Address
    keys:
      line_1:
      line_2:
```
