### ISSUE TITLE
Pages field inside a Grid returning null for each page title

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1250]
### Expected behaviour
I should be able to add a Grid field and have one of the child field be the Pages field type.

### Actual behaviour
The Pages field is returning `null` for the names of related pages. (The Pages field type is working normally as a standalone field type.)

<img width="1071" alt="screen shot 2017-02-08 at 3 25 22 pm" src="https://cloud.githubusercontent.com/assets/510790/22758108/daf5d2c8-ee12-11e6-8daa-729060df9e86.png">

### Steps to reproduce
1.  
<img width="1138" alt="screen shot on 2017-02-08 at 15_23_07" src="https://cloud.githubusercontent.com/assets/510790/22758043/97f426fa-ee12-11e6-9472-27bb4294bdbf.png">

2.  
<img width="861" alt="screen shot 2017-02-08 at 3 24 15 pm" src="https://cloud.githubusercontent.com/assets/510790/22758074/b2933cb2-ee12-11e6-9d90-073767f1830c.png">

3.  
<img width="884" alt="screen shot 2017-02-08 at 3 24 25 pm" src="https://cloud.githubusercontent.com/assets/510790/22758083/b8ac4db4-ee12-11e6-90d2-350c408fc58d.png">

### Server configuration
**Operating system**:
Mac

**Web server:**
valet

**PHP version:**
7.1

**Statamic version:**
2.5.2

**Updated from an older Statamic or fresh install:**
fresh

**List of installed addons:**
none

### Logs
Here's the field type
```
title: Rates
create_title: ""
fields:
  content:
    type: markdown
    display: content
    cheatsheet: true
    container: images
    restrict_assets: false
  rates:
    type: grid
    display: Rates
    instructions: 'Select cabins for each rate group.'
    fields:
      cabins:
        type: pages
        display: Cabins
        instructions: null
        parent: 83c1e1b8-b22c-4ec2-8271-d558f4c66a99
        depth: "1"
        max_items: null
        sort: null
        label: null
        mode: null
    mode: table
    min_rows: "1"
    add_row: Add Rate Level

```
