### ISSUE TITLE
Toggle field in addon settings doesn't honour `default` settings

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1280]
### Expected behaviour
When I set a `default` on a `toggle` field in my addon settings, it should be honoured.

### Actual behaviour
It is ignored

### Steps to reproduce
1. Add a Toggle field to your addon's settings  
2.  Set the `default` to `true` (or `'true'`)
3.  Visit the settings in the CP 

### Server configuration

**Statamic version:**
2.5.3

![mailchimp settings statamic 2017-02-28 15-05-33](https://cloud.githubusercontent.com/assets/6069653/23438797/6069c544-fdc8-11e6-9c8d-e8d6d1794783.png)

```
      double_opt_in:
        type: toggle
        display: Double Opt In
        default: 'true'
```
