### ISSUE TITLE
Taxonomy Terms are not translating in template as I expect

### ISSUE THREAD

**Issue by matteobarone** [statamic/v2-hub#1290]
### Expected behaviour
When I translate the taxonomy terms in another language, I expect to see the correct translation in the template.

### Actual behaviour
Taxonomies are the only things that i’m not able to translate.
I use the collection tag, and i can see in the page the title translated, but if I use the taxonomy tag not.

### Server configuration
**Operating system**:
OSX

**Web server:**
Apache

**PHP version:**
5.6.28

**Statamic version:**
2.5.3

**Updated from an older Statamic or fresh install:**
Update from statamic 2.1.9

**List of installed addons:**
none

### Logs
This is the taxonomy file
```
title: Function
fieldset: function
template: products-function
slugs:
  it:
    ceiling: soffitto
    floor: terra
    outdoor: esterno
    suspension: sospensione
    table: tavolo
    wall: parete
```

This is one of the terms file
```
title: Ceiling
image:
  - /assets/functions/ceiling.jpg
it:
  title: Soffitto
```

I call the taxonomy in the template like this
```
{{ taxonomy:function }}
  {{ title }}
{{ /taxonomy:function }}
```

System.yaml file
```
locales:
  en:
    full: en_US
    name: English
    url: http://example.dev/
  it:
    full: it_IT
    name: Italiano
    url: http://example.dev/it/
```
