### ISSUE TITLE
FR: Users fieldtype should be filterable

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1343]
### Expected behaviour
Be able to limit the users fieldtype to a certain role or group.

### Actual behaviour
Impossible, all users show up. Really messy. VERY BAD!

I have to create several addons for a custom role/group suggest mode then a custom fieldtype with a users suggest mode. Very complicated!

### Steps to reproduce
1.  Use Users fieldtype

**Comment by rrelmy** [comment]
You can use a custom Suggest mode for it
``` php
<?php
/**
 * @author Rémy M. Böhler
 */

namespace Statamic\Addons\Users2;

use Statamic\Addons\Suggest\Modes\AbstractMode;
use Statamic\API\User;
use Statamic\Exceptions\FatalException;
use Statamic\Extend\Extensible;

/**
 * Class Users2SuggestMode
 * @package Statamic\Addons\Users2
 */
class Users2SuggestMode extends AbstractMode
{
    use Extensible;

    /**
     * Get the suggestions.
     *
     * @return array
     * @throws FatalException
     */
    public function suggestions()
    {
        $role = $this->request->input('role');

        /** @var \Statamic\Data\Users\User[] $users */
        $users = User::all()->filter(function ($user) use ($role) {
            /** @var \Statamic\Data\Users\User $user */
            return $user->hasRole($role);
        });

        $suggestions = [];
        foreach ($users as $user) {
            $suggestions[$user->id()] = $this->label($user, 'username');
        }

        return format_input_options($suggestions);
    }
}
```

And the corresponding field for the fieldset
``` yaml
fields:
  author:
    type: suggest
    mode: users2
    display: Author
    role: 07233e4d-3c42-4144-ad37-95f47d9ad60d
    max_items: 1
    label: '{{ name }} <{{ email }}>'
```
