### ISSUE TITLE
Drag and Drop reorder, reording wrong elements, in nested replicators

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1394]
### Expected behaviour
Expected behaviour is that the items I dragged are reorder

### Actual behaviour
Other items (inside another replicator are reordered)

### Steps to reproduce
**1. use the following fieldset**
```
title: Multi Row
hide: true
taxonomies: false
fields:
  multi_row:
    type: replicator
    display: Multi Row
    sets:
....................
      form:
        display: Form
        fields:
          section_id:
            type: text
            display: Section ID
            instructions: Used for Anchor navigation / scrolling (leave empty if unsure)
            validate: numeric
          form_id:
            type: text
            display: Form ID
            instructions: The Form ID as specified during form creation
            width: 50
          section_display_options:
            type: checkboxes
            display: Section Display Options
            options:
              section--light: Light Section
              section: Transparent Section
            width: 50
      multi_column_row:
        display: Multi Column Row
        fields:
          section_id:
            type: text
            display: Section ID
            instructions: Used for Anchor navigation / scrolling (leave empty if unsure)
            validate: numeric
          parallax_image:
            type: assets
            display: Image
            instructions: Parallax image should be at least 1920px wide
            container: main
            folder: img
            max_files: "1"
          display_options:
            type: select
            display: Display Options
            options:
              full-width: Full Width
              container: Container
            width: 50
          section_display_options:
            type: checkboxes
            display: Section Display Options
            options:
              text--light: Light Text
              text--dark: Dark Text
              section--dark: Dark Section
              section--light: Light Section
              section: Transparent Section
              parallax-img-container: Parallax
            width: 50
          custom_style_classes:
            type: text
            display: Custom Style Classes
            instructions: For Developer use only
            width: 50
          columns:
            type: replicator
            display: Columns
            sets:
              column:
                display: Column
                fields:
                  column_width:
                    type: select
                    display: Column Width
                    options:
                      col-md-3: 1/4
                      col-md-4: 1/3
                      col-md-6: 1/2
                      col-md-8: 2/3
                      col-md-12: Full Width
                    width: 50
                  custom_style_classes:
                    type: text
                    display: Custom Style Classes
                    instructions: For Developer use only
                    width: 50
                  column_content:
                    type: replicator
                    display: Column Content
                    sets:
                      Single_Image:
                        display: Single Image
                        fields:
                          image:
                            type: assets
                            display: Image
                            container: main
                            folder: img
                            max_files: "1"
                            width: 50
                          alt_text:
                            type: text
                            display: Alt Text
                            width: 50
                      Slider:
                        display: Slider
                        fields:
                          images:
                            type: grid
                            display: Images
                            fields:
                              image:
                                type: assets
                                display: Image
                                container: main
                                folder: img
                                max_files: "1"
                                width: 50
                              alt_text:
                                type: text
                                display: Alt Text
                                width: 50
                      WeatherToday:
                        display: Weather Today
                        fields:
                          subline:
                            type: text
                            display: Subline
                          headline:
                            type: text
                            display: Headline
                            width: 50
                          headline_type:
                            type: select
                            display: Headline Type
                            options:
                              h2: H2
                              h3: H3
                              h4: H4
                            default: h3
                            width: 50
                      Post:
                        display: Post (Headline + Text)
                        fields:
                          subline:
                            type: text
                            display: Subline
                          headline:
                            type: text
                            display: Headline
                            width: 50
                          headline_type:
                            type: select
                            display: Headline Type
                            options:
                              h2: H2
                              h3: H3
                              h4: H4
                            default: h3
                            width: 50
                          text:
                            type: redactor
                            display: Text
                            container: main
                            folder: img
                          text_columns:
                            type: select
                            display: Text Columns
                            options:
                              text--one-column: "1"
                              text--two-column: "2"
                              text--three-column: "3"
                              text--four-column: "4"
                          list_items:
                            type: list
                            display: List Items
                      Button:
                        display: Button
                        width: 100
                        fields:
                          label:
                            type: text
                            display: Label
                            width: 33
                          button_style:
                            type: select
                            display: Button Style
                            options:
                              btn--animated: Animated
                              btn--dark-solid: Dark Solid
                              btn--dark-border: Dark Border
                              btn--theme-color: Theme Colored Solid
                              btn--theme-border-color: Theme Colored Border
                              btn: Default
                            width: 33
                          icon:
                            type: text
                            display: Icon
                            instructions: Font Awesome Icon Name (http://fontawesome.io/)
                            width: 33
                          link_target:
                            type: pages
                            display: Page Link
                            max_items: 1
                            label: '{{ title }}'
                            width: 33
                          url_target:
                            type: text
                            display: URL
                            instructions: URL Target is only used if no "Link Target" is provied
                            width: 33
                          button_display_options:
                            type: checkboxes
                            display: Display Options
                            options:
                              display--block: Display in separate line
                              display--inline-block: Display in line with others
                              btn--center: Center Button
                            width: 33
                      Form:
                        display: Form
                        fields:
                          form_id:
                            type: text
                            display: Form ID
                            instructions: The Form ID as specified during form creation
                            width: 50
                      Table:
                        display: Table
                        fields:
                          table:
                            type: table
                            display: Table
```

**2. and the following content**
```
multi_row:
  - 
    type: multi_column_row
    display_options: container
    section_display_options:
      - section--light
      - text--dark
    columns:
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Post
            subline: 'Lorem Ipsum '
            headline_type: h3
            text: |
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
          - 
            type: Button
            label: Contact us
            button_style: btn--theme-border-color
            button_display_options:
              - btn--center
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Single_Image
            image:
              - /assets/img/myimg.jpg
  - 
    type: multi_column_row
    display_options: container
    section_display_options:
      - section--light
      - text--dark
    columns:
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Post
            subline: Lorem Ipsum
            headline_type: h3
            text: |
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
          - 
            type: Button
            label: Contact us
            button_style: btn--theme-border-color
            link_target:
              - db0ae4e3-4f10-4803-bc40-0b880cbf02c7
            button_display_options:
              - btn--center
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Single_Image
            image:
              - /assets/img/myimg2.jpg
  - 
    type: multi_column_row
    display_options: container
    columns:
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Post
            subline: 'Lorem Ipsum'
            headline_type: h3
            text: |
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
      - 
        type: column
        column_width: col-md-6
        column_content:
          - 
            type: Post
            subline: 'Lorem Ipsum'
            headline_type: h3
            text: |
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
              <p>Lorem Ipsum
              </p>
      - 
        type: column
        column_width: col-md-12
        column_content:
          - 
            type: Button
            label: Contact us
            button_style: btn--theme-border-color
            button_display_options:
              - btn--center
    section_display_options:
      - section--light
      - text--dark
```

3. When you try to drag and drop re-order columns (especially within the second row) then some other elements are reordered but not the ones I've dragged around

### Server Details

**Operating System**: CentOS 7

**Web Server:** Apache 2

**PHP Version:** PHP 7

**Statamic Version:** 2.5.7 and 2.5.8

**Updated from an older Statamic or fresh install:** updated
