### ISSUE TITLE
Localization breaks for Australian site

### ISSUE THREAD

**Issue by nobodyiscertain** [statamic/v2-hub#1423]
### Expected behaviour
I set up multiple locales for my site following the docs on how to do so.

### Actual behaviour
The site and locale swapping worked for all except the Australian site. Carbon doesn't have an `au.php` file and throwing an exception. 

<img width="994" alt="carbon-australia" src="https://cloud.githubusercontent.com/assets/71233/26168364/a90684d2-3aee-11e7-9d91-d0b9face5717.png">

### Steps to reproduce
1.  Copy in locales config into settings.yaml
2.  Go to /au

```yaml
locales:
  en:
    name: USA
    full: en_US
    url: /
  ca:
    full: en_CA
    name: Canada
    url: /ca/
  uk:
    full: en_GB
    name: United Kingdom
    url: /uk/
  au:
    full: en_AU
    name: Australia
    url: /au/
```

### Server Details

**Operating System**:
Mac OSX 10.12.4

**Web Server:**
Apache (MAMP Pro)

**PHP Version:**
PHP 7.0.13

**Statamic Version:**
2.5.10

**Updated from an older Statamic or fresh install:**
Updated 

**List of installed addons:**
Seo
VideoEmbed
