### ISSUE TITLE
When multiple wysiwyg fields are added with assets, multiple asset buttons are added

### ISSUE THREAD

**Issue by Rias500** [statamic/v2-hub#1447]
### Expected behaviour
For each wysiwyg field on the control panel, a button gets added so the first one has 1 asset button but the next one has 2 and so on...

### Actual behaviour
Only 1 asset button on each wysiwyg

### Steps to reproduce
1.  Create a fieldset with multiple wysiwyg fields
2.  See multiple asset buttons

**Comment by jaggy** [comment]
@Rias500 Can I get for more info about the issue? Your Statamic version and the fieldset setting. Thanks!

**Comment by Rias500** [comment]
Latest Statamic

Fieldset could be something like this:

```yaml
columns:
    display: 2 Kolommen
    type: grid
    fields:
        left:
            display: Links
            type: redactor
            settings: Default
            container: images
        right:
            display: Rechts
            type: redactor
            settings: Default
            container: images
```

Screenshot (there's 3 redactor fields total on this control panel): 
<img width="749" alt="screen shot 2017-06-13 at 22 54 51" src="https://user-images.githubusercontent.com/3626559/27104121-64a94786-508b-11e7-96cb-53fc924b28e6.png">
