### ISSUE TITLE
Redactor Add Custom Formatting Tags not working

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1459]
Trying to add custom formatting as per the docs. I've done this:

```
redactor:
  -
    name: Standard
    settings:
      buttons:
        - alignment
        - formatting
        - link
        - html
      formatting:
        - p
      formattingAdd:
        red-p-add:
          title: Red Block Add
          args:
            - p
            - class
            - red-styled
  -
```

It's creating the drop down in the toolbar, but when I select it all I get is this (in HTML mode):

![image](https://user-images.githubusercontent.com/5466694/26958390-87f4620a-4d09-11e7-8065-41d01d48a475.png)

```
<p><undefined>TEST</undefined></p>
```

**Comment by rockethouse** [comment]
My bad... I was using the wrong Redactor docs... the following works:

```
      formattingAdd:
        -
          title: Red Text
          tag: p
          class: 'red'
        -
          title: Blue Text
          tag: p
          class: 'blue'
```
