### ISSUE TITLE
FR: Static Caching Invalidation for Globals

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1463]
Right now we can invalidate static cache(s) when collection items are updated:
```
static_caching_invalidation:
  collections:
    blog:
      urls:
        - /blog
        - /blog/category/*
        - /
```

It would be nice to extend this to globals so we can invalidate appropriate cache(s) when a global set is updated something like:
```
static_caching_invalidation:
  globals:
    default:
      urls:
        - /blog
        - /blog/category/*
        - /
```

Globals are content and it would be nice to invalidate all (appropriate) caches when something a global set is updated.

This would avoid us having to tell our clients to use `php please clear:static` or use the `Clear Static` button from the PowerTools addon every time they update a global.
