### ISSUE TITLE
[FR] Change default OAuth GeneratingUsername event

### ISSUE THREAD

**Issue by chrisburton** [statamic/v2-hub#1476]
**Background:**

When using multiple OAuth providers in your application, there seems to be some inconsistency with what each provider allows access to.

Example:

`$event->user->nickname`

- **Twitter:** returns `"chrisburton"`
- **Facebook:** returns `null`

Similarly, the same goes for email. Twitter does not allow access to the user's email, however Facebook does.

This is a problem when using the GeneratingUsername event. If a user authenticates with Facebook, the username will be null. If you don't use the GeneratingUsername event, a user authenticating with Twitter will now have just a timestamp rather than the default:

>By default, Statamic will generate a username by slugifying the email address and appending a timestamp.

There doesn't seem to be any consistency here. Talking with Jason, perhaps it would be best if Statamic used the same alpha-numeric ID applied inside the {$user}.yaml file as the filename of the user. 

Example user yaml file:
```yaml
username: test
avatar: https://graph.facebook.com/v2.8/some-random-numbers/picture?type=normal
url: https://facebook.com/test
provider: facebook
password_hash: $2y$90$dblahTblahKsQ0S6Xblahblahblahblahblah
id: 5b1398a8-abcd-123-9876-4632df198765
```

Filename: `5b1398a8-abcd-123-9876-4632df198765.yaml`
