### ISSUE TITLE
Feature request: Global redactor settings 

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#148]
Can we have a global Redactor settings like in V1?

Right now, for every Redactor field type, the settings can get rather long, example:
```
    buttons:
      - 'formatting'
      - 'bold'
      - 'italic'
      - 'deleted'
      - 'unorderedlist'
      - 'orderedlist'
      - 'outdent'
      - 'indent'
      - 'alignment'
      - 'image'
      - 'file'
      - 'link'
      - 'horizontalrule'
      - 'html'
    formatting: 
      - p
      - blockquote
      - pre
      - h1
      - h2
      - h3
      - h4
      - h5
    fileUpload: '/assets/docs' 
    imageUpload: '/assets/img'
```
