### ISSUE TITLE
FR: Column fieldset type

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1535]
It would be nice to have a way to put fields in columns just to arrange them nicely, although this can sometimes be done using widths and the natural flow - it can't always, not without offsets and other spacing.

If there was a column type that literally just took a width and grouped whatever was inside it into that column that would be a great tool for laying out fields in the CP.

I guess something like:

```
column_main:
  width: 50
  fields:
    copy:
      type: redactor

column_details:
  width: 25
  fields:
    name:
      type: text
    email:
      type: text

column_images:
  width: 25
  fields:
    avatar:
      type: assets
    background:
      type: assets
```

This would then add in 3 flexbox columns, 50%, 25% and 25% - these can be responsive and go to 100% width for smaller sizes. On larger screens they would layout the groups of fields in 3 columns.
