### ISSUE TITLE
Missing Widget shouldn't cause CP to break

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1544]
### Expected behaviour
CP is displayed with "Missing Widget" message in dashboard.

### Actual behaviour
A `Whoops` message is displayed and you can't access the Dashboard

### Steps to reproduce
1. Add a non-existing Widget to the `cp.yaml`  
2. Visit the CP

**Comment by lukeagsmith** [comment]
Actually I'm getting and error after upgrading to 2.6.3 from 2.5.9 with a widget that does exist.

`cp.yaml`:
```
widgets:
  -
    type: template
    template: widgets/therapist-checker
    width: 33
```

Was working fine before update so I know the template exists.

The error is
```
ErrorException in Extensible.php line 70:
Undefined property: Statamic\Addons\Template\TemplateWidget::$config
```
