### ISSUE TITLE
Localizable collection routes produce an error exception

### ISSUE THREAD

**Issue by FR6** [statamic/v2-hub#1556]
### Expected behaviour

I'm trying to localize the collections route as stated on the documentation:
https://docs.statamic.com/localization#localizing-content

### Actual behaviour

When i go to edit my collection: /cp/configure/content/collections/fourniture
I get the error: 
```
ErrorException in helpers.php line 469:
htmlentities() expects parameter 1 to be string, array given (View: .../statamic/resources/views/collections/edit.blade.php)
```

### Steps to reproduce

_settings/routes.yaml_:
```
collections:
  fourniture:
    fr: /fourniture/{slug}
    en: /furniture/{slug}
```

### Server Details

Homestead
**Statamic Version:** 2.6.4
