### ISSUE TITLE
FR: Date validation to compare against another field

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1561]
I have not tested this extensively, but the following fieldtype validation error occurs:

```
title: Booking
hide: true
taxonomies: false
fields:
  start_date:
    display: Start Time
    type: date
    validate: required|date|after:today
  end_date:
    display: End Time
    type: date
    validate: required|date|after:start_date
```
The validation on `start_date` works but the validation on `end_date` does not work.

I copied the validation rules directly from the Laravel rules: https://laravel.com/docs/5.1/validation#rule-after

**Comment by rrelmy** [comment]
Does not work is the worst description of an issue possible.
Always describe what exactly does not work. Use the issue template for it an write down what you do expect and what does happen.

What happens on the end_date field validation?
- Does the validation do nothing at all?
- Does it allow empty values?
- Does it allow invalid dates?
- Does it allow dates before start_date?
- Does it always fail?
- … 

Maybe also relevant are things like:
- What content type do you use (Collection, Page, Globals, Addon Settings)?
- Is this fieldset used directly or as a partial inside another?
- Statamic version (hopefully the latest)? Always add it for future reference

The more information you can give the easier it gets to reproduce and fix the issue.

**Comment by jasonvarga** [comment]
I see what you're trying to do, but this is more of a feature request than a bug.

You're asking for the validation rule to compare to the value of another field.

**Comment by anthubbard** [comment]
Hi Jason,

When working on this I was looking through the docs and on this page -
 https://docs.statamic.com/fieldtypes - at the bottom there is a link to 'validation rules'. This link goes directly to the laravel validation rules: http://laravel.com/docs/5.1/validation#available-validation-rules.

I just assumed that because you linked directly to the Laravel validation rules that ANY validation rule from that Laravel page would work.

If that isn't the case, then maybe the docs need to be a bit clearer regarding what validation actually applies and what doesn't.

Cheers,

Ant

**Comment by jasonvarga** [comment]
Just noticed that validation rule says you can pass it another field name. Didn't realize that. I'll look into it.

**Comment by jasonvarga** [comment]
Okay. A long standing internal thing we've been wanting to adjust is that the published fields are nested under a `fields` variable. It hasn't really been an issue, but this is obviously a side-effect.

So for now, you can change your validation rule to this:

```
  end_date:
    display: End Time
    type: date
    validate: required|date|after:fields.start_date
```

That'll work now, but you'll need to adjust whenever we address that. (It might not be until v3, or ever. Not sure.)
