### ISSUE TITLE
'Add new row' on grid broken on 2.6.6+

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1593]
### Expected behaviour
When pressing 'add new row on a grid' it should add a new row.

### Actual behaviour
It doesn't add a new row. Console has the following error:
```
Uncaught TypeError: this.data.push is not a function
    at GridFieldtype.addRow (jabbascripts.js:5)
    at HTMLButtonElement.<anonymous> (johnny-deps.js:5)
```
Nothing in logs (as expected).

### Server Details

**Operating System**: OSX

**Web Server:** Apache

**Statamic Version:** Tested on 2.6.6 and 2.6.8

**Updated from an older Statamic or fresh install:** update

**Comment by anthubbard** [comment]
Turned out a random character ended up in my array - not sure how or why, it must have been put there by statamic so it might still be an issue?

```
feature:
  2:
    file: /assets/images/pages/pexels-photo-261628.jpeg
    text: Contact Us to Book
    link: /contact
```
That `2:` shouldn't be there.
