### ISSUE TITLE
Statamic adding strange character entries like 0: and 2: to arrays

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1594]
Statamic is adding strange character entries in some really weird places in files. I have no idea how it is happening or at what point.

This happened to me - on an array on my index.md (homepage) this was added somehow by statamic (or at least I assume it was, I certainly didn't add it):
```
feature:
  2:
    file: /assets/images/pages/pexels-photo-261628.jpeg
    text: Contact Us to Book
    link: /contact
```
That array should be:
```
feature:
  -
    file: /assets/images/pages/pexels-... etc
```
I figured it was some random issue, or possibly that I'd somehow done it - but the same thing happened to beckysoll and with possibly worse consequences in her routes.yaml file so it probably is a real issue:

![pasted image at 2017_09_12 04_36 pm](https://user-images.githubusercontent.com/5089177/30353948-c07b9e50-986c-11e7-885d-f4a91c4ccc82.png)

V 2.6.6

**Comment by jasonvarga** [comment]
Unfortunately I'm going to need to ask for more details. We'll need to know what caused it.
Seems like maybe there was a Javascript error on the page preventing the array from being properly re-keyed before submitting.


No idea on the route screenshot either. That field is basically just manual entry, even from the CP.

**Comment by anthubbard** [comment]
I know it is vague, but I have no idea how it happened or when or where or why. Sorry. I was just reporting that it happened and I wouldn't have even posted it if the same thing hadn't happened to Becky as well... maybe just leave/close it till someone else runs into the same thing or can actually recreate it.

**Comment by jasonvarga** [comment]
Looks like Becky's issue was that there was a `---` in her content, causing it to confuse where front matter starts and ends.

I don't know if you are running into a similar problem, @anthubbard

**Comment by beckysoll** [comment]
FWIW, that routes issue was way before the --- issue - for that, i entered the route correctly, saved it, went back later and that was there. Granted i could just think i typed it correctly, and mistyped something - but i'm 100% sure it looked right after i saved it, and didn't start with 0: until i went back in to look at it a few hours later to add another route.

**Comment by anthubbard** [comment]
Alright! I managed to recreate my issue (won't help Becky though) :)

I have a grid setup  with another grid inside it:
```
  header_img:
    display: Heading Image or Slider
    instructions: To make this a slider click the toggle above and add multiple rows
    type: grid
    mode: stacked
    fields:
      img:
        display: Image / Slider File and Size
        type: grid
        min_rows: 1
        max_rows: 1
        fields:
          file:
            type: assets
            display: Image
            container: main
            folder: images
            max_files: 1
          text:
            display: Text Over Image / Slider (optional)
            type: textarea
            height: 100
          link:
            display: Image / Slider Link (optional)
            instructions: "FORMAT - Internal links:'/link' | External links:'http://www.site.com/link'"
            type: text
```
If I had some rows to the outside grid *and add content somewhere in the grid inside them* then save the page all is well.  If I then add an outside grid but don't put content inside it and save, all is still well. BUT then if I move that outside grid that has no content on the inside grid anywhere up the row list of the outside grids, it changes the - of the grid numbering to a number 0: etc

Does that make sense?

Ant
