### ISSUE TITLE
The conditions doesn't work

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1596]
### Expected behaviour
The template should print my image

### Actual behaviour
It doesn't print it.

### Steps to reproduce
Entry YAML:

```
title: A post
images:
  - 
    category: Yes
    source: image.jpg
  -
    category: No
    source: image2.jpg
```

Template:

```
<h1>{{ title }}</h1>

{{ images }}

       <h2>Category: {{ category }}</h2>

	{{ if category == "Yes" }}

		<p>Image here</p>

	{{ /if }}

{{ /images }}
```
Outputs:

> <h1>A post</h1>
> <h2>Category: Yes</h2>
> <h2>Category: No</h2>

Doesn't output:

> <p>Image here</p>

**Statamic Version:**

2.6.8
