### ISSUE TITLE
Modifier where doesn't work

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1597]
### Expected behaviour
Should be able to modify the array in the entry.

### Actual behaviour
Throws error:

> 
> ErrorException in Parser.php line 400:
> Array to string conversion

### Steps to reproduce
Entry YAML:

```
title: My test
my_array:
  -
    shout: "Hello"
    something: "lalala"
  -
    shout: "Goodbye"
    something: "olalala"
```

Template:

```
{{ title }}

{{ my_array where="shout:Hello"}}

    {{ something }}

{{ /my_array }}
```

**Note**
This is an entry not a page. In a page content it works.

**Statamic Version:**
2.6.8
