### ISSUE TITLE
FR: Ignore validation rules on conditional fields if they aren't shown

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#1619]
### Expected behaviour
If I have two fields, one which is only shown when another is set such as:

```
field_1:
  type: select
  options:
    - option_1
    - option_2

field_2:
  type: date
  validate: required
  show_when:
     field_1: option_1
```

I'd like to only have the validation if `option_1` is selected and `field_2` is shown. 

### Actual behaviour
Validation error even when `field_2` isn't shown.

**Statamic Version:**
2.7.0

**Comment by jasonvarga** [comment]
Try this:

`validate: required_if:fields.field_1,option_1`

**Comment by josewhitetower** [comment]
I want to validate a field only under the `show_when`rules. 
```
field_1:
    type: text
    display: 'Field_1'
    show_when:
      field_2:
        - value_1
        - value_2
      field_3: value_3
    validate: required_if:fields.field_2,value_1,value2 "AND" fields.field_3,value_3
```
Is there anyway I can have a validation rule with a Logical "AND"?
