### ISSUE TITLE
Cache Invalidation not working in non-default locales/languages

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1626]
After #1277  has been fixed it is now possible to use [Static File Caching](https://docs.statamic.com/caching#static-page) on multilingual websites. Yay!

Unfortunately the invalidation doesn't work:

The setting `static_caching_invalidation` is ignoring localized cached files.

I tried this:

```yaml
static_caching_invalidation:
  collections:
    assistant:
      urls:
        - /assistent
        - /assistant
        - /en/assistant
```
It works for the default locale `/assistent` (German), but wont delete the static cache files for English on save.

Also, apparently `static_caching_exclude` uses slugs without locales, which is not mentioned in the docs about [Static File Caching](https://docs.statamic.com/caching#static-page).

Because of before mentioned bug I'd like to exclude my English home page from the cache, which is not possible. It might not make sense to exclude locales from caching, though. Just documenting it (:
