### ISSUE TITLE
Max items 1 not working 

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1632]
### Expected behaviour
A nice dropdown list that lets you select 1 item.

### Actual behaviour
When using max-items: 1 it should generate a dropdown list, it does show a dropdown list but it 
adds the tag to the field and allows you to add another. 

``` yaml
example_grid:
    display: Example grid
    type: grid
    min_rows: 3
    max_rows: 3
    mode: stacked
    fields:
      image:
        type: assets
        max_files: 1
        container: images
        width: 33
      title:
        type: pages
        max-items: 1
        display: Link to page
        depth: 1
        width: 33
      project_list:
        type: grid
        display: project list
        min_rows: 1
        width: 33
        fields:
          project:
            type: collection
            display: Link to project
            collection: projects
            max-items: 1
```

### Server Details

**Operating System**:
macOS HS
**Web Server:**
local mamp pro 4.2.1
**PHP Version:**
7.1.8
**Statamic Version:**
2.7.1

**Updated from an older Statamic or fresh install:**
Updated from 2.7.0
**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...

</details>
