### ISSUE TITLE
Clear CP thumbnails when filename already existed

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1664]
### Expected behaviour
When an image (asset) has been uploaded thumbnails are generated (_small_ & _large_). If that image is replaced by an asset with the same filename, the thumbnails should be regenerated to show the new image. 

### Actual behaviour
The old thumbnails persist from the previous image (that had the same filename).

I thought I could clear it with `php please clear:glide` or one of the other clear commands, but the CP thumbnails are stored elsewhere it seems. Right-clicking on the image to open it reveals a route that isn't in the file system.
`http://example.com/cp/assets/thumbnails/bWFpbjo6...anBn/small`

Refreshing that URL does regenerate the thumbnail but it'd be nice to have a CP button or `php please` command to address this.

**Comment by jasonvarga** [comment]
Can you show me your `site/settings/assets.yaml`?

If you aren't using the image_manipulation_cached setting, can you just hard refresh on one of those thumbnail urls? Maybe your browser has cached the older version.

**Comment by wesort** [comment]
Sure. 

I can't remember for certain, but I most likely would have hard refreshed (cmd+shift+R) and also have hit _Empty cache and hard reload_. (Damn I wish there was a [keyboard shortcut for that](https://bugs.chromium.org/p/chromium/issues/detail?id=786143)!)

### site/settings/assets.yaml
```
image_manipulation_route: /img
image_manipulation_secure: true
auto_crop: true
image_manipulation_driver: imagick
image_manipulation_cached: false
image_manipulation_presets:
  w360:
    w: 360
    q: 80
    fit: max
  w600:
    w: 600
    q: 80
    fit: max
  w900:
    w: 900
    q: 80
    fit: max
  w1200:
    w: 1200
    q: 80
    fit: max
  w1600:
    w: 1600
    q: 80
    fit: max
thumbnail_max_width: 6000
thumbnail_max_height: 6000
```
