### ISSUE TITLE
Create a sub-page doesn't set the fieldset property within the page markdown file

### ISSUE THREAD

**Issue by fkwakkenbos** [statamic/v2-hub#1697]
### Expected behaviour
When we create a sub-page, the new page markdown file should contain a fieldset parameter/property with the correct (choosen) fieldset.

### Actual behaviour
When we create a sub-page, the new page markdown file is missing the fieldset parameter/property.

### Steps to reproduce
1.  Create a normal page, etc...
2.  Create a sub-page below the normal page using the submenu in the CP at the right of the normal page you just created in step 1
3.  Choose the correct fieldset for the new sub-page
4. Save the new sub-page

### Server Details

**Operating System**:
Mac OS X

**Web Server:**
MAMP Pro

**PHP Version:**
7.1.1

**Statamic Version:**
5.1.46

**Updated from an older Statamic or fresh install:**
Updated from 5.1.??

**List of installed addons:**
No add-ons

### Logs
No error log entries
</details>

**Comment by dannyuk1982** [comment]
Your statamic version is wrong

**Comment by jasonvarga** [comment]
![](http://tuhoatylsyys.com/wp-content/uploads/2015/10/tumblr_nhigjk3LXG1qd584so2_500.gif)

**Comment by jasonvarga** [comment]
I can't see this issue. Whats the name of the fieldset you're trying to use? Does it happen with all fieldsets?

**Comment by fkwakkenbos** [comment]
Sorry... We are running Statamic version 2.7.3 :-)

The fieldset name is: page_detail
Hmm interesting.
When I use a new simple fieldset, the problem does NOT occur.

Here is my fieldset: page_detail

```
taxonomies: false
title: page detail
create_title: Detail page
fields:
  title:
    type: title
    display: Title
    localizable: true
  page_top_layout:
    type: select
    display: Page Top Layout
    options:
      it-solutions: IT Solutions
      it-services: IT Services
      it-buying: IT Buying
      general: General (like about...)
    width: 25
    default: it-solutions
    validate: required
  meta_title:
    type: text
    display: Meta Title
    validate: required|between:1,160
  meta_description:
    type: text
    display: Meta Description
    validate: required|between:1,255
  content_top:
    type: redactor
    display: Content Top
    settings: Standard
    container: main
    folder: /
    width: 50
  image_top:
    type: assets
    display: Image Top
    container: main
    folder: /
    max_files: 1
    mode: grid
    width: 50
  content_grid:
    type: grid
    display: Content Grid
    fields:
      section_image:
        type: assets
        display: Block afbeelding
        instructions: Als geen image, dan toont die deze ook niet.
        container: main
        folder: /
        mode: grid
        max_files: 1
      content:
        type: redactor
        display: Content
        settings: Standard
        container: main
        folder: /
      style_type:
        type: select
        display: Style Type
        options:
          html_only: HTML only
          html_only_blue: HTML only but Blue background
          icon_blocks: Icon blocks
          2cols_html_image: HTML left and Image right
          2cols_image_html: HTML right and Image left
        default: html_only
      icon_blocks:
        type: grid
        display: Icon Blocks
        fields:
          title:
            type: text
            display: Title
          icon_class:
            type: text
            display: Icon Class
            width: 25
            default: callbell
          internal_link:
            type: pages
            display: Internal Link
            max_items: 1
            mode: panes
            width: 25
          external_link:
            type: text
            display: External Link
            width: 25
        mode: table
        max_rows: 99
    mode: stacked
  template:
    type: template
    display: Template
    default: page-detail

```
