### ISSUE TITLE
Hidden fieldsets get saved with an empty value if not shown

### ISSUE THREAD

**Issue by hmalaud** [statamic/v2-hub#1706]
### Expected behaviour
On saving a settings page with hidden fieldsets (_show_when_), their value should not change (if filled, it should not be cleared).

### Actual behaviour
On saving a settings page with hidden fieldsets (_show_when_), they are saved with an empty value (not just "not saved") if the related _revealer_ has not been activated. 
However, when using the _revealer_, data is correctly displayed in the fields and saving goes according to plan. 
(When the fields are hidden, using the browser's inspector returns the correct value with $0.value when focusing any of the hidden fields.)

### Steps to reproduce
1.  Create a settings page with a revealer
```
reveal_config:
    type: revealer
    display: Display hidden fieldsets
```
2.  Create hidden fieldsets
```
hidden_fieldset:
    type: array
    display: Hidden fieldset
    keys:
      first_key: First Key
      second_key: Second Key
    show_when:
      reveal_config: true
    width: 50
  another_hidden_fieldset:
    type: checkboxes
    display: Another Hidden Fieldset
    options:
      option_one: Option 1
      option_two: Option 2
    show_when:
      reveal_config: true
    width: 25
[...]
```
3.  

### Server Details

**Operating System**: macOS Sierra 10.12.6

**Web Server:** Apache 2.4

**PHP Version:** PHP Version 7.0.14

**Statamic Version:** 2.8.0

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** Custom Addons + sections by Rudy Affandi

![screen-recording-2018-01-12-at-10 55-am](https://user-images.githubusercontent.com/1000119/34869475-49a95cd4-f787-11e7-9d9b-64a51fc1df68.gif)
