### ISSUE TITLE
Drag and Drop of Bard sets within Replicator doesn't work

### ISSUE THREAD

**Issue by aerni90** [statamic/v2-hub#1723]
### Actual behaviour
When trying to move a set within Bard, it actually moves the whole Replicator field, instead of the Bard set. [Watch video of issue.](https://drive.google.com/file/d/1IzgnUeHC87HfF-aqYunKhqGNscb6PrSY/view)

### Steps to reproduce
1.  Create a Replicator field with a set of Bard
2.  Create a set within Bard
3.  Try to move the Bard set in the Control Panel.

### Fieldset
```
title: Builder
hide: true
fields:
  builder:
    type: replicator
    display: Page Builder
    instructions: Build this page with the components provided below.
    sets:
      hero:
        display: Hero
        fields:
          hero_images:
            type: assets
            display: Hero Image / Slider
            instructions: Choose a hero image. Add multiple images to create a hero slider. No image will result in a white hero.
            container: images
            folder: /
          hero_title:
            type: text
            display: Hero Title
            instructions: Write a title for this page.
          hero_lead:
            type: text
            display: Hero Lead
            instructions: Write a lead for this page.
      content:
        display: Content
        fields:
          content:
            type: bard
            display: Content
            instructions: Write the content of this post entry. Add Images and other components as needed.
            buttons:
              - bold
              - italic
              - anchor
              - h3
            sets:
              download:
                display: Download
                fields:
                  download:
                    type: assets
                    display: Download
                    instructions: Choose a file for the user to download.
                    container: documents
                    folder: /
                    max_files: 1
              forms:
                display: Forms
                fields:
                  forms:
                    type: select
                    display: Forms
                    instructions: Select the form of your choice.
                    options:
                      contact: Contact
                      newsletter: Newsletter
                      rooms: Room Reservation
              image-slider:
                display: Image / Slider
                fields:
                  images:
                    type: assets
                    display:  Image / Slider
                    instructions: Choose more than one image to create a slider.
                    container: images
                    folder: /
              link:
                display: Link
                fields:
                  link_title:
                    type: text
                    display: Link Title
                    instructions: Enter the title for this link.
                  link_url:
                    type: text
                    display: Link URL
                    instructions: Enter the URL for this link.
              title-lead:
                display: Title / Lead
                fields:
                  section_title:
                    type: text
                    display: Title
                  section_lead:
                    type: text
                    display: Lead
```

**Operating System:** macOS 10.12.6
**Web Server:** Laravel Valet
**PHP Version:** 7.1
**Statamic Version:** 2.8.1
