### ISSUE TITLE
Bard without sets within a Replicator fails

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1724]
### Expected behaviour
Using a `Bard` without sets within a `Replicator` works as a normal editor.

### Actual behaviour
Javascript throws an error:

### Steps to reproduce
1. Setup a replicator with a bard set without its own set.
2. Try to add a new bard set.
3. Inspect the console for errors.

### Javascript error
```
jabbascripts.js?v=2.8.1:32 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
jabbascripts.js?v=2.8.1:7 Uncaught (in promise) TypeError: this.data.forEach is not a function
    at BardFieldtype.combineConsecutiveTextBlocks (jabbascripts.js?v=2.8.1:7)
    at BardFieldtype.combineConsecutiveTextBlocks (johnny-deps.js?v=2.8.1:5)
    at BardFieldtype.ready (jabbascripts.js?v=2.8.1:7)
    at BardFieldtype.Sn.t._callHook (johnny-deps.js?v=2.8.1:6)
    at BardFieldtype.e (johnny-deps.js?v=2.8.1:7)
    at BardFieldtype.n (johnny-deps.js?v=2.8.1:6)
    at BardFieldtype.Rn.t.$emit (johnny-deps.js?v=2.8.1:6)
    at BardFieldtype.Sn.t._callHook (johnny-deps.js?v=2.8.1:6)
    at o (johnny-deps.js?v=2.8.1:6)
    at Array.forEach (<anonymous>)
combineConsecutiveTextBlocks @ jabbascripts.js?v=2.8.1:7
(anonymous) @ johnny-deps.js?v=2.8.1:5
ready @ jabbascripts.js?v=2.8.1:7
Sn.t._callHook @ johnny-deps.js?v=2.8.1:6
e @ johnny-deps.js?v=2.8.1:7
n @ johnny-deps.js?v=2.8.1:6
Rn.t.$emit @ johnny-deps.js?v=2.8.1:6
Sn.t._callHook @ johnny-deps.js?v=2.8.1:6
o @ johnny-deps.js?v=2.8.1:6
r @ johnny-deps.js?v=2.8.1:6
Rn.t.$emit @ johnny-deps.js?v=2.8.1:6
Sn.t._callHook @ johnny-deps.js?v=2.8.1:6
ge @ johnny-deps.js?v=2.8.1:6
he.callHook @ johnny-deps.js?v=2.8.1:7
fe @ johnny-deps.js?v=2.8.1:6
insert @ johnny-deps.js?v=2.8.1:7
diff @ johnny-deps.js?v=2.8.1:7
update @ johnny-deps.js?v=2.8.1:7
update._update @ johnny-deps.js?v=2.8.1:8
re.run @ johnny-deps.js?v=2.8.1:7
ne @ johnny-deps.js?v=2.8.1:6
ee @ johnny-deps.js?v=2.8.1:6
t @ johnny-deps.js?v=2.8.1:7
Promise resolved (async)
i @ johnny-deps.js?v=2.8.1:7
(anonymous) @ johnny-deps.js?v=2.8.1:7
ie @ johnny-deps.js?v=2.8.1:6
re.update @ johnny-deps.js?v=2.8.1:7
Pt.notify @ johnny-deps.js?v=2.8.1:7
(anonymous) @ johnny-deps.js?v=2.8.1:7
addSet @ jabbascripts.js?v=2.8.1:8
(anonymous) @ johnny-deps.js?v=2.8.1:5
(anonymous) @ VM3346:3
i @ johnny-deps.js?v=2.8.1:8
```

### Simple fieldset test
```yaml
fields:
  modules:
    type: replicator
    display: Modules
    sets:
      text:
        display: Text
        fields:
          headline:
            type: text
            display: Headline
            validate: required|string
          content:
            type: bard
            display: Content
            buttons:
              - bold
              - italic
              - anchor
              - h3
              - quote
            validate: required|string
```

### Server Details

**Statamic Version:** 2.8.1
