### ISSUE TITLE
File uploads are not validated correctly in forms

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1765]
When validating a file field in a form with a rule that depends on an `UploadedFile` instance, it fails.

**Comment by aryehraber** [comment]
Funny, I just came across this issue today and was about to report.

This seems to also be an issue inside fieldsets. Here's an example using rule from [Laravel docs](https://laravel.com/docs/5.1/validation#rule-image):

```
fields:
  logo:
    type: assets
    container: main
    validate: image
```

This results in an error: "The Logo field must be an image."

Also fails when using MIME type rules instead of `image`:

```
fields:
  logo:
    type: assets
    container: main
    validate: mimes:jpg,jpeg,png,gif
```

**Comment by jasonvarga** [comment]
Fixed for next release

**Comment by aryehraber** [comment]
@jasonvarga That's awesome, thanks for the update!

Just to clarify, is it fixed for both Forms and Fieldsets, or just Forms?

**Comment by mrcalc** [comment]
Statamic 2.8.5 still seems to have this issue for front-end forms. 

``` yaml
title: File validation test form
fields:
  something:
    validate: mimes:doc,docx,pdf
    display: Test file validation
    type: file
    destination: uploads/
```

If sanitize is enabled on the form (the default), the `UploadedFile` instance is wiped out by the call to `sanitize_array` in `FormListener::create`, so validation receives the path to the temp file instead of the `UploadedFile` instance. 

Validation of file uploads works if the sanitize helper skips `UploadedFile` instances:
``` php
// statamic/bootstrap/helpers.php
function sanitize($value, $antlers = true)
{
    if (is_array($value)) {
        return sanitize_array($value, $antlers);
    }
    if ($value instanceof UploadedFile) {
        return $value;
    }
```
I can't comment on whether this is a good fix given the helper method may be used for other purposes. Maybe a fix within `FormListener::create` would be better.
