### ISSUE TITLE
[FR] use of partials in Bard fieldtype

### ISSUE THREAD

**Issue by PeterEmil** [statamic/v2-hub#1770]
The way Bard makes writing content and giving clients curated components is its strong USP. To DRY up a fieldset which uses Bard the way is templates work it is very helpful the Bard fieldtype handles the `partial` fieldtype.
```
title: Bard
fields:
  content:
    type: bard
    sets:
      partial_bard:
        fields:
          content:
            type: partial
            fieldset: bard-partial
```
