### ISSUE TITLE
Toggle field within a Grid breaks alignment

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#1801]
When adding a Toggle field to a Grid field, this changes the height of the cell and breaks alignment for the other fields.

Changing

```css
.grid-fieldtype .toggle-fieldtype {
    padding: 10px;
}
```

to

```css
.grid-fieldtype .toggle-fieldtype {
    padding: 3px 10px;
}
```

Seems to fix this.

![localhost_8080_admin_globals_fulfilment-settings laptop 1](https://user-images.githubusercontent.com/893609/36592788-0d0fb416-188f-11e8-8476-9e54c9b7065f.png)
