### ISSUE TITLE
Fixes: Text overflow in SelectFieldtype Vue component

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1805]
These style changes will fix the broken text overflow for the drop-downs, and slightly adjust the arrows to be vertically centered.
```css
.select::before {
    width: 100%;
    overflow: hidden;
}
.select::after {
    top: 12px;
}
```

**Comment by jackmcdade** [comment]
Can you show me a screenshot of what this is fixing and in what browser? I do see the icons are better centered (thank you) but the text-overflow behavior is still the same.

**Comment by FrittenKeeZ** [comment]
If you set the select `<div class="select">` to a fixed width the text will overflow.

**Comment by FrittenKeeZ** [comment]
The arrows for `selectize` needs adjustment as well:
```css
.selectize-control.single .selectize-input:after {
    top: 12px;
}
```
