### ISSUE TITLE
FR: ability to define attributes for fieldtypes like text, textarea, select & etc.

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1830]
When we define fieldtypes for RTL langs like Hebrew/Arabic, for some inputs like `email` or `username`, the direction has to be `ltr`. But I can't set attributes like `dir="ltr"` to fieldtype.
Also, it would be good to be able to define custom classes to inputs:
An example:
```
email:
  type: text
  attributes:
    dir: ltr
    class: class_name
    placeholder: Enter your email address
```
