### ISSUE TITLE
Bug: Bard Markdown should handle empty text value

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1845]
When using Bard with markdown, saving an empty `text` field throws an error when reopened. 

```
ErrorException in BardFieldtype.php line 28:
Undefined index: text
```

Content:

```
body:
  -
    type: text
    text: ""
```
Fieldset:

```
body:
    type: bard
    markdown: true
    sets:
      -
        type: quote
        display: Quote
        fields:
          quote:
            display: Quote
            type: text
          cite:
            display: Cite
            type: text
```

### Server Details

**Statamic Version:**
2.8.8
