### ISSUE TITLE
Firefox-Bug: Error Editing List-Items in Bard Field

### ISSUE THREAD

**Issue by goldnead** [statamic/v2-hub#1851]
### Expected behaviour
List Items in bard-field should be editable when double-clicked in Firefox (works as expected in Chrome/Safari).

### Actual behaviour
Nothing Happens and console throws the following Error:
```
ReferenceError: event is not defined
jabbascripts.js:5:25229
```
### Steps to reproduce
My Fieldset looks like the following:
```yaml
title: Artikel
taxonomies:
  tags: true
fields:
  title:
    type: title
    display: Titel
    localizable: true
    validate: required
  article:
    type: bard
    display: Artikel-Text
    instructions: Der eigentliche Inhalt des Artikels
    sets:
      list:
        display: Liste
        fields:
          list:
            display: Liste
            type: list
    spellcheck: true
    buttons:
      - bold
      - italic
      - anchor
      - h3
    autoLink: true
    link_validation: true
    paste:
      forcePlainText: true
    allow_source: true
    force_plain_text: true
    validate: required

```
Creating a List Element with Items works as expected. But afterwards deletions are the only option to edit the items in Firefox.

### Server Details

**Operating System**: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-92-generic x86_64)
**Web Server**: Homestead/vagrant nginx

**PHP Version:** 7.1

**Statamic Version**: 2.8.8

**Updated from an older Statamic or fresh install:** updated from 2.8.5

**List of installed addons:**
[Colorpicker](https://github.com/lesaff/statamic-colorpicker) & [Image-Optimizer](https://github.com/4rn0/statamic-image-optimizer)

### Logs
No Log-Messages
