### ISSUE TITLE
CSS issue in CP when a Section is the first field on a page

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1865]
I have a fieldset that uses a hero_image partial.  

```
taxonomies: false
title: Default Page
fields:
  hero_image_partial:
    type: partial
    fieldset: hero_image
  long_form_content_partial:
    type: partial
    fieldset: long_form
```

In the partial there is a section field 

```
taxonomies: false
title: Hero Image
hide: true
fields:
  hero_image_section:
    type: section
    display: Hero Image
  hero_image:
    type: assets
    display: Hero Image
```

and the section field is overlapping the Title field when viewed on a desktop.  Looks like a CSS issue.

![screen shot 2018-04-02 at 10 21 20 pm](https://user-images.githubusercontent.com/2436728/38225804-a5e4f2e8-36c4-11e8-9899-e0387e2f86d4.png)
