### ISSUE TITLE
Bug: Required title field not communicated in UI by red asterisk

### ISSUE THREAD

**Issue by tkoosis** [statamic/v2-hub#1879]
### Expected behaviour
When you try to save a collection entry without having a title it errors on validation because it's required, but the UI doesn't reflect it.  I'd assume it should.

### Actual behaviour
No required notation in the UI (e.g. the red asterisk) like there is for other fields we introduce. 

<img width="245" alt="screenshot 2018-04-06 16 28 28" src="https://user-images.githubusercontent.com/170316/38448220-9c5f9d7c-39b7-11e8-8ec6-bc3452bba7d8.png">

### Steps to reproduce
1.  Create a fieldset 
2.  Add to collection
3.  Add entry and save without title 
4. You get validation error on title 

### Server Details
**Statamic Version:** 2.8.10

**Updated from an older Statamic or fresh install:**
Fresh and clean 

**List of installed addons:**
none

### Logs
I noticed this when I was trying to change the display title for... title. :)
```
fields:
  title: 
    display: Full Name
    instructions: "Team member's full display name"
    validate: required <--- not communicated in UI
```
