### ISSUE TITLE
Suggest fieldtype needs default set as an array

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1888]
### Expected behaviour
To be able to set `default: this-value` on a Suggest typefield and for Statamic to use a string or an array as appropriate.

### Actual behaviour
CP shows spinning loading icon under certain conditions. My context should set a default and allow up to 4.

Does **not** work
```
fields:
  suggest_things:
    type: suggest
    default: this-value
    max_items: 4
    options:
      this-value: This Value
      that-thing: That Thing
```

Does work
```
fields:
  suggest_things:
    type: suggest
    default: 
      - this-value
    max_items: 4
    options:
      this-value: This Value
      that-thing: That Thing
```

### Server Details
**Operating System**:
Linux (remote server)

**Web Server:**
Apache

**PHP Version:**
7.0

**Statamic Version:**
v2.8.10

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
None
