### ISSUE TITLE
Array field with no keys saves empty array

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1891]
### Expected behaviour

Saving a fieldset with an `array` field without any keys should have no `keys` value.

Like this:

```
fields:
  array:
    type: array
```

### Actual behaviour

An empty array is saved, which causes the field on the publish page to be blank.

```
fields:
  array:
    type: array
    keys: []
```
