### ISSUE TITLE
Image icon doesn't show on initial page load

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1899]
### Expected behaviour
After the image is selected in a replicator there is a little icon that shows when the row is collapsed.

![screen shot 2018-04-25 at 7 56 42 am](https://user-images.githubusercontent.com/1793867/39247174-4cd47e8e-485e-11e8-944e-c883d9f34d43.png)

_See the two green icons in the screenshot above_

When you reload the page or visit it though these icons do not show anymore. You have to click to expand the row and then when you collapse they show again (But they won't show if you reload the page).

![screen shot 2018-04-25 at 7 58 29 am](https://user-images.githubusercontent.com/1793867/39247237-7683794c-485e-11e8-9c35-ef439d962971.png)

This is Statamic 2.8.11.

**Comment by jasonvarga** [comment]
Can you give some more details? 
Does this still happen to you?
What values are being saved in those blocks for the images?

**Comment by thestepafter** [comment]
Yes, this is still happening. Basically the icon for the image doesn't show until you expand the replicator block that it is in. Then when you collapse the block the icon shows. The value being saved is an asset (in this case it is a .jpg).

**Comment by thestepafter** [comment]
Here is the content:

```
        content_fields:
          - 
            type: image_set
            image: /assets/img-sample.jpg
          - 
```

And here is the field set:

```
fields:
  image:
    type: assets
    display: Image
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: /
    max_files: 1
    mode: grid
```

**Comment by jasonvarga** [comment]
Does that image exist? Is the URL valid? You should be seeing a thumbnail instead of a generic jpg icon.

**Comment by thestepafter** [comment]
Yes, here is a screenshot of the icon and then when I click to edit the image. (It is a default filler image that I'm using for my site builder.)

![screen shot 2018-06-06 at 10 37 29 am](https://user-images.githubusercontent.com/1793867/41055283-a7a811bc-6975-11e8-9a99-aca01933752c.png)
![screen shot 2018-06-06 at 10 37 20 am](https://user-images.githubusercontent.com/1793867/41055284-a7c19e84-6975-11e8-94e9-43d9e1bd1e43.png)

**Comment by jasonvarga** [comment]
What does your site/settings/assets.yaml look like?

**Comment by thestepafter** [comment]
```
image_manipulation_route: /cache/images
image_manipulation_secure: true
auto_crop: true
image_manipulation_driver: gd
image_manipulation_cached: true
image_manipulation_cached_path: cache/images
image_manipulation_presets:
  small:
    w: 640
    q: 100
thumbnail_max_width: 600
thumbnail_max_height: 600
```
