### ISSUE TITLE
Replicator with Markdown has styling issue

### ISSUE THREAD

**Issue by ericlbarnes** [statamic/v2-hub#190]
<img width="696" alt="screen shot 2015-12-04 at 10 13 16 am" src="https://cloud.githubusercontent.com/assets/116662/11592965/aba4b446-9a6f-11e5-80c8-0b36513c1e6e.png">

Fieldset:

```
my_replicator_field:
      type: replicator
      instructions: |
        Replicate a new set for each piece of content you need.
      sets:
        content_set:
          display: Content
          instructions: A basic block of text
          fields:
            text:
              display: Text
              type: markdown
```
