### ISSUE TITLE
Glide presets: unwanted presets added when some already there

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1909]
### Expected behaviour
Running `php please assets:generate-presets`should first clear the presets folder and then re-generates those presets

### Actual behaviour
`php please assets:generate-presets` is actually adding 2 more unwanted presets to the ones already there.

### Steps to reproduce
1. Define your presets
```
image_manipulation_route: /img
image_manipulation_secure: true
auto_crop: true
image_manipulation_driver: gd
image_manipulation_cached: true
image_manipulation_cached_path: img
image_manipulation_presets:
  xsmall:
    w: 320
    fit: crop
  small:
    w: 640
    fit: crop
  medium:
    w: 990
    fit: crop
  large:
    w: 1140
    fit: crop
  xlarge:
    w: 1760
    fit: crop
thumbnail_max_width: 6000
thumbnail_max_height: 6000
```
2. Generate your presets

3. For any reason, re-generate your presets with the php please command
I then get 2 unwanted new presets per image folder:
- one is 300 wide
- one is a square 1000X1000

### Server Details

**Operating System**:
MAC OS 
**Web Server:**
MAMP
**PHP Version:**
7.0.22 or 7.1
**Statamic Version:**
2.8.11
**Updated from an older Statamic or fresh install:**
update
**List of installed addons:**
Location
Naxi
PowerTools (getting the same behaviour)
Section
