### ISSUE TITLE
Replicator with image throws JS error

### ISSUE THREAD

**Issue by ericlbarnes** [statamic/v2-hub#191]
Setup a replicator with an image or asset: 

```
        image_set:
          display: Image
          instructions: Showcase your adventures in a gallery
          fields:
            photo:
              type: assets
              allowed: [png, jpg, gif]
              destination: assets/img/
            caption:
              type: text
              instructions: Describe the photo
```

Then when adding it to the page it throws these js errors and can't be removed: 

<img width="1094" alt="screen shot 2015-12-04 at 10 16 13 am" src="https://cloud.githubusercontent.com/assets/116662/11593045/16decfc6-9a70-11e5-89f4-f1dd82da9e95.png">
