### ISSUE TITLE
Upload only option for assets fieldtype

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1927]
**Is your feature request related to a problem? Please describe.**
There is no way to only allow uploads. For instance allowing a user to upload their avatar. Currently since there's always a browse button, they can choose other people's avatars.

**Describe the solution you'd like**
An option to disable browsing. eg `browse: false` or `upload_only: true`

**Describe alternatives you've considered**
CSS workaround:

``` css
.assets-fieldtype .manage-assets button:first-child {
    display: none;
}
```

**Additional context**
https://statamic.com/forum/3351-assets-no-browse-only-upload
