### ISSUE TITLE
Single Image Bard Sets inside Partials don't load from string correctly

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1933]
Loving the 2.9 update but I have one issue.  All the single image blocks in Bard fields changes to an Array and no longer are visible in the CP.  

![screen shot 2018-05-21 at 9 33 39 pm](https://user-images.githubusercontent.com/2436728/40338973-1bafaa2a-5d46-11e8-82b8-e70d2b84842c.png)

Any new images, upload like an array, even though only one is allowed.

2.8.12
```
    type: image
    photo: /assets/images/Warriors_to_Welders_FINAL3.jpg
    caption: Warriors to Welders
```

2.9
```
    type: image
    photo:
      - /assets/images/Warriors_to_Welders_FINAL3.jpg
    caption: Warriors to Welders
```

Here is the fieldset:
```
          image:
            display: Image
            fields:
              photo:
                type: assets
                display: Photo
                container: main
                folder: images
                max_files: 1
                restrict: true
                conditions:
                  style: standard
                  conditions: [ ]
              caption:
                type: text
                display: Caption
```

Should I just go through the entries and change them all to arrays?  Seems an array would not be needed for a single image?

**Comment by jasonvarga** [comment]
If you've set `max_files: 1` it should save a string, not an array.
If you're seeing an array, it's wrong. We'll check that out.

**Comment by bgarrant** [comment]
It was always `max_files: 1`.  The .md file was changed to an array when the update from 2.8.12 to 2.9 occurred.

**Comment by jasonvarga** [comment]
When exactly did it change?

- During the update.
- Once on 2.9, when you saved the entry.

Have all your entries been modified?

**Comment by bgarrant** [comment]
They were not modified.  Looks like just the CP is not reading the singles correctly, and any new ones added come in the array format

**Comment by jasonvarga** [comment]
Not modified? I don't understand the before and after snippets of YAML you posted in your original issue then.

Where/when do you see this?

```
    type: image
    photo:
      - /assets/images/Warriors_to_Welders_FINAL3.jpg
    caption: Warriors to Welders
```

**Comment by bgarrant** [comment]
Here is a site I have not updated yet and has 2.8.12 live and 2.9 local.  Looks like they don't change.  

2.8.12
```
    type: image
    photo: /assets/images/bigstockphoto_Serious_Great_Grandmother_426012.jpg
    caption: Home Care Crisis Worry
```
2.9.1
```
    type: image
    photo: /assets/images/bigstockphoto_Serious_Great_Grandmother_426012.jpg
    caption: Home Care Crisis Worry
```

In 2.9.1 CP

![screen shot 2018-05-21 at 10 45 36 pm](https://user-images.githubusercontent.com/2436728/40339496-bd35fb22-5d48-11e8-8392-2d2092c32f3f.png)

**Comment by jasonvarga** [comment]
Can you look at your logs and/or devtools network tab for whats failing in the ajax requests?

**Comment by bgarrant** [comment]
Now in 2.9.1 if I add a NEW block it does this and we can view them sine in the CP
```
    type: image
    photo: 
      - /assets/images/bigstockphoto_Serious_Great_Grandmother_426012.jpg
    caption: Home Care Crisis Worry
```

**Comment by bgarrant** [comment]
![screen shot 2018-05-21 at 10 48 41 pm](https://user-images.githubusercontent.com/2436728/40339585-2790909a-5d49-11e8-8354-4eeddb30b760.png)

**Comment by jasonvarga** [comment]
Yeah click through to see the error. Or, find it in your log file.

**Comment by bgarrant** [comment]
![screen shot 2018-05-21 at 10 50 34 pm](https://user-images.githubusercontent.com/2436728/40339665-6b1820bc-5d49-11e8-8a65-2f39d56b7f76.png)

**Comment by bgarrant** [comment]
```
#0 /home/adkmercy/statamic/core/Http/Controllers/AssetsController.php(174): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/adkmercy/...', 174, Array)
#1 [internal function]: Statamic\Http\Controllers\AssetsController->get()
#2 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#3 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('get', Array)
#4 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), 'get')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'get')
#11 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'get')
#12 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#13 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home/adkmercy/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 /home/adkmercy/statamic/core/Http/Middleware/Outpost.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 /home/adkmercy/statamic/core/Http/Middleware/CP/Localize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 /home/adkmercy/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 /home/adkmercy/statamic/core/Http/Middleware/CpEnabled.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Statamic\Http\Middleware\CpEnabled->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /home/adkmercy/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /home/adkmercy/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /home/adkmercy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /home/adkmercy/public_html/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}  
```

**Comment by jasonvarga** [comment]
It's easier in Chrome. In the network tab one request would be red. Click it. It'll show you the response.

Or, find it in your log file.

**Comment by bgarrant** [comment]
This is happening on all sites we migrated from 2.8.12 to 2.9

**Comment by jasonvarga** [comment]
In the failing request, can you show me the POST payload?

Network tab > Click failing request > Headers tab > Request Payload

**Comment by bgarrant** [comment]
2.8.12 Fieldset
```
taxonomies: false
title: Long Form Content
create_title: ""
hide: true
fields:
  long_form:
    type: bard
    buttons:
      - bold
      - italic
      - anchor
      - h4
      - h5
      - quote
      - assets
    display: Long Form Content
    sets:
      heading:
        display: Heading
        fields:
          heading:
            type: text
            display: Heading
            instructions: 'Heading 4 (PREFERRED SIZE) is a good size for content section headers. Heading 5 is for small breaks in content.'
      image:
        display: Image
        fields:
          photo:
            type: assets
            display: Photo
            container: main
            folder: images
            max_files: 1
            restrict: true
          caption:
            type: text
            display: Caption
      quote:
        display: Pull Quote
        fields:
          quote:
            type: text
            display: The Quote
          cite:
            type: text
            display: Cite
      table:
        display: Table
        fields:
          table:
            type: table
            display: Table
            width: 100
        instructions: '**The first row with be a header row for the table**'
      video:
        display: Video
        fields:
          video:
            type: video
            display: Video
            instructions: 'YouTube URLs: https://www.youtube.com/watch?v=s9F5fhJQo34, Vimeo URLs: https://vimeo.com/22439234, OR mp4, ogv, mov, or webm URLs: http://example.com/video.mp4'
      documents:
        display: Documents
        fields:
          documents:
            type: assets
            display: Documents
            container: main
            folder: files
            restrict: true
      source_code:
        display: Source Code
        fields:
          source_code:
            type: textarea
            display: Source Code
    container: main
    folder: /
    spellcheck: true
    allow_source: true
    force_plain_text: true
    autoLink: true
    target_blank: true
    link_validation: true
    clean_pasted_html: true
```
2.9 Fieldset
```
taxonomies: false
title: Long Form Content
create_title: ""
hide: true
fields:
  long_form:
    type: bard
    buttons:
      - bold
      - italic
      - anchor
      - h4
      - h5
      - quote
      - assets
    display: Long Form Content
    sets:
      heading:
        display: Heading
        fields:
          heading:
            type: text
            display: Heading
            instructions: 'Heading 4 (PREFERRED SIZE) is a good size for content section headers. Heading 5 is for small breaks in content.'
      image:
        display: Image
        fields:
          photo:
            type: assets
            display: Photo
            container: main
            folder: images
            max_files: 1
            restrict: true
          caption:
            type: text
            display: Caption
      quote:
        display: Pull Quote
        fields:
          quote:
            type: text
            display: The Quote
          cite:
            type: text
            display: Cite
      table:
        display: Table
        fields:
          table:
            type: table
            display: Table
            width: 100
        instructions: '**The first row with be a header row for the table**'
      video:
        display: Video
        fields:
          video:
            type: video
            display: Video
            instructions: 'YouTube URLs: https://www.youtube.com/watch?v=s9F5fhJQo34, Vimeo URLs: https://vimeo.com/22439234, OR mp4, ogv, mov, or webm URLs: http://example.com/video.mp4'
      documents:
        display: Documents
        fields:
          documents:
            type: assets
            display: Documents
            container: main
            folder: files
            restrict: true
      source_code:
        display: Source Code
        fields:
          source_code:
            type: textarea
            display: Source Code
    container: main
    folder: /
    spellcheck: true
    allow_source: true
    force_plain_text: true
    autoLink: true
    target_blank: true
    link_validation: true
    clean_pasted_html: true

```
