### ISSUE TITLE
Cannot add locales to the home page

### ISSUE THREAD

**Issue by eddiesigner** [statamic/v2-hub#1981]
**Describe the bug**
I have a website in spanish and english, being spanish the default locale. Before the upgrade I was able to translate the content (`title, slug and text`) for the home page but now I can't because the button to choose a language is missing. I can translate the content from the `index.md` or the `en.index.md` files but not from the control panel.

This issue just happens on the home page. If I try to remove the default home page and create a new one using a custom 'Home page' type I get the same result and all the pages get lost :/

This is my `home.yaml` file (home fieldset):

```yaml
title: Inicio
fields:
  text:
    type: textarea
    display: Texto que se muestra debajo del carrusel
    validate: required
    localizable: true
  bottom_picture_mobile:
    type: assets
    display: Imagen que se muestra hasta abajo de la página (Mobile)
    container: main
    folder: home
    max_files: 1
    validate: required | ext:jpg,jpeg,png
  bottom_picture_desktop:
    type: assets
    display: Imagen que se muestra hasta abajo de la página (Desktop)
    container: main
    folder: home
    max_files: 1
    validate: required | ext:jpg,jpeg,png
taxonomies: false
```

**To Reproduce**
1. Go to 'Pages'
2. Click on 'Home page'
or
1. Go to 'Pages'
2. Create a new page
3. Select type: 'Home'

**Expected behavior**
I would expect to see the locales button so I can switch between languages and modify the content accordly. 

**Screenshots**
Just for the home page I cannot select the english locale because the button is missing:
![screenshot-2018-5-29 panel de control vimaliving](https://user-images.githubusercontent.com/1477503/40676119-0cd6dfd4-637a-11e8-974f-a9f95f974074.png)

But for different pages I can select both languages (spanish and english):
![screenshot-2018-s5-29 panel de control vimaliving](https://user-images.githubusercontent.com/1477503/40676146-2c0b4304-637a-11e8-9747-44d2dad0c763.png)

**Environment details:**
 - Statamic Version: 2.9.4
 - Fresh Install or Upgrade: Upgrade
 - OS: macOS 10.13.4
 - Browser: Firefox Quantum
 - Web Server: Apache
 - PHP Version: 7.1.10
 - Addons installed: None

**Additional context**
This is my `index.md` file:

```yaml
text: >
  Hay variaciones de los pasajes de Lorem Ipsum pero la mayoría SUFREN CIERTAS alteraciones en alguna manera.
bottom_picture_mobile: /assets/home/home-mobile-2.jpg
bottom_picture_desktop: /assets/home/home-desktop-2.jpg
title: Inicio
template: home
fieldset: home
mount: home-slider
id: ace0be7b-a658-4baf-9307-3ca4a5da2c54
```
