### ISSUE TITLE
Asset preview does not work within partial with Symfony Yaml Parser

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#1998]
**Describe the bug**
We different fieldsets including the default fieldset as a partial. But if we do switch the Yaml parser to Symfony, the preview of asset fields does not work anymore – see screenshots.

**To Reproduce**
1. Create two fieldsets. We have `default.yaml` and `award.yaml`.

```yaml
title: Default
fields:
  header_image:
    type: assets
    display: 'Header Image'
    container: main
    folder: images
    restrict: false
    max_files: 1
```

```yaml
title: Award
fields:
  title:
    type: text
    display: Title
    localizable: true
  template:
    type: hidden
    display: Template
    default: award
  award:
    type: suggest
    display: Award
    mode: IfDesignAward
    max_items: 1
    create: false
  long_form:
    type: partial
    display: 'Long Form Content'
    fieldset: default
```

2. Create a page using the `award` fieldset.
3. Upload a header image.
4. Switch the Yaml parser in `system.yaml` to `symfony`

**Expected behavior**
Preview should appear.

**Screenshots**
Without Symfony Yaml:
<img width="337" alt="bildschirmfoto 2018-06-03 um 16 49 49" src="https://user-images.githubusercontent.com/522446/40888424-2509fefc-6757-11e8-98d4-9f2342b13aae.png">

and with:
<img width="332" alt="bildschirmfoto 2018-06-03 um 16 49 36" src="https://user-images.githubusercontent.com/522446/40888438-438c0186-6757-11e8-8b81-73f2e44f5d56.png">

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.6
 - Fresh Install or Upgrade: Updated from 2.8.12
 - OS: macOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: Spock, MinifyHTML, IfDesignAward (our own)
