### ISSUE TITLE
Date fields can break after Symfony YAML converts date-like strings to a UNIX timestamp

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#1999]
**Describe the bug**
Normal text fields get converted to timestamps with the Symfony Yaml parser.

EDIT: This also breaks date fields as the date picker cannot load because of a JS error.

**To Reproduce**
1. Have a fieldset something like:

```yaml
title: Default
sections:
  main:
    display: Main
    fields:
      headline:
        type: text
        display: Headline
```

2. Create a page.
3. Edit the Yaml file of the new page and set `headline: 2018-01-01`
4. Reload the page editor page and see the headline field containing `1514764800`

**Environment details (please complete the following information):**
 - Statamic Version 2.9.6
 - Fresh Install or Upgrade: Updated from 2.8.12
 - OS: macOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2
