### ISSUE TITLE
secondary addon-fieldtypes are not displayed inside a grid fieldtype

### ISSUE THREAD

**Issue by eike-hass** [statamic/v2-hub#2001]
**Describe the bug**
"secondary" addon-fieldtypes don't seem to work in a grid field.

**To Reproduce**
1. Configure a grid fieldtype like so 
```yaml
box:
    type: grid
    display: Box
    fields:
      field_1: 
       type: custom_addon
      text:
        type: text
        display: Field_2
      linkUrl:
        type: text
        display: Field_3
      textfarbe:
        type: custom_addon.secondary_4
        display: Field_4
        mode: custom
        default: '#FFFFFF'
      textfarbe_1:
        type: custom_addon.secondary_5
        display: Field_5
      textfarbe_2:
        type: custom_addon.secondary_6
        display: Field_6
      textfarbe_3:
        type: custom_addon.secondary_7
        display: Field_7
    mode: table
    add_row: Box hinzufügen
````
2. See the screenshot for result

**Expected behavior**
All addon-fieldtypes should be displayed inside a grid.

**Screenshots**
![gridfieldtypes](https://user-images.githubusercontent.com/3441319/40926541-bc39b234-681c-11e8-80fd-2812fe30ff09.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.8.X and 2.9.X
 - Upgrade
 - OS: All it seems
 - Browser: chrome
 - Web Server: Apache
 - PHP Version: 7.1.X

 - Addons installed:

**Additional context**
There seems no be no js exception
