### ISSUE TITLE
Official support for Minio as asset storage

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#2008]
**Is your feature request related to a problem? Please describe.**
Add official support for Minio to store assets. We got this working, using the S3 driver and modifying the `asset.yaml` file afterwards:

```yaml
title: 'Main Assets'
driver: s3
key: AKIAIOSFODNN7EXAMPLE
secret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
bucket: assets
use_path_style_endpoint: true
region: us-east-1
endpoint: 'http://127.0.0.1:9000'
```

**Describe the solution you'd like**
Add documentation about using Minio as storage. As of Minio is fully compatible with the S3 driver, adapting the CP to add a toggle to set `use_path_style_endpoint` should be enough :-)
