### ISSUE TITLE
FR: Specify name formats for uploads on entries

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#2027]
**Is your feature request related to a problem? Please describe.**

Clients suck at naming things. Duplicate, unrelated, and bad names make the assets folder messy, hard to manage and also don't make for semantic, accessible pages with good SEO.

**Describe the solution you'd like**

The ability to set a format for the naming of upload files with variables taken from the entry they are uploaded against e.g. `{{ slug }}--hero`, `{{ slug }}--floor-plans` etc [file extension maintained].

In some instances where you have more arbitrary assets such as gallery images or a bunch of relevant files to download it would be more useful to automatically add these to a sub folder related to the entry e.g. `/downloads/{{ slug }}/` and a new sub-folder would be made.

It would also be useful to be able to carry through the original filename if required.

I guess these would be set in the fieldset YAML
```
my_asset_field:
  type: assets  
  container: downloads
  folder: '/jobs/{{ slug }}'
  filename: 'Acme-Inc__{{ slug }}-job--{{ filename }}'
  restrict: true
```
