### ISSUE TITLE
multiple locales: {{ locale:url }} returns the wrong URLs if relative URLs are defined in system.yaml

### ISSUE THREAD

**Issue by ASochat** [statamic/v2-hub#2044]
**Describe the bug**

I have two locales on my website: EN (default) and FR. In my `system.yaml` file, I defined relative URL for each one. When updating from statamic 2.8.12 to 2.9.0, `{{ locales }} {{ url }} {{ /locales }}` now inserts the segment corresponding to the first $locale in the URL. Example for the page `foo.dev/en/stuff`, it returns:
```
foo.dev/en/stuff
foo.dev/en/fr/chose
```

**To Reproduce**
1. Change your URLs to relative ones in `system.yaml`file
1. Downgrade to 2.8.12 and check if the code above works
2. Upgrade to 2.9.0 and see it's not working

**Expected behavior**
The URLs should match the real ones, without
```
foo.dev/en/stuff
foo.dev/fr/chose
```

**Environment details (please complete the following information):**
 - Statamic Version [2.9.0]
 - Browser: [chrome]
 - Web Server: [ Nginx]
 - PHP Version: [eg. 7.2]

**Additional context**
I think it comes from the following FIX of 2.9.0 update : 

"`URL::makeAbsolute()` now uses the URL defined in `system.locales` when absolute. When relative, it just gets a bit smarter. #1882 "

Here is what's in my `system.yaml` file:
```
locales:
  en:
    full: en_EN
    name: English
    url: /en/
  fr:
    full: fr_FR
    name: French
    url: /fr/
```

If I set absolute URLs (like https://foo.com) it works fine, it starts returning errors only with relative URLs.

A workaround is to change the absolute URLs depending on the environments, though I'd like to work with relative URLs on my local machine.

**Comment by iljapanic** [comment]
I was having the same issue with locales on my site.

Changing the relative URLs to absolute ones in my `system.yaml` fixed it. Thanks for the tip @ASochat.

However, now I have to maintain separate config files for each environment. It would be great if locales worked with relative URLs like they used to before the 2.9.0 update.

**Comment by 1stevengrant** [comment]
@iljapanic why not move that into environment variables in that case?

**Comment by jasonvarga** [comment]
In `statamic/core/Data/Content/Content.php` try changing line 167 to

```
return URL::makeAbsolute($this->uri(), $this->locale());
```

**Comment by manogi** [comment]
I have the same problem (2.9.8), and when I follow @jasonvarga 's advice the locale in all three links (i have three locales) just stays the the current locale - so that does not work for me?
My fix for now: in my .env file i have:
```
SITE_ROOT=https://mydomain.test
``` 
and in systems.yaml:

```
  de:
    name: Deutsch
    full: deu
    url: {env:SITE_ROOT}/
  en:
    name: English
    full: eng
    url: {env:SITE_ROOT}/en/
  fi:
    name: Finnish
    full: fin
    url: {env:SITE_ROOT}/fi/
```
