### ISSUE TITLE
Assets button shows in redactor when it shouldn't

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2046]
The assets button is showing in the redactor field with the following settings:

buttons:
  - bold
  - italic
  - link

![assets-button-showing](https://user-images.githubusercontent.com/1793867/42292298-518e18f4-7f86-11e8-9094-23442ce3297a.png)

Expected functionality is if image / file isn't in the settings then the assets button shouldn't show.

**Comment by jasonvarga** [comment]
Please show me the configuration for this field.

eg.

```
redactor_field:
  type: redactor
  etc...
```

**Comment by thestepafter** [comment]
```
  redactor:
    type: redactor
    display: Redactor
    settings: Builder
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: /
```

I found the problem, if a container is set then the assets icon shows. I removed the `container:` line and now the icon doesn't show. Should probably fix this so even if a container is defined if it isn't a setting in the redactor settings the icon doesn't display.
