### ISSUE TITLE
Localized Routes for Pages

### ISSUE THREAD

**Issue by tschmidiger** [statamic/v2-hub#2053]
If you have multiple locales you might want to assign different routes for each page. A similiar feature is already given, but it applies only to collection and/or taxonomy routes.

A possible solution could look like this:

**Definition of the localized page routes in routes.yaml**

```
/english-url:
    template: mytemplate
    load: c9f6fcd3-5b08-4b03-a411-901eea319123
    locale: en
/deutsche-url:
    template: mytemplate
    load: c9f6fcd3-5b08-4b03-a411-901eea319123
    locale: de
```

Additionally the **Route class (statamic/core/Routing/Route.php:66) must be updated** in order to make use of the locale parameter in the routes file and load the localized data for the requested page:

```
if(!empty($this->data['locale']) && $content->hasLocale($this->data['locale'])) {
    return $content->in($this->data['locale'])->toArray();
}
return $content->toArray();
```

I created a helper controller as a work-around. But I think it would make more sense to implement this feature into the core system...
