### ISSUE TITLE
Grid always stacked if conditional on field

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2057]
**Describe the bug**
In an addon's settings, if you have a grid that's conditional on another field, the grid is always in `stacked` mode, instead of `table`

**To Reproduce**
1. Create addon settings w/ these fields:
```
fields:
  add_new_users:
    type: toggle
    display: Add New Users?
  user_merge_fields:
    type: grid
    display: 'Merge & Form Field Mapping'
    fields:
      tag:
        type: text
        display: Mailchimp Merge Tag
        instructions: **Case Matters**! Upper case only please.
        width: 50
      field_name:
        type: text
        display: Field Name
        instructions: '&nbsp;'
        width: 50
    add_row: Add Merge Field
    show_when:
      add_new_users: true
```
2. Load the addon settings

**Expected behavior**
That grid is in `table` mode

**Screenshots**
<img width="913" alt="2018-07-13 at 9 30 pm" src="https://user-images.githubusercontent.com/6069653/42720832-0f52f6c0-86e4-11e8-8a70-40d02ed11c77.png">

vs
<img width="871" alt="2018-07-13 at 9 31 pm" src="https://user-images.githubusercontent.com/6069653/42720839-2652177a-86e4-11e8-8f42-a4d476651b3e.png">

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.8
