### ISSUE TITLE
FR: Collapsable Sections

### ISSUE THREAD

**Issue by KimKJDesigns** [statamic/v2-hub#2080]
**Problem:** I'm breaking up my fieldset options with sections like normal, however, all options are being displayed at all times. Because I have chosen to use replicators, I'm unable to use conditionals to display options required for each block. So I display all of them. This leads to blocks with a wealth of options but everything is displayed on the screen, whether it's needed or not. _Note: the following image only has three sections but other blocks have up to 7 sections_

![image](https://user-images.githubusercontent.com/4345295/43238261-ce25de14-90d0-11e8-823d-73dc7cb42d77.png)

**Solution:** Since there isn't any plans to roll out conditionals for Replicators, Grid or Bard fields, perhaps there can be a simpler solution to collapse sections instead. It isn't ideal but if I can collapse the contents of a section, I would be able to hide the block settings until it is required, if at all. The child fields would all be collapsed up to the next section and when we click the "show" button it will display all the fields, up to the next section.

![image](https://user-images.githubusercontent.com/4345295/43238609-23aef4c8-90d2-11e8-8ccb-186019e461ab.png)

**Alternatives:** I've tried conditionals, which would be the best solution as I can control exactly what fields are being displayed for each block through my partials. 

**Code:** 
```
fields:
  section_section:
    type: section
    display: Section Settings
    collapse: true    (default: false)
  section_display_mobile:
    type: toggle
    display: Visible On Mobile
    instructions: Select the device sizes which this section should appear on.
    width: 33
    default: true
    replicator_preview: false
```
