### ISSUE TITLE
Textfield doesn’t like to have it’s bottom touched

### ISSUE THREAD

**Issue by miktirr** [statamic/v2-hub#2104]
**Describe the bug**
When an entry is first opened, the user is unable to click or select the bottom of a textfield ([see video](http://sisalto.finnlectura.fi/temp/2018-08-06-statamic-textfield.mp4)).

If the window is resized even a little, the field fixes itself ([see another video](http://sisalto.finnlectura.fi/temp/2018-08-06-statamic-textfield-window-resize.mp4)).

(Overall could have something to do with the size of the window. I seem to be able to recreate this more consistently with full screen windows.)

**To Reproduce**
1. Open an entry with CP.
2. Try to click the last lines of a textfield.
3. Be rejected.

**Environment details**
 - Statamic 2.10.3 (upgraded)
 - OS: macOS 10.13.6
 - Browser: Chrome (68.0.3440.84)

**Comment by jasonvarga** [comment]
Can you post your fieldset?

**Comment by miktirr** [comment]
```
title: Julkaisu
hide: true
taxonomies: false
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        display: Otsikko
        instructions: Julkaisun otsikko. Selkeyden vuoksi nimen olisi hyvä olla uniikki.
        localizable: true
      section_main:
        type: section
        display: Perustiedot
        instructions: Julkaisun yleistietojen syöttäminen. Nämä tiedot esitetään tuotesivulla.
      subtitle:
        type: text
        display: Alaotsikko
        instructions: Julkaisun mahdollinen alaotsikko.
      isbn:
        type: list
        display: ISBN
        instructions: >
          Tähän kenttään julkaisun ISBN väliviioilla ja ilman sanaa ISBN. Eli esimerkiksi
          `978-951-792-543-3`.
        width: 50
      tuotenumerotog:
        type: toggle
        display: Tuotenumero
        instructions: >
          Korvaa ”ISBN” -sana sanalla ”Tuotenumero”. Tämän päälle esimerkiksi oppimispeleissä,
          joilla on ISBN:n sijasta GTIN.
        width: 25
      releasedate:
        type: date
        allow_time: false
        allow_blank: true
        display: Julkaisupäivä
        instructions: Julkaisun ilmestymispäivä. Tämän perusteella julkaisua kohdellaan uutena.
        width: 50
      lowprofile:
        type: toggle
        display: Älä näytä etusivulla
        instructions: Älä näytä julkaisua etusivulla.
        width: 25
      tekijat:
        type: list
        display: Tekijä(t)
        instructions: Teoksen tekijä(t). `Etunimi Sukunimi`, jokainen omalle rivilleen.
        width: 75
      description:
        type: markdown
        display: Takakansi
        instructions: Julkaisun esittely/takakansiteksti
        cheatsheet: true
        width: 75
        container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
        folder: julkaisut-liitteet
      cover:
        type: assets
        display: Kansikuva
        instructions: Julkaisun kansikuva
        container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
        folder: kansikuvat
        max_files: 1
        width: 25
      shortdescription:
        type: markdown
        display: Lyhyt kuvaus
        instructions: >
          Lyhyttä kuvausta käytetään mm. sarja-sivulla. Jos lyhyttä kuvausta ei anneta, takakansitekstiä
          lyhyennetään tilanteen mukaan.
        width: 75
      pagecount:
        type: text
        display: Sivumäärä
        instructions: Julkaisun sivumäärä
        width: 33
      printsize:
        type: text
        display: Painoasu
        instructions: Julkaisun painoasu
        width: 33
      onlydigital:
        type: toggle
        display: Saatavilla vain Digimateriaaleista
        instructions: Piilottaa ”Jälleenmyyjät” -painikkeen julkaisun tiedoista.
        width: 25
      forceorder:
        type: text
        display: Mahdollinen erikoisjärjestys julkaisusarjassa
        instructions: >
          Sarjaan kuuluvat julkaisut järjestetään oletusarvoisesti aakkosjärjestykseen. Tällä kentällä
          on kuitenkin mahdollista antaa muu järjestys. Esimerkiksi _Everyday English Starter_ on sarjan
          ensimmäinen osa, vaikka _Everyday English 1_ tulisi aakkosissa ensin. Siksi _Starterille_
          annettaisiin tähän kenttään `1`.
        width: 50
      section_sample:
        type: section
        display: Näytteet
        instructions: Näytteitä julkaisusta ladattavaksi
      naytesivut:
        type: assets
        display: Näytesivut
        instructions: Lisää julkaisusta näytesivut (PDF-tiedosto).
        container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
        folder: naytesivut
        max_files: 1
        width: 33
      aaninayte:
        type: assets
        display: Näyte äänitteestä
        instructions: Lisää julkaisusta näytesivut (MP3-tiedosto).
        container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
        folder: aaninaytteet
        max_files: 1
        width: 33
      section_meta:
        type: section
        display: Luokittelutiedot
        instructions: >
          Näitä tietoja käytetään ennen muuta julkaisun luokitteluun ja esittämiseen verkkosivuila
          oikeissa paikoissa.
      class:
        type: radio
        display: Julkaisuluokka
        instructions: Onko julkaisu oppimateriaali vai tietokirja?
        options:
          oppimateriaalit: Oppimateriaali
          tietokirjat: Tietokirjat
      langcategories:
        type: taxonomy
        taxonomy: langcategories
        create: false
        display: Oppimateriaali
        instructions: Minkä kielen tai aiheen oppimateriaali julkaisu on
        max_items: 1
        sort: name:asc
        label: '{{ title }}'
        width: 50
      series:
        type: taxonomy
        taxonomy: series
        create: false
        display: Julkaisusarja
        instructions: Jos julkaisu on osa sarjaa, valitse sarja
        max_items: 1
        sort: name:asc
        label: '{{ title }}'
        width: 50
      nonficcategories:
        type: taxonomy
        taxonomy: nonficcategories
        create: false
        display: Tietokirjallisuus
        instructions: Minkä aiheen tai alan tietokirja julkaisu on
        max_items: 1
        sort: name:asc
        label: '{{ title }}'
        width: 50
      section_extra:
        type: section
        display: Oheismateriaalit
        instructions: >
          Tähän julkaisuun liittyvien oheismateriaalien tiedot. Oheisjulkaisut on täytynyt lisätä ensin
          erikseen. Tässä vain osoitetaan asioiden välinen yhteys.
      subpubs:
        display: Oheismateriaalit
        type: collection
        collection:
          - subpublications
        instructions: Julkaisun oheismateriaalit.
      section_notes:
        type: section
        display: Muistiinpanoja
        instructions: Julkaisuun liittyviä muistiinpanoja. Näitä ei näytetä verkossa.
      notes:
        type: textarea
        display: Muistiinpanoja
        instructions: Muistiinpanoja sisäiseen käyttöön.
        width: 50
      extraisbn:
        type: list
        display: ISBN
        instructions: >
          Julkaisuun liittyvät vanhat tai ylimääräiset ISBN:t. Esimerkiksi `978-951-792-543-3
          (vanhentuneen opetussuunnitelman mukainan painos)`.
        width: 50
```
