### ISSUE TITLE
Can't set default value of Date fieldtype to null in a grid

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2106]
**Describe the bug**

I would like a date field in a grid that defaulted to `null` or empty.

**To Reproduce**
1. add a Date fieldtype to a fieldset in a grid
2. set `default: null` and `allow_blank: true`
3. view fieldset in cp

**Expected behavior**
empty date field

**Environment details (please complete the following information):**
 - Statamic Version - 2.10.3

**Comment by jasonvarga** [comment]
Just get rid of `default: null`. It'll be null by default if allow_blank is true

**Comment by edalzell** [comment]
I tried that too, didn't work.

**Comment by jasonvarga** [comment]
Seem fine here. What else is in your fieldset?

**Comment by edalzell** [comment]
```
fields:
  charge_formsets:
    type: suggest
    mode: form
    display: Forms
    width: 33
  charge_collections:
    type: suggest
    mode: collections
    display: Collections
    width: 33
  currency:
    type: text
    validate: required
    width: 33
    default: usd
  statuses_section:
    type: section
    display: Statuses
    instructions: What would you like to call the statuses?
  active:
    type: text
    default: Active
    width: 25
  canceling:
    type: text
    default: Canceling
    width: 25
  past_due:
    type: text
    default: Past Due
    width: 25
  canceled:
    type: text
    default: Canceled
    width: 25
  roles_section:
    type: section
    display: Plans & Roles
  plans_and_roles:
    type: grid
    display: 'When a user registers and subscribes to a plan, give them a role'
    fields:
      plan:
        type: suggest
        mode: charge.stripe_plans
        display: 'Stripe Plan'
        validate: required
        max_items: 1
      billing_date:
        type: date
        display: Billing Date
        allow_time: false
        allow_blank: true
      prorate:
        type: toggle
        default: true
      role:
        type: user_roles
        display: 'Role to add to user'
        validate: required
        max_items: 1
    mode: table
    add_row: Add Plan & Role
  templates_section:
    type: section
    display: Email Setting
  from_email:
    type: text
    width: 33
  canceled_email_template:
    type: template
    width: 33
  payment_failed_email_template:
    type: template
    width: 33
```

**Comment by edalzell** [comment]
actually I'm on 2.10.2, not 2.10.3 as I said

**Comment by edalzell** [comment]
this is what I see: <img width="955" alt="2018-08-06 at 10 50 am" src="https://user-images.githubusercontent.com/6069653/43732449-9d78b446-9966-11e8-82bc-cb983dc1b2de.png">

**Comment by jasonvarga** [comment]
What's in your data?

**Comment by edalzell** [comment]
```
charge_formsets:
  - charge
currency: cad
active: Active
canceling: Canceling
past_due: Past Due
canceled: Canceled
plans_and_roles:
  - 
    plan: associate
    role:
      - d32e14fb-08c9-44c2-aaf8-21200852bafd
  - 
    plan: small
    role:
      - 5cd3954c-3cb4-4ef3-b2a1-b1531d2fbb2f
```

**Comment by jasonvarga** [comment]
New rows come in with blank dates though, right?

**Comment by edalzell** [comment]
Yes, interesting.

**Comment by jasonvarga** [comment]
Okay, thanks.

**Comment by lukeagsmith** [comment]
I've just bumped into this too.

Existing grid rows with no date set display with today's date when editing an entry.

It's causing a problem for the client as they have to remember to delete the date against on some rows time they save - which of course they don't remember to do - and erroneous dates keep getting into the data.

`v2.11.3`

**Comment by gsenior** [comment]
I have also just stumbled across the same issue as well, using version 2.11.6.

My grid before saving:

![grid-before-save](https://user-images.githubusercontent.com/768967/51324389-8317c100-1a62-11e9-9c02-d3c8a4596502.png)

My grid after saving, navigating away and editing again:

![grid-after-save](https://user-images.githubusercontent.com/768967/51324434-9dea3580-1a62-11e9-9be9-3b18653466ae.png)

The bottom two rows don't have any dates in the underlying YAML, unless saved again:

```
ticket_types:
  -
    ticket_label: Freebird
    member_price: 0
    non_member_price: 0
    expires_on: '2019-01-16'
  -
    ticket_label: 'Free for Members (£50 for Non)'
    member_price: 0
    non_member_price: 50
  -
    ticket_label: 'Full Bag-O-Mashins'
    member_price: 145
    non_member_price: 190
```
