### ISSUE TITLE
Attempting to save a collection entry using a replicator field causes an array to string conversion error

### ISSUE THREAD

**Issue by cdransf** [statamic/v2-hub#213]
Attempting to save an entry using the following fieldset (generated via the cp) causes an error pointing to `/statamic/core/API/YAML.php:71`:

```
title: Note
fields:
  title:
    type: text
    display: Title
  tags:
    type: taxonomy
    taxonomy: tags
    display: Tags
  post_type:
    type: radio
    display: Note type
    options:
      Text: text
      Link: link
  link:
    type: text
    display: Note link
  content:
    type: replicator
    sets:
      text:
        display: Text
        instructions:
        fields:
          text_field:
            type: markdown
            display: Text field
            instructions: null
      code:
        display: Code
        instructions:
        fields:
          code_field:
            type: textarea
            display: Code
            instructions: null
      quote:
        display: Quote
        instructions:
        fields:
          quote_field:
            type: textarea
            display: Quote field
            instructions: null
```
