### ISSUE TITLE
Grid systems not working correctly

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2148]
I have a couple of grid sytems on my website and i had them set on stacked. My customer didn't find it clear enough to work in so i had to set them on table. Now i get a couple of problems:

problem 1:
I have a grid field with a couple of fields and another grid field in it.
It shows in stacked mode (even though the setting is table) and after resizing the browser this happens.
![image](https://user-images.githubusercontent.com/20043831/44843383-8394f400-ac48-11e8-98b4-9e58871f4b7f.png)

problem 2:
for the same grid on a different page.
It shows in stacked mode (the setting is in table) and after resizing the browser it will show the table view, but its annoying that i have to resize before it show the correct view. I can't sell this to my customers.

Before resizing:
![image](https://user-images.githubusercontent.com/20043831/44843995-f783cc00-ac49-11e8-84d8-6709ae7e2e05.png)

After resizing:
![image](https://user-images.githubusercontent.com/20043831/44844040-18e4b800-ac4a-11e8-9bca-1f304d3a8739.png)

**Comment by jackmcdade** [comment]
We fixed this in 2.10.1. If you're still having an issue, could you let us know what version you're on and post that fieldset?

**Comment by 4kets** [comment]
The website is on 2.10.4.
And here is the fieldset.
```
sections:
  blocks:
    dienst:
      fields:
        image:
          container: main
          folder: img
          restrict: false
          max_files: 1
          type: assets
          display: image
          dienst_title_color:
          options:
            blue: Blue
            mediumblue: 'Medium blue'
            darkblue: 'Dark blue'
            green: Green
            red: Red
            orange: Orange
          type: select
          width: 50
          display: 'Dienst title color'
        dienst_title:
          type: text
          display: 'Dienst title'
          width: 50
        text:
          restrict_assets: false
          type: redactor
          display: tekst
          btn:
            max_rows: 1
            fields:
              url:
                type: text
                display: url
              btn_color:
                options:
                  btn-blue: Blue
                  btn-mediumblue: 'Medium blue'
                  btn-darkblue: 'Dark blue'
                  btn-green: Green
                  btn-red: Red
                  btn-orange: Orange
                  btn-pink: Pink
                type: select
                display: 'Button color'
              btn_text:
                type: text
                display: 'button text'
            type: grid
            display: button
          type: grid
          display: dienst
```
