### ISSUE TITLE
Collection:previous tag pulling random links

### ISSUE THREAD

**Issue by wratke** [statamic/v2-hub#2161]
I've created fields on a collection type called projects that are used to assign different sort values based on category. In order to create previous/next links that use that assigned order, I've used the collection:previous and collection:next tags. The next link works as expected, but the previous doesn't. I've posted the tags for the general category (which uses the general_sort field to establish the order of the projects).

```
<a class="work-prev work-nav-icon" href="{{ collection:previous in='project' sort=general_sort general_sort:isnt='' show_unpublished='false' as='posts' wrap='true' limit='1' }}{{ posts }}{{ site_url }}project/{{ client | slugify }}/{{ project_title | slugify }}{{ /posts }}{{ /collection:previous }}?cat=general">
      // previous icon
</a>
<a class="work-next work-nav-icon" href="{{ collection:next in='project' sort='general_sort' general_sort:isnt='' show_unpublished='false' as='posts' wrap='true' limit='1' }}{{ posts }}{{ site_url }}project/{{ client | slugify }}/{{ project_title | slugify }}{{ /posts }}{{ /collection:next }}?cat=general">
      // next icon
</a>
```

The next link works as expected, the previous link seems to pick a project randomly, the variables I'm using on the collection:next tag don't work in the same way when used on the collection:previous tag.

So, When I click on the next project link for the project that's been assigned the value of 4 for the general_sort field in the CMS, it navigates to the project with a value of 5 for general_sort. If I click on the previous project link generated above for project 4, instead of going to project 3, the project it pulls using the collection:previous tag is completely random.

**Environment details (please complete the following information):**
 - Statamic Version 2.10.4
 - Fresh Install or Upgrade:
 - OS: Windows 10
 - Browser: Chrome
 - Web Server: Apache
 - PHP Version: 7.1
 - Addons installed:

**Comment by wratke** [comment]
Here's the data for the projects assigned the values 3, 4, and 5 for general_sort and the fieldset for the projects.

Project 3
```
title: '‘Climate Change Is Coming’'
project_title: '‘Climate Change Is Coming’'
associated_images:
  - grid_images/pch-climatechange/ninesixteen-project-pch-climatechange-00.jpg
general_sort: '3'
exhibit_sort: '2'
id: db730d3f-602b-4a3d-9e0c-14a6a7aff18e
services:
  - exhibit-design
  - environmental-graphic-design
  - spatial-planning
  - industrial-design
```

Project 4
```
title: 'Wellington Gastropub'
project_title: 'Wellington Gastropub'
associated_images:
  - grid_images/WGP/ninesixteen-project-wellingtongastropub-00.jpg
general_sort: '4'
web_sort: '2'
call_to_action: 5efa6dc0-9d03-4ba7-800c-ef2163487d75
id: 8a1fda5e-afed-4c1e-91a6-896b15d14334
services:
  - online-strategy
  - web-copywriting
  - web-design
  - web-development
```

Project 5
```
title: Atlas
project_title: Atlas
associated_images:
  - grid_images/Atlas/ninesixteen-project-toh-atlas-00.png
general_sort: '5'
branding_sort: '6'
call_to_action: 5efa6dc0-9d03-4ba7-800c-ef2163487d75
id: e7a85256-a2a3-49b9-b000-aec12e80ab1e
services:
  - brand-identity
  - naming
  - brand-strategy
```

Project Fieldset
```
title: Project
sections:
  main_info:
    display: Main Info 
    fields:
      instructions:
        type: section
        display: Main Info
        instructions: Select 'Visit URL' from the drop down labeled 'Live Preview' to get the full URL to the project page.
      title:
        type: text     
      project_title:
        type: text 
        display: Overlay Title
        width: 60 
        rows: 10
        instructions: The text displayed in the overlay on the grid.
        validate: required
      client:
        type: text 
        display: Client
        width: 60 
        validate: required
      services:
        type: taxonomy
        taxonomy: services
        display: Services
        width: 60 
      collaborators:
        type: taxonomy
        taxonomy: collaborators
        display: Collaborators
        width: 60 
      highlighted_image:
        type: collection
        collection: grid_section 
        display: Highlighted Image
        instructions: This is the image that appears directly below the header.
        max_items: 1 
      description: 
        type: textarea
        display: Description
        validate: required
      grid_section_ids:
        type: collection
        collection: grid_section 
        display: Grid Sections 
      associated_image:
        type: assets
        container: grid_images 
        display: Associated Image
        instructions: Used for the layouts on the main Work page and the work category pages. 
        width: 60 
        max_files: 1
  sort_info:
    display: Sorting Info
    fields:
      general_sort:
        display: Work Page Sort Order
        type: text
      branding_sort:
        display: Branding, Identity & Strategy Sort Order
        type: text 
      exhibit_sort:
        display: Exhibit Design & Environments Sort Order
        type: text 
      print_sort:
        display: Print Design & Packaging Sort Order
        type: text 
      web_sort:
        display: Web Design & Interactive Sort Order
        type: text 
      illustration_sort:
        display: Illustration & Iconography Sort Order
        type: text 
  module_section: 
    display: Modules
    fields:
      module_top:
        type: section 
        display: Modules
        instructions: To remove a module, leave the input blank.
      testimonial:
        type: collection
        collection: testimonial
        display: Testimonial
        width: 60 
        max_items: 1
```
