### ISSUE TITLE
Nested if statement breaking ifelse statment

### ISSUE THREAD

**Issue by wratke** [statamic/v2-hub#2162]
I had the following conditional statements that were working without any problems, all of a sudden they've stopped working:

```
        {{ relate:grid_section_ids }} 
          {{ if section_type == "WorkImage-FiveSquaresLeft" }}
               // show images
          {{ elseif section_type == "WorkImage-SingleLarge" }}
              // show images
          {{ elseif section_type == "WorkImage-Single_1.5H" }}
             // show images
          {{ elseif section_type == "WorkImage-Single_2H" }}
            // show images
          {{ elseif section_type == "WorkImage-Description" }}
            // show images
          {{ else }}
            // the default images
          {{ /if }}
        {{ /relate:grid_section_ids }}
```

Here's the fieldset info for the section_type I'm using in the conditional:
```
title: Single Project Grid Section 
fields:
  section_type:
    type: select
    display: Section Layout
    options:
        - WorkImage-SingleLarge
        - WorkImage-Single_1.5H
        - WorkImage-Single_2H
        - WorkImage-TwoSquares
        - WorkImage-EightSquares
        - WorkImage-FiveSquaresRight
        - WorkImage-FiveSquaresLeft
        - WorkImage-Description
    validate: required 
```

And here's an example of a grid section that match the WorkImage-Description conditional:
```
section_type: WorkImage-Description
grid_title: 'This is a Title'
grid_description: 'This is some text!'
title: text
id: 727d4706-f5db-4aa3-90d1-5734a83d05dd
```

However, all of the sections are defaulting to the default template included in the last part of the if/else statement, including the one above which was triggering the WorkImage-Description without any problems an hour ago. This was working fine, all of a sudden the conditional statement is matching anything and the template has broken. Is there any reason why conditionals would arbitrarily stop working? 

Here's the full fieldset for the grid_section collection type:

```
title: Single Project Grid Section 
fields:
  section_type:
    type: select
    display: Section Layout
    options:
        - WorkImage-SingleLarge
        - WorkImage-Single_1.5H
        - WorkImage-Single_2H
        - WorkImage-TwoSquares
        - WorkImage-EightSquares
        - WorkImage-FiveSquaresRight
        - WorkImage-FiveSquaresLeft
        - WorkImage-Description
    validate: required 
  grid_title:
    display: Section Title
    type: text
    width: 60 
    show_when:
      section_type: WorkImage-Description 
    validate: required_if:fields.section_type,WorkImage-Description
  grid_description:
    display: Section Description
    type: textarea 
    width: 60 
    show_when:
      section_type: WorkImage-Description
  single_rectangle:
    type: assets
    container: grid_images 
    display: Rectangle Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 3040px X 1487px. 
    show_when:
      section_type: WorkImage-SingleLarge
    validate: required_if:fields.section_type,WorkImage-SingleLarge
  single_square:
    type: assets
    container: grid_images 
    display: Square Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-SingleLarge
    validate: required_if:fields.section_type,WorkImage-SingleLarge
  single_1_5_rectangle:
    type: assets
    container: grid_images 
    display: Rectangle Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 3040px X 2266px. 
    show_when:
      section_type: WorkImage-Single_1.5H
    validate: required_if:fields.section_type,WorkImage-Single_1.5H
  single_1_5_square:
    type: assets
    container: grid_images 
    display: Square Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-Single_1.5H
    validate: required_if:fields.section_type,WorkImage-Single_1.5H
  single_double_height:
    type: assets
    container: grid_images 
    display: Square Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 3040px X 3040px.  
    show_when:
      section_type: WorkImage-Single_2H
    validate: required_if:fields.section_type,WorkImage-Single_2H
  double_left:
    type: assets
    container: grid_images 
    display: Left/Top Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-TwoSquares
    validate: required_if:fields.section_type,WorkImage-TwoSquares
  double_right:
    type: assets
    container: grid_images 
    display: Right/Bottom Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-TwoSquares
    validate: required_if:fields.section_type,WorkImage-TwoSquares
  eight1:
    type: assets
    container: grid_images 
    display: Image 1
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight2:
    type: assets
    container: grid_images 
    display: Image 2
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight3:
    type: assets
    container: grid_images 
    display: Image 3
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight4:
    type: assets
    container: grid_images 
    display: Image 4
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight5:
    type: assets
    container: grid_images 
    display: Image 5
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight6:
    type: assets
    container: grid_images 
    display: Image 6
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight7:
    type: assets
    container: grid_images 
    display: Image 7
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  eight8:
    type: assets
    container: grid_images 
    display: Image 8
    width: 60 
    max_files: 1
    instructions: Image should be at minimum 732px X 732px.  
    show_when:
      section_type: WorkImage-EightSquares
    validate: required_if:fields.section_type,WorkImage-EightSquares
  five_large_right:
    type: assets
    container: grid_images 
    display: Large Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresRight
    validate: required_if:fields.section_type,WorkImage-FiveSquaresRight
  five_small1_right:
    type: assets
    container: grid_images 
    display: Small Image Top Left
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresRight
    validate: required_if:fields.section_type,WorkImage-FiveSquaresRight
  five_small2_right:
    type: assets
    container: grid_images 
    display: Small Image Top Right
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresRight
    validate: required_if:fields.section_type,WorkImage-FiveSquaresRight
  five_small3_right:
    type: assets
    container: grid_images 
    display: Small Image Bottom Left
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresRight
    vvalidate: required_if:fields.section_type,WorkImage-FiveSquaresRight
  five_small4_right:
    type: assets
    container: grid_images 
    display: Small Image Bottom Right
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresRight
    validate: required_if:fields.section_type,WorkImage-FiveSquaresRight
  five_large_left:
    type: assets
    container: grid_images 
    display: Large Image
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresLeft
    validate: required_if:fields.section_type,WorkImage-FiveSquaresLeft
  five_small1_left:
    type: assets
    container: grid_images 
    display: Small Image Top Left
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresLeft
    validate: required_if:fields.section_type,WorkImage-FiveSquaresLeft
  five_small2_left:
    type: assets
    container: grid_images 
    display: Small Image Top Right
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresLeft
    validate: required_if:fields.section_type,WorkImage-FiveSquaresLeft
  five_small3_left:
    type: assets
    container: grid_images 
    display: Small Image Bottom Left
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresLeft
    validate: required_if:fields.section_type,WorkImage-FiveSquaresLeft
  five_small4_left:
    type: assets
    container: grid_images 
    display: Small Image Bottom Right
    width: 60 
    max_files: 1
    instructions: Image should be exactly 1464px X 1464px.  
    show_when:
      section_type: WorkImage-FiveSquaresLeft
    validate: required_if:fields.section_type,WorkImage-FiveSquaresLeft
```
