### ISSUE TITLE
Custom 404 error page not working

### ISSUE THREAD

**Issue by jimblue** [statamic/v2-hub#2180]
**Describe the bug**
Statamic crash when I switch from default 404 template to a custom one.
I've follow the documentation by creating a **/errors/404.html** template.

**The error summary**
```
FatalThrowableError in LocalesTags.php line 97:
Call to a member function in() on null
```

and

**[A link to the full error message](https://gist.github.com/jimblue/51474925573d069e91dd720ea73a51c9)**

**To Reproduce**
1. Create an **errors** folder in the **templates** folder
2. Create a new **404.html** file in the newly created **errors** folder
3. Browse to an url that should trigger a 404

**Expected behavior**
By **following https://docs.statamic.com/knowledge-base/error-pages** I should be able to see my custom error template.

**Environment details:**
 - Statamic Version 2.10.7
 - Upgrade
 -  macOS 10.14
 - Valet
 - PHP Version 7.2.11
 - Addons installed: Charge, Fetch, Google Analytics, Instagram, Power Tools, Seo pro, Webpacker

**Comment by jimblue** [comment]
Not sure but maybe relate [](https://statamic.com/forum/3050-locales-tag-not-working-on-error-page)

**Comment by edalzell** [comment]
That error is not a 404, which is why your custom page is not being triggered.

**Comment by jasonvarga** [comment]
I can't reproduce this. Can you give any more details? What does your system.yaml look like?

Also, why are you trying to use the {{ 404 }} tag on your 404 template? You're already on a 404.

**Comment by jimblue** [comment]
I confirm the problem come from the `{{ locales }}` tag. When I remove it from my template error, I don't get the error anymore.

Didn't you try to had the above snippet to a custom error template?

BTW, there is my **system.yaml**:

```
locales:
  en:
    name: en
    full: en_US
    url: 'https://statamic.test/'
  fr:
    full: fr_FR
    name: fr
    url: 'https://statamic.test/fr'
timezone: UTC
date_format: 'F jS, Y'
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
app_key: 6mXpUSPsbizeeM0ypnfetGVcn9e692zD
redactor:
  -
    name: Standard
    settings:
      buttons:
        - formatting
        - bold
        - italic
        - link
        - unorderedlist
        - orderedlist
        - html
  -
    name: Basic
    settings:
      buttons:
        - bold
        - italic
csrf_exclude:
  - '/!/Fetch/*'
  - /!/Charge/webhook
yaml_parser: symfony
send_powered_by_header: true
ensure_unique_ids: true
```
