### ISSUE TITLE
Populated Grid field appears Stacked inside replicator

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#2266]
**Describe the bug**
Initially, the Grid field displays as Table mode inside the replicator. But it seems like after content is saved, the Grid fields displays as Stacked.

**To Reproduce**
1. Create fieldset with a Grid field inside replicator
2. Edit entry and enter content in Grid field. 
3. Save entry.
3. See Grid field appear in Stacked mode.

**Expected behavior**
Grid field should appear in Table mode.

**Screenshots**
<img width="850" alt="screenshot 2018-11-28 16 14 02" src="https://user-images.githubusercontent.com/414211/49130556-ac508680-f328-11e8-81e4-8d8df621c78f.png">

**Fieldset**
```
content_blocks:
    display: Content Blocks
    type: replicator
    sets:
      set_pages:
        display: Nav Item
        fields:
          page:
            type: grid
            add_row: Add Page
            mode: table
            fields:
              page:
                display: Page
                type: pages
                max_items: 1   
      set_checklist:
        display: Checklist
        fields:
          checklist:
            type: grid
            display: Checklist
            fields:
              title:
                type: text
                display: Title
              summary:
                type: text
                display: Summary
```

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.2
 - Fresh Install or Upgrade: 
 - OS: macOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2.11
 - Addons installed: none
