### ISSUE TITLE
[FR] Ability to add default settings

### ISSUE THREAD

**Issue by pxwee5** [statamic/v2-hub#2269]
**Is your feature request related to a problem? Please describe.**
There's no way to use one setting for multiple fieldsets. Partial was supposed to solve this issue, but created another issue where you can't change the name of the fieldset. 

**Describe the solution you'd like**
page.yaml
```
fields:
  names:
    type: select
    settings: settings/select.yaml
```

select.yaml
```
fields:
  field_name_that_does_not_matter:
    type: select
    options:
      - Tom
      - Dick
      - Harry
```

Would produce the following code in page.yaml
```
fields:
  names:
    type: select
    options:
      - Tom
      - Dick
      - Harry
```

This way I can share the settings and use it anywhere. 

**Other options**
Another options would be to add a flag in partial field to not inherit field name from the partial and use the one in the current setting instead:
```
fields:
  partial_name:
    type: partial
    fieldset: partials/select
    inherit_fieldname: false
```
