### ISSUE TITLE
[BUG]: Localization Issue deletes Content of other locales

### ISSUE THREAD

**Issue by goldnead** [statamic/v2-hub#2270]
might be related to: https://github.com/statamic/v2-hub/issues/1221

**Describe the bug**
I've got a project that heavily relies on replicator fields. Furthermore each page has to be translated in 5 different languages.
Now, there are certain moments where Statamic deletes the tranlsated content seemingly out of nowhere while the page is saved in the default locale. It's pretty hard to reproduce but it occasionaly occurs which results in a huge data loss!

**To Reproduce**
1. create a `home.yaml` with a full-blown replicator field
here's an example:
```
title: Home
create_title: ''
hide: true
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        display: Title
        localizable: true
      content_sections:
        type: replicator
        display: Sections
        instructions: '...'
        localizable: true
        sets:
          stage:
            display: Stage
            fields:
              hero_title:
                display: Heading
                type: text
                localizable: true
              description:
                type: textarea
                display: Description
              button_label:
                type: text
                width: 50
                display: 'Button Label'
              button_target:
                max_items: 1
                type: pages
                width: 50
                display: 'Button Target'
          usps:
            display: USPs
            fields:
              usps:
                sets:
                  usp:
                    display: 'Single USP-Element'
                    fields:
                      title:
                        type: text
                        display: Title
                      category_title:
                        type: text
                        display: Category
                        width: 75
                      description:
                        type: textarea
                        display: Description
                      has_badges:
                        type: toggle
                        display: 'Show Logos (below description)'
                        width: 25
                      image:
                        container: main
                        folder: /
                        restrict: false
                        max_files: 1
                        type: assets
                        display: Illustration
                type: replicator
                display: USPs
          payment_howto:
            display: HowTo
            fields:
              how_to_title:
                type: text
                display: Heading
              howto_sections:
                type: replicator
                localizable: true
                display: Options
                instructions: ...'
                sets:
                  option_1:
                    display: option_1
                    fields:
                      section_title:
                        type: text
                        display: Section-Title
                      section_text:
                        type: textarea
                        display: Section-Text
                      show_more_link:
                        type: text
                        display: 'Show-More Link Text'
                  option_2:
                    display: option_2
                    fields:
                      section_title:
                        type: text
                        display: Section-Title
                      section_text:
                        type: textarea
                        display: Section-Text
                      show_more_link:
                        type: text
                        display: 'Show-More Link Text'
                  option_3:
                    display: option_3
                    fields:
                      section_title:
                        type: text
                        display: Section-Title
                      section_text:
                        type: textarea
                        display: Section-Text
                      show_more_link:
                        type: text
                        display: 'Show-More Link Text'
                  option_4:
                    display: option_4
                    fields:
                      section_title:
                        type: text
                        display: Section-Title
                      section_text:
                        type: textarea
                        display: Section-Text
                      show_more_link:
                        type: text
                        display: 'Show-More Link Text'
          product:
            display: Product
            instructions: '...'
            fields:
              subline:
                type: text
                display: Subline
              more_btn:
                display: 'Button Label'
                type: text
                width: 50
              button_target:
                max_items: 1
                type: pages
                width: 50
                display: 'Button Target'
taxonomies: true

```
2. fill with content & localize everything in multiple languages (mine are en, de, fr, it & es)
3. in `home.yaml` extend fieldset with a text-field on highest level (`sections > main > fields > ...`)
```
...
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        display: Title
        localizable: true
      test:
        type: text
        display: TEST
        localizable: true
...
```
4. fill sample-field with content in all languages
5. remove field from `home.yaml` and remove field content (in code editor) from `index.md` but leave it in all other locales
6. go to cp and save home while editing in default locale
7. all contents from all other locales get deleted!

**Expected behavior**
The other locales are being untouched, No data get's lost!

**Screenshots**
![bildschirmfoto 2018-11-29 um 09 08 03](https://user-images.githubusercontent.com/1313348/49208020-e6686980-f3b6-11e8-9708-9bb2b79099cc.png)

**Environment details:**
 - Statamic Version 2.11.2
 - Fresh Instal
 - OS: Ubuntu 16.04
 - Browser: latest Chrome
 - Web Server: Nginx on Homestead
 - PHP Version: 7.1
 - Addons installed: none

This is a very serious Issue, since we're about to launch a Client's project next week and this Bug seems to pop up multiple times. Any Ideas why that keeps happening?

Note:
I found another way that isn't that hard to reproduce:
1. Go to home Page in CP and edit the content of the default locale
2. discard changes via git
3. on the same page without reload save without making any changes
4. All Content from other locales gone
