### ISSUE TITLE
[BUG] Control Panel: Static Files Path option fieldtype not working with array

### ISSUE THREAD

**Issue by jimblue** [statamic/v2-hub#2271]
For multiple locales website, the doc suggest to use different paths for static caching like so:

```yaml
static_caching_file_path:
  en: static
  fr: fr/static
```

This cause a problem with the control panel as the `Static  Files Path` field seems to accept string only:

![screenshot 2018-11-30 at 08 56 43](https://user-images.githubusercontent.com/10623367/49276141-debfc800-f47d-11e8-95b0-17f2d67e3d7a.png)
