### ISSUE TITLE
Array field with no keys saves empty keys

### ISSUE THREAD

**Issue by josvar** [statamic/v2-hub#2273]
**Describe the bug**
#1891 is back in the last release.

**To Reproduce**
Add a new Array field  to a fieldset.

**Expected behavior**
Saving a fieldset with an array field without any keys should have no keys value.

Like this:

```
      field_8:
        type: array
        display: 'Field 8'
```
Instead empty keys is generated.
```
      field_8:
        keys: {  }
        type: array
        display: 'Field 8'
```

**Screenshots**
Array field created:
![image](https://user-images.githubusercontent.com/5150244/49308944-82c66500-f4b8-11e8-9b6b-99478274ec6e.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.2
 - Fresh Install
 - Web Server: Valet
 - PHP Version: 7.1 here.
