### ISSUE TITLE
FR: Computed Columns

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#2297]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could have custom fields in the columns of a collection. For example columns where the data is computed antlers code.

**Describe the solution you'd like**
It could look something like this (to show the page hits for entries in a collection:
```
columns:
  - title
  - slug
  - value: "{{ google_analytics:hits }}"
    extra: true
    width: 25
    header: Page Hits
    link: false
```

**Describe alternatives you've considered**
I considered adding the info as data to the entry YAML file, but it does not fit well as data in this case, as the data is dynamic.
