### ISSUE TITLE
show_when toggle is not working for addon custom fieldsets

### ISSUE THREAD

**Issue by abhimanyu003** [statamic/v2-hub#2305]
**Describe the bug**
For addons custom Fieldtype
`show_when` field in `meta.yaml` is not working in addons extra tab

**To Reproduce**

Add this to `meta.yaml`

```
fieldtype_fields:

  include_everything:
    type: toggle

  include:
    type: list
    show_when:
      includeEverything: true
```

**Expected behavior**

`include` list must be be toggled based on `include_everything`
