### ISSUE TITLE
Make it possible to validate arrays and map field names / dynamic

### ISSUE THREAD

**Issue by madsem** [statamic/v2-hub#2308]
Not sure if related to  #345 

But Validation should accept arrays and strings. So we could do something like this for example:

```yaml
ratings:
        type: array
        display: "Ratings"
        instructions: "Rate the below properties from 1 - 10"
        keys:
          taste: Taste
          presentation: Presentation
          quality: Overall Quality
        validate:
          - keys.*: required|numeric|between:1,10

```

Currently, it doesn't seem possible to validate array values.
