### ISSUE TITLE
Changing filesystems to use S3 doesn't work

### ISSUE THREAD

**Issue by gigo6000** [statamic/v2-hub#2314]
**Describe the bug**
I'm trying to change an existing statamic site to use S3 buckets for the `content` and `storage` folders, so I changed the `site/settings/system.yml` file to use S3 but it just doesn't do anything it seems to be failing silently, no error anywhere. According to the docs (https://docs.statamic.com/knowledge-base/filesystems#main) this is possible but there are not much details about it. I had to check the Laravel documentation to find info about using S3 as a filesystem.

**To Reproduce**
1. Create two buckets on S3 one for the `content` folder and another for the `storage` folder. 
2. Upload the content of your `content` and `storage` folders to the corresponding S3 buckets.
2. Delete/Move your local `content` and `storage` folders.
2. Open `site/settings/system.yml` 
3. Change the filesystem config according to your S3 config:
```
filesystems:
  content:
    driver: s3
    key: xxxxx
    secret: xxxxxx
    region: xxxxxx
    bucket: xxxxxx
  storage:
    driver: s3
    key: xxxxx
    secret: xxxxxx
    region: xxxxxx
    bucket: xxxxxx
...
```

3. Go to the browser and refresh the page
4. Nothing happens. Nothing in the apache logs, nothing in the `local/storage/logs/`.

**Expected behavior**
I expect to see the content being loaded from S3, but all I get is the homepage without content.

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.2
 - Fresh Install or Upgrade: Upgrade
 - OS: Ubuntu 16.04.5
 - Browser: Chrome
 - Web Server: Apache
 - PHP Version: 7.0.32
