### ISSUE TITLE
Bug(s) wrt Roles/Groups and user records?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#2327]
In v2.11.4 (and earlier) seems there's something... odd... going on with regard to users and roles. It's possible I'm just confused, so let me document in detail (sorry for the length) what I've got and what's going on, and you can let me know if this is a bug, or what.

For context, here is my `site/settings/users/roles.yaml`:
```
super:
  title: Super
  slug: super
  permissions:
    - super
admin:
  title: Admin
  slug: admin
  permissions:
    - super
executive_committee_member:
  title: Executive Committee Member
  slug: executive-committee-member
  permissions: [ ]
officer:
  title: Officer
  slug: officer
  permissions: [ ]
supercow:
  title: SuperCoW
  slug: supercow
  permissions:
    - users:view
    - users:edit
cow:
  title: CoW
  slug: cow
  permissions: [ ]
member:
  title: Member
  slug: member
  permissions:
    - cp:access
```
(FYI: CoW stands for "Coordinator of the Week", and SuperCoW is the permanent overseer and backup for whomever gets the CoW role for each week.)

Moving on, here is `site/settings/users/groups.yaml`:
```
admins:
  title: Admins
  slug: admins
  roles:
    - admin
  users:
    - b3d207f4-8315-4e31-8083-93890dde33ea
    - 4b211ba5-9791-436d-957b-84399e962e19
    - fab19293-54e0-4fb1-ba92-6c705429ca78
executive_committee_members:
  title: 'Executive Committee Members'
  slug: executive_committee_members
  roles:
    - executive_committee_member
  users:
    - 7da174dc-63f6-4af4-8e4c-9ec760f490b7
    - 3ea55999-5320-485d-8965-ae61182ac5c8
    - b28b93c0-d54b-4b1c-bca2-f794607e5da5
    - cbe38bfc-f7bb-4e0f-9525-4d65dfb57209
    - cd5e7243-a3c5-466a-aa14-628d22c04114
    - fab19293-54e0-4fb1-ba92-6c705429ca78
    - 47355ec1-9cca-495f-ad32-bf1c64b15d96
    - 8f1b30bb-dba9-4104-8bf6-462430a089e7
    - f19624e6-55e7-4a38-aee3-d58e5116ba0d
    - 85644b79-cf63-4e21-9551-a655d38e5e8a
officers:
  title: Officers
  slug: officers
  roles:
    - officer
  users:
    - cbe38bfc-f7bb-4e0f-9525-4d65dfb57209
    - fab19293-54e0-4fb1-ba92-6c705429ca78
    - b28b93c0-d54b-4b1c-bca2-f794607e5da5
    - 47355ec1-9cca-495f-ad32-bf1c64b15d96
    - 8f1b30bb-dba9-4104-8bf6-462430a089e7
    - f19624e6-55e7-4a38-aee3-d58e5116ba0d
    - 85644b79-cf63-4e21-9551-a655d38e5e8a
supercows:
  title: SuperCoWs
  slug: supercows
  roles:
    - supercow
  users:
    - fab19293-54e0-4fb1-ba92-6c705429ca78
cows:
  title: CoWs
  slug: cows
  roles:
    - cow
  users:
    - 7e169d62-b212-425d-8b08-c60b4cb82d0f
    - e717351f-ec20-42b1-b0e7-b1e151ea010e
members:
  title: Members
  slug: members
  roles:
    - member
  users:
    - 7da174dc-63f6-4af4-8e4c-9ec760f490b7
    - 8642b4d7-f094-4667-b240-cd2053637b94
    - e599337a-0f37-4d07-820a-3eff95236381
    - 3ea55999-5320-485d-8965-ae61182ac5c8
    - 9f221003-b1c6-45c9-8b8f-39df835612ea
    - 451bfb64-27c0-4120-b9df-b6ba777765b3
    - c8122a6e-a95c-4abd-9a9c-b4d52bfb49b3
    - a20ab24e-cb86-4fc5-9154-495fad947f9d
    - cbe38bfc-f7bb-4e0f-9525-4d65dfb57209
    - cd5e7243-a3c5-466a-aa14-628d22c04114
    - 8013d1a2-eb65-438a-95a1-c1e1eee92bfb
    - 9a1ef6bc-5ed9-4217-97aa-eaaf13dcd9a7
    - 3cf49871-c8ba-4f69-be63-41aafa571e9d
    - b53f6c16-4456-4e84-aac6-0cd093435f91
    - fab19293-54e0-4fb1-ba92-6c705429ca78
    - ff671d6b-012a-4666-8f43-1dcd6dee601f
    - 5d5bf460-7c97-457b-949c-ebbc7ce49b89
    - d8d93401-8ba0-4ecc-9bd4-4f98f1eca500
    - b28b93c0-d54b-4b1c-bca2-f794607e5da5
    - 84ae511d-d3cc-4cde-a542-5b6368baa72d
    - 6bcee43c-b7dc-4f3f-80bf-84c63b225bad
    - cb3e7ddd-fe3c-40cd-b3cf-c747cbf27f21
    - 47355ec1-9cca-495f-ad32-bf1c64b15d96
    - 7e169d62-b212-425d-8b08-c60b4cb82d0f
    - 0003ff9e-ef2a-49fb-865d-3b786dd653b3
    - 13105e80-f0ec-458f-aa0b-0d38c8c55f98
    - b9370879-54d5-43f6-b890-027d007f8abf
    - 8f1b30bb-dba9-4104-8bf6-462430a089e7
    - f19624e6-55e7-4a38-aee3-d58e5116ba0d
    - 67549d3c-0ce6-46e4-be66-213ada9990f3
    - e1ef31d6-f4a7-4e2a-b591-ab0c66ab8066
    - 79352475-a673-4463-85a9-1146bc40f467
    - 85644b79-cf63-4e21-9551-a655d38e5e8a
    - e717351f-ec20-42b1-b0e7-b1e151ea010e
    - a099daf4-8c37-4fb8-aaa7-5ae7d4b876d9
```

So far, so good. The above all works fine, and I can use the CP to give and take away roles as the situation warrants. For example, I can use the CP to change out whoever's the CoW (Coordinator of the Week) as that duty changes from week to week. I can make someone an admin, etc., and conditionals out yonder in the partials and templates code like this:
```
{{ user:is role="super|admin" }}
...
{{ /user:is }}
```
all work just fine.

So where's the beef?

What's bugging me is that odd thigns are going on in the user records. You know, the files in `/site/users`.

A little back-story... I previously I did `php please convert:email-login` on the command line. So, as expected, all user records are now named by their email address. For instance, I created a few test cases, such as: `/site/users/Ima.Testcase@example.org.yaml`

And, as a byproduct of doing that `php please convert:email-login` I got this as my `/site/settings/users.yaml`:
```
driver: file
redis_write_file: true
login_type: email
new_user_roles: {  }
enable_gravatar: true
```
which I changed to first
```
login_type: email
new_user_roles:
  - member
enable_gravatar: true
driver: file
redis_write_file: true
```
and then
```
login_type: email
new_user_roles: { member } #(and even `new_user_roles: {member}`)
enable_gravatar: true
driver: file
redis_write_file: true
```
but nothing I could do seemed to automatically give a newly created user a role of "member".

For instance, I'd go to `/cp/users/groups/members` and find Ima is not in the "Selected" list over in the CP pane on the right.

Well, OK. So I click on her email ID over on the left, and she gets added to the "Selected" list over on the right.  Roger that.

But, I observe no change over in her user record, although, yes, she's now in `/site/settings/users/groups.yaml`:
```
members:
  title: Members
  slug: members
  roles:
    - member
  users:
    - 7da174dc-63f6-4af4-8e4c-9ec760f490b7
    - 8642b4d7-f094-4667-b240-cd2053637b94
    - e599337a-0f37-4d07-820a-3eff95236381
        ...

    - e717351f-ec20-42b1-b0e7-b1e151ea010e
        ...
```
(That `e717351f-ec20-42b1-b0e7-b1e151ea010e` near the bottom is her, which I had to suss out by coping the ID from her user record and searching for it here.)

(Sidebar: is it true we can't have this list human-readable as email IDs? Just asking.)

UM. OK. So now I go to her use record in the CP at `/cp/users/Ima.Testcase@example.org`, and I *don't do anything* except click the `SAVE` button, top right.

What happened?  This: In her user record there's now something new:
```
roles:
  member: member
```
[NB. Need to double check: If it's `new_user_roles: {member}`,`or new_user_roles: { member }`, then clicking SAVE does NOT insert roles info into the user record? So many things to check out, so little time...]

Moving on...

First, I can delete that info from her user record, and there's no ill effect that I can see. Ima is still a member over in that groups list. And I can paste it back into he user record, and likewise there's no ill effect that I can see. It seems unrelated to anything to do with actually being in a group and having a role as member.

Second, what's kinda weird is that it says
```
  member: member
``` rather than
```
  - member
```
as I would have expected, since it was set up differently as:
```
new_user_roles:
  - member
```
back there in `/site/settings/users.yaml`. (Although I suspect that's just dead code, and has no effect on the scenario here.)

Which I'll now again mention seemed to do nothing in terms of getting her into the "Members" group automatically as I'd hoped.

So in all this, if feels like I'm missing something.

*Should* roles info be in the user record?

If so, why doesn't enrolling someone in the group via the CP put that info in their record?

And, why does simply *saving* a member record via the CP then stuff the (unusually formatted) roles info into their record, as it doesn't seem to be used or necessary?

I support this assertion by the fact that after I stripped all such roles info out of all user records, cleared cache (`php please clear:cache`) the conditionals I'd set up in partials and templates, etc., like,
```
{{ user:is role="super|admin" }}
...
{{ /user:is }}
```
etc. all work just fine without any roles info whatsoever in the user records.

BUT, when you save a user record, it--the system--somehow knows what the appropriate roles are, and assigns them into the user record "correctly" (at least in terms of which roles go to who). For instance saving a real users record where I'd previously stripped out all roles info, it inserts:
```
roles:
  admin: admin
  executive_committee_member: executive_committee_member
  officer: officer
  member: member
```
again, with the weird `rolename: rolename` syntax that I don't understand where it's coming from.

Just in case it was going from *me*, I messed around with `/site/settings/fieldsets/user.yaml. Originally that had this in it:
```
...
  roles:
    type: checkboxes
    display: Roles
    instructions: Enabling roles gives users different abilities.
    options:
      admin: Admin
      officer: Officer (Currently holds any chapter office or title; e.g., Chair, Treasurer, etc.)
      executive_committee_member: Executive Committee member
      supercow: Super-CoW
      cow: CoW
      member: Member
...
```
but I took that out and substituted
```
  roles:
    display: Roles
    instructions: "__UPDATE:__ There's now a difference between *defining* a role, and saying a member *has* that role.<br /><br />E.g., To change who has the role of CoW (singular), use the sidebar or this link to go to [__Users/User GROUPS__](/cmscp/users/groups)<br />and add or delete a members from the CoWs (plural) group. (Even if there's only one, it's a group—get it?)<br /><br />VS. To define/edit roles and what they allow, you'd go to Users/User Roles. (Probably NOT what you want to do!)"
```
and then I even removed it altogether.

In all cases the above behaviors persisted. That is, having the fieldset info either defined or undefined had no effect. The system behaved as described, and used the CP specified roles and groups info (as it should!), rather than stuff like
```
roles:
  cow: cow
  member: member
  admin: admin
```
which is what's in Ima's test user record at the moment.

So what's the point? My conclusions so far are:

1) The system is *forcing* roles info into user records when and only when you explicitly save a user record in the CP. So far as I know, you can't stop it from doing that.

2) The format of that info is in (to me) the mysterious double-speak format, such as
```
roles:
  member: member
```
rather than the (to me) preferred list-y format
```
roles:
  - member
```

3) It seems that other than forcing it in there, the roles info in user records is NOT USED by the system at all (it uses the CP specified roles and groups info).

4) Unfortunately, the roles info in user records can easily become stale, misleading, or wrong at any particular point in time, since it's only update upon a CP save of the user's info. (Do we care? That roles info is not being used. But, IMHO, the system shouldn't be doing this.)

5) The `new_user_roles: {  }` feature of `/site/settings/users.yaml` doesn't seem to work. At least, *I* couldn't get it to work.

Again, all this in a system where I stripped out all the roles info from all user records, carefully defined the roles in the CP (`/cp/users/roles`), then entered users into groups according to their intended roles (at `cp/users/groups`), and it's all working fine, except for the above odd behaviors.

Hope this is useful info.

Please advise?

**Comment by jackmcdade** [comment]
Can you provide a TL;DR? This is so long I can't get all the info into my head at once.

**Comment by iDGS** [comment]
Sorry to take so long to reply... Hope this helps...

The main points being made here are: 

1. If you edit any user's record via the CP when they are a member of any group, the current state of that member's group's roles info is inserted into their user record. This is a bug.
2. You cannot get rid of this roles info in the user record without manually editing the file. It's otherwise "invisible", since groups and roles membership are managed elsewhere, in `/site/settings/users/groups.yaml` and `/site/settings/users/roles.yaml`.

(a few other points are listed way down below)

Note you can easily recreate this problem and demo it in the default install like so:
1. Install Statamic 2.11.9 download, run install.php, etc.
2. Go to `cp/users/roles` tap "Create Role" 
3. Enter Title: `King`, Slug: `king`, tap "Save"
   3a. Optional: Use a text editor to open `site/settings/users/roles.yaml` and replace the code on line 5 (e.g., 80705b6a-b6e8-4b37-84a6-2ea89d316980:) with `king:` (Not necessary, but more readable)
4. Go to `cp/users/groups`, tap "Create Group"
5. Enter Title: `Kings`, Slug: `kings`, Select: Roles, `King`, tap "Save"
6. Go to `cp/users` tap "Create User"
7. Enter Username: `Huey`, First Name: `Huey`, tap "Save"
8. Again tap "Create User"; Enter Username: `Dewey`, First Name: `Dewey`, tap "Save"
9. Again tap "Create User"; Enter Username: `Louie`, First Name: `Louie`, tap "Save" (Yes, Donald Duck's 3 nephews)
10. Use a text editor to open `/site/content/pages/index.md`
11. To the end of line 8, (`Our latest blog posts:`), append: ` <b>{{ users }}{{ if is_king }}{{ first_name }} {{ /if }}{{ /users }}is King!</b>` and save the file.
12. View home page to verify subhead says: "Our latest blog posts: is King!" (i.e., nobody is yet a king)
13. Use a text editor to open `/site/settings/users/groups.yaml`
14. Replace line 1 (which says something like `b6565e4e-0a89-4335-b20b-f0409707496c:`) with `kings:` (Not necessary, but more readable) and save the file.
15. In Terminal, go to site root and run `php please clear:cache`
16. Go to `cp/users/groups/kings` (See? Way easier to type/read "kings" than b6565e4e-0a89-4335-b20b-f0409707496c, wouldn't you agree?)
17. Under the Users area, tap `Huey` and when he appears on the Selected area, tap "Save"
18. Reload home page, and verify "Huey is King!"
19. Go to `/cp/users/Huey` and under Biography, enter "King forever!" and tap "Save" (any edit to current king record will do the trick)
20. Return to `/cp/users/groups/kings`, Remove Huey from Selected by taping the (x) to left of his name, then under Users tap Louie, so only Louie's name appears under the Selected heading, then tap "Save"
21. Reload the home page and verify it now says "Huey Louie is King!" (Hey—Huey shouldn't be in there!)
22. Use a text editor to open `/site/users/Louie.yaml` to verify it only contains two lines: `first_name: Louie` and an id.
22. Use a text editor to open `/site/users/Huey.yaml`
NB. if you opted for readability back in step 3a, you'll see something like:
```
---
roles:
  - king
first_name: Huey
id: f4885b9a-88e5-4179-9474-2b8875224b92
---
King forever!
```
otherwise it's more like:
```
---
roles:
  - db265760-7f48-40aa-81c3-1c6fe64fa96a
first_name: Huey
id: f4885b9a-88e5-4179-9474-2b8875224b92
---
King forever!
```
(the value of Huey's id may vary--that's not important; it's the fact there's *roles* info in the user record that's weird!)

23. If necessary, open `/site/settings/users/roles.yaml` to verify that that is indeed the role code for "King".

To continue the "points being made here" started way up top...

3. I've also seen a variation of this roles "pollution" of the member record that lists the roles info "stuttered" like so:
```
---
roles:
  king: king
```
with the role name repeated, seperated by a colon. However, I haven't tracked down how to recreate that.

4. Sequence is important. E.g., if you create a role of "Nephew" then a Group "Nephews" and enroll all three ducks and hit "Save", nothing happens until you edit one of the duck's records in the CP. Say you add "I'm a duck!" to Dewey's bio. You'll get
```
---
roles:
  - nephew
first_name: Dewey
id: bc135ef0-07db-47e9-a710-a71002bfd96f
---
I'm a duck!
```
Make Dewey a king and the subhead on the Home page becomes:  "Dewey Huey is King!" but the role of king doesn't appear in Dewey's record because he wasn't a king when you edited him.
5. Yes, changing the homepage code from role focus (`is_king`) to group focus (`in_kings`) like so, from
```
<b>{{ users }}{{ if is_king }}{{ first_name }} {{ /if }}{{ /users }}is King!</b>
```
to
```
<b>{{ users }}{{ if in_kings }}{{ first_name }} {{ /if }}{{ /users }}is King!</b>
```
makes the problem "go away" on the home page, but the pollution of role data is still in the user record(s). The "so what?" issue here being that such user record changes do show up when you do a `git status` on your site, because they are real but spurious changes to the site's content.

6. I have not experimented to see if edits to user data via front end add-ons have the same effect, so that's an open issue.

**Comment by iDGS** [comment]
Further to point 3., above: on my test system, I just made a member a "cow" (Coordinator of the Week), then edited a random field on his user record. As expected, his at-the-moment roles info got inserted into his user record as soon as I taped "Save". Not a surprise anymore, but I mention it because it's giving me the double-role variant I spoke of, like so:
```
roles:
  executive_committee_member: executive_committee_member
  officer: officer
  cow: cow
  member: member
  chair: chair
```
I'm not inclined at the mo' to chase after why, as I'm hoping y'all gents can fix the issue, so it just goes away. (Fingers crossed!)
