### ISSUE TITLE
Replicator and Bard ignoring replicator_preview: false in grids

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#2362]
**Describe the bug**
Collapsed replicator fieldsets show a preview and even enumerate grid items – that's awesome!
You even can select fields that shouldn't show in the preview by means of `replicator_preview: false`.

Unfortunately that doesn't work for fields in the next level, even though they are enumerated.

**To Reproduce**

Fieldset:
```
fields:
  testfield:
    type: bard
    sets:
      gallery_set:
        fields:
          gallery:
            type: grid
            min_rows: 1
            fields:
              image:
                type: assets
                …

              caption:
                type: text
                replicator_preview: false
                …
```

1. Add a field like the above to any page or collection fieldset
2. In CP add a gallery to any page or collection
3. Add some images and captions
4. Collaps the block

**Expected behavior**
The caption shouldn't show in the preview

**Environment details (please complete the following information):**
 - Statamic Version 2.11.9
 - Fresh Install or Upgrade: Upgrade
 - OS: Fedora 29
 - Browser: Firefox for Developers
 - Web Server: Apache 
 - PHP Version: 7.3
 - Addons installed: None
