### ISSUE TITLE
Content in yaml file of second locale is cleared when saving in CP

### ISSUE THREAD

**Issue by PeterEmil** [statamic/v2-hub#2374]
**Describe the bug**
On multi-locale site, when after writing and saving in the second language in CP the yaml file is cleared. This happens when changing the title, slug, or changes made to Bard fieldset, etc. This behaviour wasn't noticed before; my client wrote the second language some months ago. Then saving in the CP worked correct.

**To Reproduce**
1. Click on locale switcher and switch to second language
2. Change title, or slug, or some Bard content
3. Save
4. Refresh: the Bard content is in the first language, the rest is correct
5. Checking yaml file shows empty bard field

**Expected behavior**
This behaviour wasn't noticed before; my client wrote the second language some months ago. Then saving in the CP worked correct. So perhaps this issue is introduced in an update but we haven't notice it before.

**Screenshots**
![1 switch from to second first language](https://user-images.githubusercontent.com/2565012/55511443-ec21d480-5660-11e9-91cf-e5870a3cf1f1.png)
![2 change in second language](https://user-images.githubusercontent.com/2565012/55511444-ecba6b00-5660-11e9-9293-900a23257165.png)
![3 save](https://user-images.githubusercontent.com/2565012/55511446-ecba6b00-5660-11e9-8e6e-7169e6802512.png)
![4 result after refresh](https://user-images.githubusercontent.com/2565012/55511448-ee842e80-5660-11e9-9154-e57a6e520069.png)
![5 result in Code](https://user-images.githubusercontent.com/2565012/55511451-ef1cc500-5660-11e9-9b33-6877520031b7.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.9
 - Fresh Install or Upgrade: 
 - OS: macOS 10.13.6
 - Browser: all
 - Web Server: Valet
 - PHP Version: 7.1.25
 - Addons installed: Spock

**Additional context**
Last weeks I tried to get Spock working so perhaps this has something to do with it.
Sometimes, but not always, when switching from the first to the second language - even when there is no change made - there is an alert "stay on this page / leave this page".

**Comment by andypillip** [comment]
I have the same issue with Bard *and* Replicator. In version 2.8.2 it's still working.

* Statamic Version 2.11.10
* OS: Linux
* Web Server: PHP server and Apache
* PHP Version: 7.3
* Addons installed: parseURL

**Comment by wautersj** [comment]
I experience a somewhat similar behaviour. When I update the slug in a translation, the routes yaml cleares other defined locale slug defenitions, so the pages at those slugs break ...

**Comment by andypillip** [comment]
I just upgraded to 2.11.14, but the issue is still present. I cannot edit pages in my second locale without loosing them completely.

**Comment by wautersj** [comment]
Looks like the same issues as with https://github.com/statamic/v2-hub/issues/2435

**Comment by jasonvarga** [comment]
Can someone please post their fieldset and system.yaml files? I can't replicate this all.

**Comment by PeterEmil** [comment]
Hi there! After half a year working on different stuff I'm back. Issue still persist in version 2.11.17.

Whenever in CP the edits are saved using the "save" button the en.index.md is wiped clean. Editing the file directly is not a solution for my client I'm afraid.

This is the system.yaml:
```
locales:
  nl:
    full: nl_NL
    name: Nederlands
    url: /
  en:
    full: en_US
    name: English
    url: /en/
timezone: Europe/Amsterdam
date_format: j F Y
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
app_key: TcrM1siEZS3Ux3138yMY8weOfA798Xyo
redactor:
  - 
    name: Standard
    settings:
      buttons:
        - formatting
        - bold
        - italic
        - link
        - unorderedlist
        - orderedlist
        - html
  - 
    name: Basic
    settings:
      buttons:
        - bold
        - italic
send_powered_by_header: true
ensure_unique_ids: false
```

**Comment by PeterEmil** [comment]
I installed a fresh new statamic install, cleared the default site, created blank theme using `php please` and created a multi locale version using the steps in https://docs.statamic.com/localization.
The two locales are `nl` and `en`, with the former as default.

In this instance there is no issue whatsoever. I'm checking both the new install as the existing one side by side. I'm pretty sure it has something to do with the Bard field type. While in the new install the default Bard field type is saving in the CP results in a correct changed .md file, with the existing one there is no change seen in the .md file when saving in the CP.

The Bard field type in the existing install has some partials in it which are shown depending on the page or collection the user is in.

I'll update this issue with my progress so it can be of use for people having a similar issue.

 - Statamic Version 2.11.17
 - Fresh Install or Upgrade: Fresh Install
 - OS: macOS 10.15.2
 - Browser: Chrome / Safari / FireFox
 - Web Server: Valet
 - PHP Version: 7.1.25
 - Addons installed: none

**Comment by PeterEmil** [comment]
After recreating the structure using a fresh new install and some deduction I found the culprit, so I will document it here in case someone wanders around with the same localisation issue.

The fieldset regarding this issue had a reference to a partial fieldset. The name of the partial in the parent fieldset had the same name as the filename of the partial fieldset. See the code below. I removed some data from the fieldsets to pinpoint the issue better.

parent fieldset:
```
title: Default
  main:
    fields:
      title:
        type: text
        localizable: true
      content_bard:
        type: partial
        fieldset: partials/bard-sets
(...)
```
partial fieldset:
```
title: Bard Sets
fields:
  content_bard:
    type: bard
    display: The content in Fancy Mode
    localizable: true
    container: main
    spellcheck: true
    allow_source: true
(...)
```
See the duplicated `content_bard` naming? This was causing the issue, but only in the localised .md files. After renaming this to some other name in the parent fieldset, saving in the second locale using the CP was propagated to the en.md file like a charm.

And hereby I declare this issue closed :)
