### ISSUE TITLE
Static cache invalidation for localized content

### ISSUE THREAD

**Issue by xahs** [statamic/v2-hub#2414]
**Describe the bug**
When full measure caching is configured (according to the documentation). It seems like invalidation rules won't be applied correctly. As I understood, when updating content from the cp, the FileCacher is always getting the default language when building the invalidation path.

**A fix that works for me**
I was able to fix the problem by editing ```Statamic\StaticCaching\FileCacher::getCachePath```:

```php
public function getCachePath($locale = null)
{
    $paths = $this->getCachePaths();

    if (! $locale) {
        // Before
        $locale = $this->config('locale');

        // After
        $locale = request('locale', $this->config('locale'));
    }

    return $paths[$locale];
}
```

**To Reproduce**

1. Configure caching as below:
```yaml
stache_always_update: true
cache_tags_enabled: true
static_caching_enabled: true
static_caching_type: file
static_caching_file_path:
  fr: static
  de: de/static
  it: it/static
static_caching_invalidation:
  collections:
    news:
      urls:
        - /
        - /de/ # the final slash is required for my fix to work
        - /it/
```

2. The root folder should have this structure
```
- /
  - statamic
  - site
  - ...
  - /de
    - static
  - /it
    - static
```

3. Create a collection named "news" with an entry
4. Load the homepage in multiple locales to create static files for each
5. Edit the entry you created in each language

**Expected behavior**
Static files in each locale path should be deleted
