### ISSUE TITLE
thumbs not working in bard

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2418]
**Describe the bug**
I dont see images in my bard field in the cp "see screenshot 1"
The images do work on the site

**To Reproduce**
1. I made a new assets using the follwing values "see screenshot 2",
2. I made a fieldset with a bard field wich has an assets field "see code block 1"
3. I build a collection with the fieldset bard from step 1

**Expected behavior**
show the thumbs in the cp

**Screenshots**
![image](https://user-images.githubusercontent.com/20043831/60426771-9cb65a80-9bf5-11e9-80cd-bed229cee301.png)
screenshot 1

![image](https://user-images.githubusercontent.com/20043831/60426276-9ffd1680-9bf4-11e9-9cab-bf4f902a3232.png)
screenshot 2

**Environment details (please complete the following information):**
 - Statamic Version [2.11.13]
 - Fresh Install or Upgrade: [Fresh install]
 - OS: [Windows 10]
 - Browser: [chrome]
 - Web Server: [Apache]
 - PHP Version: [latest]
 - Addons installed: [none]

**Additional context**
```
bard:
  buttons:
    - h2
    - h3
    - h4
    - h5
    - h6
    - bold
    - italic
    - underline
    - strikethrough
    - unorderedlist
    - orderedlist
    - removeformat
    - quote
    - anchor
    style: sans
    spellcheck: true
    allow_source: true
    allow_internal_links: true
    link_noopener: false
    link_noreferrer: false
    target_blank: false
    semantic_elements: false
    restrict_assets: false
    sets:
      grid:
      display: grid
      fields:
        galerij_image:
          container: grid_images
          folder: img
          restrict: false
          type: assets
          display: 'galerij image'
  type: bard
  display: Bard
```
code block 1
