### ISSUE TITLE
Redactor is not working yet?

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#25]
I wasn't able to save anything when field type is set to Redactor. It also ignored my additional redactor settings.

```
    type: redactor
    display: The content
    settings:
      minHeight: 500
      buttons:
        - underline
        - bold
```
