### ISSUE TITLE
Allow routes to have regex

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#280]
From Slack:

```
routes:
  /blog/{year}/{month}:
    template: archive
    year: ^\d{4}$
```

So that one could have an archive listing at `/blog/2015/09/` AND have a taxonomy listing at `/blog/tag/sales`.

Right now the specific route takes preference so the taxonomy context is not loaded.
