### ISSUE TITLE
No thumbnail on image 

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#289]
I have an asset in a replicator:

```
title: Page
fields:
  title:
    type: text
    display: Title
  content_block:
    sets:
      text:
        display: Text
        instructions:
        fields:
          text:
            type: markdown
            display: Text
            instructions: null
      image:
        display: Image
        instructions:
        fields:
          image:
            max_files:
            folder: /
            container: 9d15cd2b-ab98-4a7f-b55f-8f812f114da4
            type: assets
            display: Image
            instructions: null
    type: replicator
    display: Content
```

When I add an Image and drag an image file onto it, there is no thumbnail:
![edit the-dls statamic 2015-12-31 10-41-31](https://cloud.githubusercontent.com/assets/6069653/12067280/235e91ea-afac-11e5-871a-725d3a2618bc.png)
