### ISSUE TITLE
Using mobile_ as prefix for assets field name breaks the field

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#310]
Ok, here's a super weird one. I have the following field:

```
  mobile_screenshot:
    display: Mobile Screenshot
    type: assets
    width: 50
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: img
```

The container is the default demo site one. Even in a fieldset with just this field, the asset upload buttons won't appear; it will just hang with "Loading..." due to internal site error 500. However, if I rename this field _anything other than mobile_xyz_, it works :) Is mobile_ getting parsed somehow?
