### ISSUE TITLE
Dashboard error when using collections

### ISSUE THREAD

**Issue by andregoldstein** [statamic/v2-hub#362]
I'm getting the following error when loading the dashboard `FatalErrorException in DashboardController.php line 0:
Method Illuminate\View\View::__toString() must not throw an exception`

``` YAML
widgets:
  -
    type: collection
    display: Recent blog articles
    collection: articles
    limit: 5
    width: 50
  -
    type: collection
    display: Latest services
    collection: services
    limit: 5
    width: 50
```
