### ISSUE TITLE
Default modifiers for fields

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#383]
Small feature request, so feel free to mark it as such, but I wondered if being able to set default modifiers for a given field would be handy. 

For example, say I have the following field:

```
  description:
    instructions: A short description of ~70 chars.
    display: Description
    type: text
```

Wherever I use this field in my site, I want to use markdown and smartypants, and strip the p tags markdown adds, so I might do something like this:

```
{{ description | markdown | strip_tags:p | smartypants }}
```

Now I could make a macro for this, but formatting is still attached to variable instances. I wonder if it'd be easier to just set it up initially in the fieldset, with something like:

```
  description:
    instructions: A short description of ~70 chars.
    display: Description
    type: text
    formatting: markdown | strip_tags:p | smartypants
```

That would centralise the formatting for the field without having to hunt through templates to find instances of the variable when you want to change something, and would locate field settings in a central place. Another example may be widont for title fields. 

Perhaps a `raw` modifier could be made available to remove the default formatting too if necessary, e.g. `{{ description | raw }}`.

Just a thought :)
