### ISSUE TITLE
Fieldset not loading

### ISSUE THREAD

**Issue by 0xgdr** [statamic/v2-hub#40]
I have the following fieldset:

```
hide: true
include: meta                  # include the meta fields

fields:
  title:
    instructions: "Enter the main page title here."

  content:
    type: hidden

  info_section:
    type: section
    display: No Content
    instructions:
      below: "This page is used to list other page content and doesn't have editable content of its own."
```

The following content YAML

```
fieldset: no_content
title: Blog
meta_title: SEO Title Used By Google
meta_desc: "This is the page description which displays in google's search results, it is important for SEO."
alt_title: Blog Articles
uuid: 6ddf3c82-5ce3-4648-933b-d988efbded9d
```

When I try and edit a page that uses this fieldset I get the following with no JS errors that are related (there are some font load errors but I don't think they are related).

<img width="992" alt="screen shot 2015-11-01 at 14 06 35" src="https://cloud.githubusercontent.com/assets/246458/10869279/21efe0fe-80a2-11e5-9f37-9e736b9a838a.png">
