### ISSUE TITLE
Redactor settings is not showing in the fieldset edit

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#421]
Also returning JS error when clicked.

Here's the settings in the yaml file

```
  content:
    type: redactor
    display: Content
    container: 
    settings:
      plugins:
        - uploadcare
      uploadcare:
        publicKey: 
        tabs: 'file url evernote facebook dropbox gdrive instagram flickr skydrive box'
        multiple: true
```

![screen shot 2016-02-10 at 2 47 17 pm](https://cloud.githubusercontent.com/assets/1151181/12957917/6b155e28-d005-11e5-8a13-d60c9c4a1565.png)
