### ISSUE TITLE
Custom fieldtype width is not 100% even when set

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#430]
![editing event yaml statamic 2016-02-11 09-39-09](https://cloud.githubusercontent.com/assets/6069653/12984639/7b3f7132-d0a3-11e5-8a73-3cf2712b10d7.png)

But in the `event.yaml` fieldset:

```
  field_7:
    type: location
    display: Field 7
    required: false
```

No width field.

Then I manually added `width: 100` but there was no change.
