### ISSUE TITLE
User registrations aren't storing custom fields

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-hub#440]
`/site/settings/fieldsets/user.yaml`

```yaml
title: User Fields
hide: true
fields:
  section_identity:
    type: section
    display: Identity
  first_name:
    type: text
    display: First name
    width: 25
  last_name:
    type: text
    display: Last name
    width: 25
  username:
    type: text
    display: Username
    width: 25
  roles:
    type: user_roles
    width: 25
  birthday:
    type: date
    width: 50

  section_contact:
    type: section
    display: Contact Info
  email:
    type: text
    display: Email address
    width: 50
  phone:
    type: text
    display: Phone number
    width: 50
```

But I don't ask for all that when they register, just...

```html
    {{ user:register_form redirect="/account" }}

      {{ if errors }}
        <div class="alert alert-danger">
          {{ errors }}
            {{ value }}<br>
          {{ /errors }}
        </div>
      {{ /if }}

      <div class="form-group">
        <label>First Name</label>
        <input type="text" name="first_name" value="{{ old:first_name }}" class="form-control" />
      </div>

      <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="last_name" value="{{ old:last_name }}" class="form-control" />
      </div>

      <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" value="{{ old:email }}" class="form-control" />
      </div>

      <div class="form-group">
        <label>Choose a username</label>
        <input type="text" name="username" value="{{ old:username }}" class="form-control" />
      </div>

      <div class="form-group">
        <label>Password</label>
        <input type="password" name="password" class="form-control" />
      </div>

      <div class="form-group">
        <label>Password Confirmation</label>
        <input type="password" name="password_confirmation" class="form-control" />
      </div>

      <button class="btn btn-primary">Register</button>

    {{ /user:register_form }}
```

And I end up with a user file that looks like this:

```yaml
email: someone@fowlertown.com
password_hash: $2y$10$L4j8YXTZ2v.QBfscw.NJOu.3kL9zl.ycnfILEwUEbhZAmPRlG5qre
id: 9d9bcac3-6968-45e7-aed8-e8d9c345ae5b
remember_token: qkYKT6QUEzSyLhIL7IcDSOOR9G23d35T7cnjHY0vCyMEmdz6VCcZYHfvHFZC
```

When I'm learning new stuff (like now), I tend to bang my head on it for a few hours thinking I've screwed it up. But this seems like a bug, since I've barely edited the default files, and since I banged my head for awhile now.
