### ISSUE TITLE
Forms can't use HTML template / docs vague

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#507]
Not sure if this is something I'm just not getting, or an actual bug. If it's the former, any tips would be appreciated :) Maybe the docs could be clarified too. 
### Steps to reproduce
1. Create a form e.g.

```
email:
  - 
    to: 'me@gmail.com'
    from: whatever@email.com
    subject: 'Email subject'
    template: email/my-html-template
```
### Expected behaviour

The template in /themes/mytheme/templates/email/my-html-template.html will be used for the email. 
### Actual behaviour

Get an error:

```
InvalidArgumentException in FileViewFinder.php line 137:
View [email.email.my-html-template-html] not found.
```

**Statamic version:** b19

**Updated from an older Statamic or fresh install:** Updated
