### ISSUE TITLE
unable to edit Asset when first uploading via Asset field

### ISSUE THREAD

**Issue by philbarbato** [statamic/v2-hub#513]
### Steps to reproduce
1. Upload image via an assets field in a replicator set (drag & drop, upload link or "Browse Assets" seem to produce the same results)
2. Hover over the thumbnail and click the little edit icon
3. watch nothing happen
### Expected behaviour

edit modal should appear with metadata fields
### Actual behaviour

nothing happens
### Server configuration

**Operating system**: OS X 10.10.5

**Web server:** Apache

**PHP version:** 5.6.10

**Statamic version:** v2 beta 19

**Updated from an older Statamic or fresh install:** updated from older

**List of installed addons:** none

This particular assets field is inside a set in a replicator field. Not sure if that is an issue. The fieldset below. The specific field is `overflow_image_file`.

```
title: Case Study
fields:
  hero_image:
    type: assets
    display: Hero Image
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: heroes
    max_files: 1
    required: false
  title:
    type: text
    display: Title
    instructions: This is the title used for navigation.
    required: false
  alternate_title:
    type: text
    display: Alternate Title
    instructions: This will appear as the H2 instead of the title.
    width: 75
    required: false
  heading_color:
    type: text
    display: Heading Color
    width: 25
    instructions: 'A hex value without "#". Used for all **Section Headings.**'
    required: false
  content:
    type: markdown
    display: Introduction
    required: false
    cheatsheet: false
    instructions: 'This will be directly below the H2, above all **Content Sections.**'
  content_sections:
    type: replicator
    display: Content Sections
    sets:
      content_section:
        display: Content Section
        instructions: 'This is the default **Content Section.**'
        fields:
          section_title:
            type: text
            display: Section Heading
            instructions: 'This will appear as an H2 in the color set under **Heading Color.**'
            required: false
          section_content:
            type: redactor
            img_dir: /assets/img
            display: Content
            instructions: null
            required: false
          overflow_image_file:
            type: assets
            display: Overflow Image
            container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
            folder: case-study
            max_files: 1
            width: 50
            required: false
          alignment:
            type: select
            display: Overflow Image Alignment
            instructions: Defaults to right if not selected
            options:
              left: Left
              right: Right
            width: 50
            required: false
      reverse_content_section:
        display: Reverse Content Section
        instructions: 'This is the alternate **Content Section.** All text will be white.'
        fields:
          background_color:
            type: text
            display: Background Color
            instructions: 'A hex value without "#".'
            width: 50
            required: false
          background_image:
            type: assets
            display: Background Image
            container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
            folder: case-study
            max_files: 1
            width: 50
            required: false
          section_title:
            type: text
            display: Section Title
            instructions: This will appear as an H2 in white.
            required: false
          section_content:
            type: redactor
            img_dir: /assets/img
            display: Content
            instructions: null
            required: false
          section_list:
            type: list
            display: List
            instructions: A list of things. Will be laid out in two columns on desktop.
            required: false
          float_image:
            type: grid
            display: Float Image
            instructions: null
            fields:
              float_image_file:
                type: assets
                display: Float Image File
                instructions: null
                container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
                folder: case-study
                max_files: null
                width: 50
              float_image_side:
                type: select
                display: Float Image Side
                instructions: null
                options:
                  left: Left
                  right: Right
            mode: stacked
            max_rows: 1
            min_rows:
    required: false

```
