### ISSUE TITLE
B19: Previous entry's data gets passed to next entry if fields are left blank

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#514]
### Steps to reproduce
1. Create a collection with multiple fieldtypes.
2. Create a few entries for collection.
3. Fill some entries in completely, leave some with blank fields (which means they won't appear in the entry's .yaml file) -- this is the key problem.
4. Loop over collection in template using the specific field names (so don't use the `json` modifier).
### Expected behaviour

All entries that don't have the specified fields simply show blank.
### Actual behaviour

The data from the previous entry gets output.
### Example

**Fieldset:**

``` yaml
title:
  type: title
  display: Title
is_in_stock:
  type: toggle
  display: In Stock?
quantity:
  type: text
  display: Quantity Available
price:
  type: text
  display: Price
```

**Entry 1:**

``` yaml
title: Product 1
is_in_stock: true
quantity: 4
price: 100
```

**Entry 2:**

``` yaml
title: Product 2
```

**Template:**

``` html
<h1>{{ title }}</h1>
<p>Is it in stock? {{ is_in_stock }}</p>
<p>Quantity: {{ quantity }}</p> 
<p>Price: {{ price }}</p>
```
