### ISSUE TITLE
B19: Some fieldtype defaults aren't saved to entry's .yaml file (eg: false or "")

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#515]
### Steps to reproduce
1. Assign a default of `false` to a toggle fieldtype, or an empty string `""` to a text fieldtype.
2. Save an entry.
3. Check the entry's .yaml file.
### Expected behaviour

The fields with a specified default (that weren't edited while creating the entry) should be saved with the default value in the entry's .yaml file. Even if the default is `false` or `""`.
### Actual behaviour

The fields don't show up at all in the .yaml file.
### Example

**Fieldset:**

``` yaml
title:
  type: title
  display: Title
is_in_stock:
  type: toggle
  display: In Stock?
  default: false # when using "false" instead, the field gets passed as true which shouldn't happen
quantity:
  type: text
  display: Quantity Available
  default: "" # doesn't get saved
price:
  type: text
  display: Price
  default: " " # leaving a space does work
```

**Entry 1:**

``` yaml
title: Product
price: " " 
```
