### ISSUE TITLE
B19: Setting fieldtype to 'required: true' doesn't do anything

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#516]
### Steps to reproduce
1. Set a fieldtype to `required: true`.
2. Create a new entry (via CP), leaving the `required` field blank.
3. Saves like normal without raising any errors or stopping the entry from saving.
### Expected behaviour

Some sort of alert should pop up raising the issue, or the fieldtype in question should get highlighted with a message. Either way, it should not get saved!
### Actual behaviour

Entry gets saved like normal.
### Quick note

Checked the docs and I don't actually see the required option being available to fieldtypes. However, after creating a new fieldset and using it; each fieldtype automatically gets assigned `required: false`, which gave me the impression that it should be available to use.
### Example

**Fieldset:**

``` yaml
title:
  type: title
  display: Title
quantity:
  type: text
  display: Quantity Available
  required: true # shouldn't save if left blank
price:
  type: text
  display: Price
  required: true # shouldn't save if left blank
```

**Entry 1:**

``` yaml
title: Product
```
