### ISSUE TITLE
locales settings in environments not picked up by app?

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#519]
I put the following in my `site/settings/environments/staging`

```
locales:
  en:
    name: English
    url: http://staging.domain.tld/
    full: en_US
```

and I noticed that `{{ site_url }}` is still pointing to the one set in the `site/settings/system.yaml`

FYI: `environment` variable works fine.
