### ISSUE TITLE
Form emails: subject not set

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#525]
I have a contact form with the following email:

```
email:
  - 
    to: me@mysite.com
    from: me@mysite.com
    subject: '-- form contact --'
```

However, whether just logging emails or using SMTP, no subject is set when the email is sent.
