### ISSUE TITLE
Enable Redactor settings

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#53]
I tried adding custom redactor settings in the field type and it's not reflected in the redactor itself. 

Is it even hooked up yet?

```
  content:
    type: redactor
    display: Body
    localizable: true
    settings:
      air: false
      toolbarFixed: false
      placeholder: Please enter content here...
```
