### ISSUE TITLE
Macro returns error

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#530]
**macro in question**

```
macros:
  class_list:
    join: true
    remove_left: .
```

**Error message**

```
[2016-03-09 18:01:09] dev.NOTICE: Invalid argument supplied for foreach()  
[2016-03-09 18:01:09] dev.ERROR: Cannot render an array variable as a string: {{ tags|macro:class_list }}  
```
