### ISSUE TITLE
Use conditions on arrays

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#533]
Given data like so:

```
social:
  - 
    network: twitter
    link: http://twitter.com/_pulkitagrawal
  - 
    network: medium
    link: http://medium.com/@_pulkitagrawal
```

Would be great if we could use the conditions `is`, etc on it to grab specific data.
