### ISSUE TITLE
Suggest field is not rendered correctly

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#606]
### Steps to reproduce
1. Create a suggest fieldtype with a bunch of options

### Expected behaviour
When selected, fieltype should show the selection

### Actual behaviour
See below

![suggest-bug](https://cloud.githubusercontent.com/assets/1151181/14589674/59dac6aa-04be-11e6-8682-cc2849992059.gif)

Fieldtype setting
```
  year:
    type: suggest
    display: Year
    options:
      2011:
      2012:
      2013:
      2014:
      2015:
      2016:
      2017:
    create: false
```

**Comment by jackmcdade** [comment]
With that particular YAML format, you're setting the `value` to the year, and the `label` to `""` an empty string. You can either do this (and have the value and label be the same)
```
 year:
    type: suggest
    display: Year
    options:
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
    create: false
```
Or this, and specify the `value` and the `label`.
```
 year:
    type: suggest
    display: Year
    options:
      2011: 2011
      2012: 2012
      2013: 2013
      2014: 2014
      2015: 2015
      2016: 2016
      2017: 2017
    create: false
```
