### ISSUE TITLE
Clicking a checkbox in a grid > grid affects first-level grid's checkboxes.

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#610]
### Steps to reproduce

Use this fieldset to create content:

``` yaml
title: Membership
fields:
  default_fieldset:
    type: partial
    display: Default Fieldset
    fieldset: default
  plans:
    type: grid
    display: Plans
    fields:
      name:
        type: text
        display: Name
        instructions: null
      price:
        type: text
        display: Price
        instructions: |
          Leave off the currency symbol.
          **Ex.** *0, 9.99, 15*
        validate:
        width: 33
      unit:
        type: text
        display: Unit
        instructions: '**Ex.** */ user / month*'
        width: 33
      condition:
        type: text
        display: Condition
        instructions: '**Ex.** *starting at 5 users*'
        width: 33
      cta_text:
        type: text
        display: CTA text
        instructions: '**Ex.** *Get started, Try it free*'
      purchase_now:
        type: checkboxes
        display: Purchase now?
        instructions: null
        options:
          true: Check this box to add an option to skip the trial and purchase immediately.
      features:
        type: grid
        display: Features
        instructions: null
        fields:
          feature:
            type: text
            display: Feature
            instructions: null
          crossed_out:
            type: checkboxes
            display: Crossed out?
            instructions: "This tells the member what they miss out on if they don't subscribe to a higher-level plan."
            options:
              true: Check this box to cross out the text.
        mode: table
        max_rows: null
        min_rows: null
    mode: stacked
  section_on_site_cta:
    type: section
    display: On-site CTA
  on_site_title:
    type: text
    display: On-site Title
  on_site_price:
    type: text
    display: Price
    width: 50
    instructions: '**Ex.** *session, week, month*'
  on_site_unit:
    type: text
    display: Unit
    width: 50
    instructions: '**Ex.** *session*'
  on_site_description:
    type: textarea
    display: Description
  on_site_label:
    type: text
    display: Email Label
```
### Expected behaviour

The clicked _Crossed out?_ checkbox's state should toggle.
### Actual behaviour

A checkbox in the first plan is always toggled.
### Server configuration

**Operating system**: Mac OS X

**Web server:** [ubuntu/trusty64](https://github.com/thefriendlybeasts/vagrant-statamic)

**PHP version:** 5

**Statamic version:** 2.0.1

**Updated from an older Statamic or fresh install:** 2.0.0 (and betas before, maybe alphas)

**List of installed addons:** Fawn
### Logs

No errors logged.
