### ISSUE TITLE
Display key doesn't update label for title field

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#620]
### Steps to reproduce
1. Create a fieldset with:
   
   ``` yaml
   title:
    type: title
    display: Name
    localizable: true
    validate: required
   ```
2. Assign it to a collection
3. Add an entry
### Expected behaviour

Instead of the label showing "Title," it should show "Name."
### Actual behaviour

Label says "Title."
