### ISSUE TITLE
{{ date_group }} not localizable 

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#635]
### Steps to reproduce
1. Use the `{{ collection:with group_by_date="Y M" }}`
2. Use `{{ date_group }}`
3. ...

### Expected behaviour
Date Group should output the date! :)
… well it does, **but it's not localizable**

### Actual behaviour
Date Group outputs the date! In english only :(.

**Statamic version:**
2.0.2

**Comment by jackmcdade** [comment]
That tag itself cannot be, but perhaps you can combine with <https://docs.statamic.com/reference/modifiers/format_localized>?

**Comment by jasonvarga** [comment]
Got some ideas.

**Comment by andypillip** [comment]
The `format_localized` modifier uses the OS's locale, instead of Statamic's!

It would be very nice to have the locale there, which is possible by means of PHP (as long as the locale is installed on the system).

Otherwise I'd find it nice if you could define a default _date-format_ in your system settings, under the locales:

```
locales:
  en:
    full: en_US
    name: English
    url: http://example.com/
    date_format: Y-m-d
  de:
    full: de_DE
    name: German
    url: http://example.com/de/
    date_format: y.m.Y
```
