### ISSUE TITLE
Allow the relate tag to access single assets rather then requiring a loop

### ISSUE THREAD

**Issue by tyvdh** [statamic/v2-hub#684]
Assuming this in the yaml:
```yaml
academy_tag: 963f4167-034c-4029-9fd8-0a526f84081d
```

And these values for that tag:
```yaml
title: Starting a Business
color: '#e35f6e'
id: 963f4167-034c-4029-9fd8-0a526f84081d
```

Allow this:
`{{ relate:academy_tag:color }}`

So I don't have to use this:
`{{ relate:academy_tag }}{{ color }}{{ /relate:academy_tag }}`
