### ISSUE TITLE
FR: Add ability to rename asset filename from CP

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#699]
This is a nice-to-have function, especially for clients.

**Comment by ericwenger** [comment]
When the SEO team goes through the site, it would be a lot easier for them to rename the files than download them (which isn't easy to do right now either) and re-upload and re-reference. Good feature to add.

**Comment by peda** [comment]
@ericwenger I found a way to "hack" this feature at least for all images generated using Glide

1. I've created an addon (https://github.com/peda/statamic-glide-vanity-url) to include the filename in Glide URLs
2. create a custom fieldset called "asset" - like the following one:
```
title: Asset
hide: true
fields:
  title:
    display: Title
    type: text
    instructions: The display name of the asset.
  alt:
    display: Alt Text
    type: text
    instructions: An alternate name for accessibility.
  filename:
    type: text
    display: Filename
    instructions: null
```
3. Just change the file `GlideVanityUrlBuilder` (from my addon) to use the field `filename` instead of `basename()`

I'm outputting every image with glide (as it can also be called without any modification parameters), so I can always show the image name I want to have. By putting the filename inside a grid or replicator you could even localize it.
