### ISSUE TITLE
Glide returns "signature is not valid" if the image filename is not web-friendly 

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#710]
### Steps to reproduce
1. Upload an image with spaces in the filename
2. Use glide tag to display your image
### Expected behaviour

Glide should process the image per your parameters
### Actual behaviour

Glide returns image not found. When you try to visit the image url, you'll get `signature is not valid` error
### Server configuration

**Operating system**: El Cap latest

**Web server:** Valet

**PHP version:** 7.x

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** updated

**List of installed addons:**
too many to list

**Comment by johnmeilleur** [comment]
I get this behaviour with a new install (v2.0.5) with the Redwood theme.

**Comment by jasonvarga** [comment]
What does your glide tag look like?

**Comment by lesaff** [comment]
**Glide tag**
```
{{ asset:cover }}
    <a href="{{ url }}" class="fancybox-thumb" rel="gallery" title="{{ label }}">
        <figure class="uk-overlay uk-overlay-hover">
            <img src="{{ glide src="{cover}" width="150" height="150" fit="crop" filename="{file}" quality="75" }}" alt="{{ label }}" />
        </figure>
    </a>
{{ /asset:cover }}
```

**Fieldset (for reference)**
```
  gallery:
    type: replicator
    display: Gallery
    sets:
      gallery_block:
        display: Gallery Block
        fields:
          gallery_title:
            type: text
            display: Gallery Block
          media:
            type: grid
            display: Media
            fields:
              label:
                type: text
                display: Label
                instructions: null
              caption:
                type: textarea
                display: Caption
                instructions: null
              cover:
                type: assets
                display: Cover
                instructions: Please provide cover image if displaying PDF
                container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
                folder: img
                max_files: 1
              file:
                type: assets
                display: File
                instructions: null
                container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
                folder: /
                max_files: 1
            mode: table
```
