### ISSUE TITLE
FR: Allow parameter(s) in SuggestMode

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#732]
Currently, we have to create a separate addon for every `SuggestMode`. It would be nice to add a parameter to `suggest` fieldtype that can be passed on to the `SuggestMode` function.

For example, 
```
  prov:
    type: suggest
    mode: StatesProvinces
    mode_param: full
    max_items: 1
    display: Province/State
```

This will pass the parameter `full` to the `suggestions()` function and grab the appropriate array.
