### ISSUE TITLE
Password Reset Email always containing production site url

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#750]
Outgoing E-Mails always contain the production URL, and don't care about environment:

site/settings/system.yaml:
```
locales:
  en:
    full: en_US
    name: English
    url: http://example.com/
```

site/settings/environments/staging.yaml:
```
locales:
  en:
    full: en_US
    name: English
    url: http://staging.example.com/
```

«Send Password Reset Email» in CP will send an Email with a link to `http://example.com/…` in it.

Of course it should send `http://staging.example.com`.

Also, when using relative URLs (which takes less effort for configuration), it wont work at all

site/settings/system.yaml:
```
locales:
  en:
    full: en_US
    name: English
    url: /
  de:
    full: de_DE
    name: Deutsch
    url: /de/
```

**Comment by jasonvarga** [comment]
Do you have `APP_ENV=staging` in your `.env` file?

The relative URL situation is expected. Put your actual URL.

**Comment by andypillip** [comment]
Yes I do have `APP_ENV=staging` in my .env file.

**Comment by jasonvarga** [comment]
Is your locales array in the root of that file? It needs to be nested under the appropriate sections.

```
settings:
  system:
    locales:
      en:
      de:
```
