### ISSUE TITLE
Replicator sub-field retaining values across items.

### ISSUE THREAD

**Issue by mikegraham00** [statamic/v2-hub#761]
### Steps to reproduce
1. Create a replicator field and sub-field A.
2. Create an item and enter a value in sub-field A.
3. Create another item and leave sub-field A blank.

```
section_content_blocks:
      - 
        type: simple_content_set
        heading: Listed Items
        subheading: Sub Heading
section_content_blocks:
      - 
        type: image_and_text_set
        heading: Heading
```
### Expected behaviour

When output in a template, the second iteration of the replicator items should not have a value for sub-field A. EX: {{ subheading }} in example above should not output anything
### Actual behaviour

When output in a template, the second iteration of the replicator items has a value for sub-field A.
EX: {{ subheading }} in example above outputs the value of the previous item's {{ subheading }}.
Have seen this behavior with text and toggle fieldtypes.
### Server configuration

**Operating system**:

**Web server:**
MAMP
**PHP version:**
5.6.2
**Statamic version:**
2.0.9
**Updated from an older Statamic or fresh install:**
updated
**List of installed addons:**
none

**Comment by jasonvarga** [comment]
Can you confirm your data?

What does this mean?

```
section_content_blocks:
      - 
        type: simple_content_set
        heading: Listed Items
        subheading: Sub Heading
section_content_blocks:
      - 
        type: image_and_text_set
        heading: Heading
```

Looks like you have two separate replicator fields with the same field name. Is this a copy paste error?

**Comment by mikegraham00** [comment]
Not an error. I just didn't give enough info. This is a replicator inside a grid. Is that a no-no?
Here's the full (giant) fieldset:
```
title: Content Fields
hide: true
fields:
  content_section:
    type: grid
    display: Content Section
    fields:
      background_style:
        type: select
        display: Background Style
        instructions: Light or dark?
        options:
          light: Light
          dark: Dark
        default: dark
      section_content_blocks:
        type: replicator
        display: Section Content Blocks
        instructions: null
        sets:
          simple_content_set:
            display: Simple Content
            instructions:
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              subheading:
                type: text
                display: Subheading
                instructions: null
              content:
                type: redactor
                display: Content
                instructions: null
                settings: Standard
                container: images
                folder: /
              cta:
                type: text
                display: Call To Action
                instructions: null
              cta_url:
                type: text
                display: Call to Action URL
                instructions: null
          logo_grid_set:
            display: Logo Grid
            instructions:
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              logos:
                type: assets
                display: Logos
                instructions: null
                container: images
                folder: /
                max_files: null
          deco_grid_set:
            display: Deco Block Grid
            instructions: Produces a grid of boxes with decorative borders.
            fields:
              heading:
                type: text
                display: heading
                instructions: null
              grid_items:
                type: grid
                display: Grid Items
                instructions: null
                fields:
                  heading:
                    type: text
                    display: Heading
                    instructions: null
                  content:
                    type: textarea
                    display: Content
                    instructions: null
                  call_to_action_url:
                    type: text
                    display: Call to Action URL
                    instructions: null
                  call_to_action_text:
                    type: text
                    display: Call to Action Text
                    instructions: null
                mode: stacked
                max_rows: null
                min_rows: null
          gallery_set:
            display: Gallery Slider
            instructions:
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              gallery_images:
                type: assets
                display: Gallery Images
                instructions: null
                container: images
                folder: /
                max_files: null
          photo_grid_set:
            display: Photo Grid
            instructions: >
              Produces a grid of photos with title underneath each one. Could be used to display Member/Officer
              headshots.
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              subheading:
                type: text
                display: Subheading
                instructions: null
              grid_items:
                type: grid
                display: Grid Items
                instructions: null
                fields:
                  photo:
                    type: assets
                    display: Photo
                    instructions: null
                    container: images
                    folder: /
                    max_files: 1
                  photo_title:
                    type: text
                    display: Photo Title
                    instructions: null
                  photo_subtitle:
                    type: text
                    display: Photo Subtitle
                    instructions: null
                mode: table
                max_rows: null
                min_rows: null
          text_list_grid_set:
            display: Text List Grid
            instructions:
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              grid_items:
                type: list
                display: Grid Items
                instructions: null
          image_and_text_set:
            display: Image and Text Block
            instructions: Produces a block with image in one half and text in the other half.
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              subheading:
                type: text
                display: Subheading
                instructions: null
              image:
                type: assets
                display: Image
                instructions: null
                container: images
                folder: /
                max_files: 1
                width: 50
              text:
                type: redactor
                display: Text
                instructions: null
                settings: Standard
                container: null
                folder: null
              cta:
                type: text
                display: Call To Action
                instructions: null
              cta_url:
                type: text
                display: Call To Action URL
                instructions: null
          image_and_link_set:
            display: Image and Link Blocks
            instructions:
            fields:
              heading:
                type: text
                display: Heading
                instructions: null
              image_blocks:
                type: grid
                display: Image Blocks
                instructions: null
                fields:
                  image:
                    type: assets
                    display: Image
                    instructions: null
                    container: images
                    folder: /
                    max_files: 1
                    width: 50
                  block_title:
                    type: text
                    display: Block Title
                    instructions: null
                    width: 25
                  block_url:
                    type: text
                    display: Block URL
                    instructions: null
                    width: 25
                mode: table
                max_rows: null
                min_rows: null
    mode: stacked
```
