### ISSUE TITLE
Error when saving with multiple grid rows and asset images

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#778]
### Steps to reproduce
It's hard to reproduce the steps exactly. I have with a min and max of 3 rows. Each row has an image and three text boxes.

### Expected behaviour
Should be able to save entries.

### Actual behaviour
When adding and removing images, at times I will receive the error `There was a problem saving the data. Please check your logs.`. 

I can reproduce this on my staging server (Linode) and local Mamp and Valet.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**PHP version:** 7

**Statamic version:** 2.0.11

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

#### Web server error log
```

#### Statamic error log (`/local/storage/logs/statamic.log`)

[2016-06-24 19:07:54] local.ERROR: ErrorException: include(/Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/../../bundles/StaticPageCache/StaticPageCacheAPI.php): failed to open stream: No such file or directory in /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/jeremyho...', 412, Array)
#1 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(412): include()
#2 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/jeremyho...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Statamic\\Addons...')
#4 [internal function]: spl_autoload_call('Statamic\\Addons...')
#5 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('Statamic\\Addons...')
#6 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Addons...', Array)
#7 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Addons...', Array)
#8 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(62): Illuminate\Foundation\Application->make('Statamic\\Addons...', Array)
#9 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/bootstrap/helpers.php(362): app('Statamic\\Addons...')
#10 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(17): addon('StaticPageCache')
#11 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->__construct()
#12 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(Array)
#13 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Http\\M...', Array)
#14 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Http\\M...', Array)
#15 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(123): Illuminate\Foundation\Application->make('Statamic\\Http\\M...')
#16 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /Users/jeremyhoover/Sites/cedarsprings-ca/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}  
[2016-06-24 19:07:54] local.ERROR: ErrorException: include(/Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/../../bundles/StaticPageCache/StaticPageCacheAPI.php): failed to open stream: No such file or directory in /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/jeremyho...', 412, Array)
#1 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(412): include()
#2 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/jeremyho...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Statamic\\Addons...')
#4 [internal function]: spl_autoload_call('Statamic\\Addons...')
#5 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('Statamic\\Addons...')
#6 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Addons...', Array)
#7 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Addons...', Array)
#8 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(62): Illuminate\Foundation\Application->make('Statamic\\Addons...', Array)
#9 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/bootstrap/helpers.php(362): app('Statamic\\Addons...')
#10 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(17): addon('StaticPageCache')
#11 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->__construct()
#12 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(Array)
#13 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Http\\M...', Array)
#14 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Http\\M...', Array)
#15 /Users/jeremyhoover/Sites/cedarsprings-ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Foundation\Application->make('Statamic\\Http\\M...')
#16 /Users/jeremyhoover/Sites/cedarsprings-ca/public/index.php(160): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#17 {main}  
```

**Comment by jackmcdade** [comment]
Can you share your config? I can’t recreate this.

**Comment by jeremydouglas** [comment]
My fieldset, if that's what you mean:

```
title: Product
hide: true
fields:
  title:
    type: title
    display: Product Name
  category:
    type: select
    display: Category
    options:
      front_yard: Front Yard
      backyard: Backyard
  variants:
    type: grid
    display: Variants
    fields:
      photo:
        type: assets
        display: Photo
        instructions: null
        container: 42dc3633-92e2-4e03-812d-9df994e3122a
        folder: /
        max_files: 1
        width: 50
      description:
        type: textarea
        display: Short Description
        instructions: null
        width: 50
      min_price:
        type: text
        display: Minimum Price
        instructions: The minimum price in thousands. (i.e. "2.5" _not_ "$2500")
        validate: numeric
        width: 25
      max_price:
        type: text
        display: Maximum Price
        instructions: The maximum price in thousands. (i.e. "24" _not_ "$24,000")
        validate: numeric
        width: 25
    mode: stacked
    max_rows: 3
    min_rows: 3
```

**Comment by jeremydouglas** [comment]
I tried rolling back to 2.0.5 and that fixed the issue. But, there will be other issues if I stay back there.

**Comment by jeremydouglas** [comment]
Update: Removing the grid rows, then adding them back again fixes things. I'll try and see what I can figure out further.

**Comment by jackmcdade** [comment]
Curious... Makes me wonder what the data was when it wasn't working...

**Comment by jeremydouglas** [comment]
I believe this it:

```
title: Gardens
category: backyard
variants:
  - 
    photo: 1a703d97-6cf9-404d-b77d-0bfabf31e272
    description: Description
    min_price: 15
    max_price: 25
  - [ ]
  - [ ]
id: dae9f213-da89-4e58-8331-2e5cc6ae84ce
```
