### ISSUE TITLE
FR Make environment variables available in container.yaml files

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#790]
We keep our filesystems out of our repo. This structure allows us to maintain the same data across pushes, without having to track it. Remotely it looks like this:

```
{{ site }}/
  staging/
    data/
      assets/
      content/
      storage/
      users/
    releases/
      {{ timestamp }}/
        html/
          local/
          site/
          statamic/
          …
    current (symlink to ./releases/{{ timestamp }})
```

In our `container.yaml` files, we have to set `path` to `../../../data/assets/{{ container }}`.

However, since locally we don't have the same structure as Envoyer, we need to set `container.yaml` `path`s to `../data/assets/{{ container }}`. Here's the local structure:

```
data/
  assets/
  content/
  storage/
  users/
html/
  local/
  site/
  statamic/
  …
```

If we could use the environment variable we're already using in `system.yaml` for each filesystem's `root`, we wouldn't have to manually update our `container.yaml` files.

```yaml
filesystems:
  content:
    driver: local
    root: '{env:APP_SYSTEM_FILESYSTEMS_ROOT_PATH}/content'
  storage:
    driver: local
    root: '{env:APP_SYSTEM_FILESYSTEMS_ROOT_PATH}/storage'
  users:
    driver: local
    root: '{env:APP_SYSTEM_FILESYSTEMS_ROOT_PATH}/users'
  themes:
    driver: local
    root: site/themes
    url: /site/themes
```
