### ISSUE TITLE
Instructions aren't showing for the title field

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#814]
### Steps to reproduce

Add instructions to the yaml for the title field in a fieldset. Please note that this is for a collection.

```
fields:
  title:
    type: title
    display: Title
    localizable: true
    validate: required
    instructions: This field will only show on the website if you also enter a description.
```

![instructions-are-missing-for-title-field](https://cloud.githubusercontent.com/assets/1793867/16895061/ab07ffd8-4b37-11e6-8f93-c8a0a8be8e03.gif)
### Expected behaviour

The instructions should show in the control panel under the title heading.
### Actual behaviour

The instructions don't show.
### Server configuration

Linux, latest versions of all software, fresh install, no addons.
#### Web server error log

none
#### Statamic error log (`/local/storage/logs/statamic.log`)

none
#### Browser log

none
