### ISSUE TITLE
Redactor assets button doubled up

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#828]
### Steps to reproduce
1. Add multiple Redactor fieldsets in your data entry page
2. Point each Redactor field to an asset container
### Expected behaviour

Assets icon should appear as one of your Redactor buttons.
### Actual behaviour

The first Redactor field works as expected, any subsequent fields show multiple Assets buttons (see screenshot below)

![screen shot 2016-07-29 at 8 10 23 am](https://cloud.githubusercontent.com/assets/1151181/17246758/7b421a36-5564-11e6-9db9-865e1d7529bd.png)
### Fieldset config

```
  summary:
    type: redactor
    display: Summary
    localizable: true
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: /
  content:
    type: redactor
    display: Content
    localizable: true
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: /
```
### Server configuration

**Operating system**: El Capitan [latest]

**Web server:** Valet 1.1.13

**PHP version:** 7.0.x

**Statamic version:** 2.0.11

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:**
