### ISSUE TITLE
Localization Slug Issue

### ISSUE THREAD

**Issue by mc72** [statamic/v2-hub#855]
### Steps to reproduce
1.  Edit and save a localized page in the cp
2. Go to that page in the front end

### Expected behaviour
Should display the localized content on the proper url

### Actual behaviour
- Slug field is removed from the localized cp and therefore no longer editable.
- Pages slug is now / , and therefore conflicts with the home page.  Localized home page content is now replaced by the new page's content.
- attempting to manually add a slug variable doesn't seem to do anything?

### Server configuration
Mac OSX El Capitan  v10.11.6

**Web server:**
Mamp Pro
Using sample .htaccess and trail guide instructions on updating index.php

**PHP version:**
7.0.8

**Statamic version:**
2.1.2

**Updated from an older Statamic or fresh install:**
Fresh install using the default setup/content/redwood theme.

**List of installed addons:**

none

![statamic-localize-this](https://cloud.githubusercontent.com/assets/8703845/17631863/a84a30e2-607a-11e6-9fdf-18636754390a.gif)

**Comment by jackmcdade** [comment]
Is your base locale something other than English?

**Comment by mc72** [comment]
No, english is the base language

```
locales:
  en:
    name: English
    full: en_US
    url: http://statamic-212.dev:8080/
  fr:
    full: fr_FR
    name: French
    url: http://statamic-212.dev:8080/fr/
```
