### ISSUE TITLE
FR: Limit templates available

### ISSUE THREAD

**Issue by danyuk1982** [statamic/v2-hub#900]
Using the template fieldtype, this will list all available templates.

A great feature would be to limit this, i.e.

```
template:
  type: template
  available:
    - event_style_1
    - event_style_2
    - event_style_3
```

If the site has multiple, but different, collections this would allow various, but relevant, templates to be picked. 

Say there exists the following available templates:  
event_style_1 - X
blog_style_1 - X 
person_style_1 - X 

then the client should only see the relevant choices.

**Comment by jackmcdade** [comment]
You can do that with a [Select](https://docs.statamic.com/reference/fieldtypes/select) fieldtype :)

```
template:
  type: select
  options:
    - event_style_1
    - event_style_2
    - event_style_3
```
