### ISSUE TITLE
Section that is stright after title doesn't have a proper margin

### ISSUE THREAD

**Issue by wojtiku** [statamic/v2-hub#918]
Such fieldset

```
title: Test
fields:
  some_section:
    type: section
    display: Customers
```

produces this:
![image](https://cloud.githubusercontent.com/assets/650828/18118351/85b1d89e-6f54-11e6-99ab-10db7edffbbd.png)
