### ISSUE TITLE
FR: Add additional formset fields

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#929]
You probably have this on the roadmap but I wanted to document which fields I think would be useful for building a variety of different forms using the CP.
# Fields
### Type

A string to give the user flexibility to define their own fieldtypes. Here are some examples:
`text`, `email`, `date`,  `number`, `select`, `multiple`, `radio`, `checkboxes`, `checkbox`, `textarea`

Example:

```
comment:
    display: Anything else you would like to share?
    type: textarea
```
### Description

A string to add additional instructions or help text.

```
email:
    display: "What's your email?"
    type: email
    description: We will get your company name from your email domain
```
### Options

A grid or array fieldtype for defining options for Select, Radio and Checkboxes.

```
role:
    display: What is your role?
    type: radio
    options:
      - 
        name: executive
        value: Executive team
      - 
        name: product
        value: Product
      - 
        name: marketing
        value: Marketing
      - 
        name: customer-success
        value: Customer Success
      - 
        name: other
        value: Other
```
### Submit Text

Another useful field for the entire Form would be `Submit Text`. This would help users define a label for their form submit button.
# Use Case

With these fields available, I can then loop through fields in the same way as using the replicator. The example below assumes the user has "mounted" or added a `form` field to their page:

```
{{ form:create in="{form}" }}
    {{ fields }}
      <div class="form-group m-b-2">
        <label class="h6">{{ display }}</label>
        {{ if type == "textarea" }}
          <textarea name="{{ field }}" class="form-control">{{ old:comment }}</textarea>
        {{ elseif type == "select" }}
          <select name="{{ field }}" class="c-select form-control">
            {{ options }}
              <option>{{ value }}</option>
            {{ /options }}
          </select>
        {{ elseif type == "multiple" }}
          <select multiple name="{{ field }}" class="form-control">
            {{ options }}
              <option>{{ value }}</option>
            {{ /options }}
          </select>
        {{ elseif type == "checkboxes" }}
          <div class="c-inputs-stacked">
          {{ options }}
            <label class="c-input c-checkbox">
              <input type="checkbox" name="{{ field }}" value="{{ key }}">
              <span class="c-indicator"></span>
              <span class="c-description">{{ value }}</span>
            </label>
          {{ /options }}
          </div>
        {{ elseif type == "radio" }}
          <div class="c-inputs-stacked">
          {{ options }}
            <label class="c-input c-radio">
              <input name="{{ field }}" type="radio" value="{{ key }}">
              <span class="c-indicator"></span>
              <span class="c-description">{{ value }}</span>
            </label>
          {{ /options }}
          </div>
        {{ elseif type == "checkbox" }}
          <div class="form-check">
            <label class="form-check-label">
              <input type="checkbox" name="{{ field }}" class="form-check-input">
              {{ value }}
            </label>
          </div>
        {{ elseif type == "date" }}
          <input type="date" name="{{ field }}" value="{{ now format="Y-m-d" }}" class="form-control" />
        {{ elseif type != null }} <!-- For all other HTML5 fields like number and email -->
          <input type="{{ type }}" name="{{ field }}" value="{{ old }}" class="form-control" />
        {{ else }}
          <input type="text" name="{{ field }}" value="{{ old }}" class="form-control" />
        {{ /if }}
        {{ if description }}
          <small class="form-text text-muted">{{ description }}</small>
        {{ /if }}
      </div>
    {{ /fields }}
  </div>
</div>
<button class="btn btn-lg btn-block btn-primary">{{ submit_text }}</button>
{{ /form:create }}
```
