### ISSUE TITLE
Error saving when entering content in a once empty and saved field

### ISSUE THREAD

**Issue by ulysses** [statamic/v2-hub#955]
### Expected behavior

I enter content into a field, save it, all worky honkydory. 
### Actual behavior

When I enter in content and save, I get an error that says "problem saving data," a pop-up window. The error also shows in the logo. I'm unable save the added content in the admin. 
### Steps to reproduce
1.  Create a grid like:
   faq_question:
     type: grid
     display: faq_question
     fields:
       faq_question:
         type: text
         display: Question
       faq_answer:
         type: redactor
         display: Answer
         settings: Standard
     mode: stacked
     min_rows: 1
     add_row: Add FAQ
2.  Add a new row and save page **without** adding content inside of the new fields—so they're blank.
3.  Then try to add content to the empty row and save. Error happens. 
### Server configuration

**Operating system**:
Mac OS

**Web server:**
Apache
**PHP version:**
5.6.10
**Statamic version:**
2.1.10
**Updated from an older Statamic or fresh install:**

**List of installed addons:**
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Add those logs here
```

**Comment by edalzell** [comment]
this code, in `GridFieldtype.php` line 53, fixes it:
```
$field_config = Helper::ensureArray($this->getFieldConfig('fields.'.$field));
```

**Comment by ulysses** [comment]
I didn't get the error, but it also didn't save the new content I added.

**Comment by ulysses** [comment]
You meant in place of line #53, not under, correct?

**Comment by edalzell** [comment]
yes, but that comment was for the Statamic devs, not really for people...that fix may not be correct.

**Comment by ulysses** [comment]
Ah, great. I'd rather people than a dev anyway. 😎

**Comment by mikemartin** [comment]
FYI, the fix above didn't work for me.

I'm using a replicator with a suggest field. When I clear the value and Save, I get this error:
`[2016-09-19 23:56:51] dev.ERROR: ErrorException: reset() expects parameter 1 to be array, null given in /Users/mike/Sites/trychameleon/statamic/bundles/Suggest/SuggestFieldtype.php:27`

**Comment by jeremydouglas** [comment]
On a grid field, the fix from @edalzell doesn't work for me either.

Replacing the code on line 53 in `GridFieldtype.php`, I no longer receive the error, but the data from the row is no longer saved either.

My steps are the same as originally posted.

**Comment by jeremydouglas** [comment]
This is still an issue for me on V 2.1.17. I'm attaching my logs, just in case it's helpful :S
[statamic-2016-11-02.log.txt](https://github.com/statamic/v2-hub/files/567496/statamic-2016-11-02.log.txt)

**Comment by dannyuk1982** [comment]
I have just ran into this

**Comment by curtisblackwell** [comment]
I encountered this issue and Erin's fix does work for me.

**Fieldset:**
```yaml
resources:
  type: grid
  display: Resources
  fields:
    name:
      type: text
      display: Name
      instructions: null
    link_label:
      type: text
      display: Link Label
      instructions: null
      width: 33
    file:
      type: assets
      display: File
      instructions: 'This field overrides **Page**.'
      container: file
      folder: /
      max_files: "1"
      width: 33
    page:
      type: pages
      display: Page
      instructions: null
      parent: null
      depth: null
      max_items: "1"
      sort: null
      label: '{{ title }}'
      mode: tags
      width: 33
```

**Content:**
```yaml
resources:
  - [ ]
  - [ ]
```
